name: obe
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pyside6=6.10.2
  - openpyxl=3.1.5
  - xlsxwriter=3.2.9
  - pytest=9.0.2
  - pip:
      - pyqtdarktheme==2.1.0
      - pyflakes==3.4.0
      - pip-audit==2.9.0
