"""English text catalog for user-facing strings."""

TEXTS = {
    # Startup / main
    "app.already_running": "Application is already running.",
    "app.unexpected_error": "An unexpected error occurred. Please check the log file.",
    "app.main_window_title": "FOCUS",
    "splash.starting": "Starting application...",
    "splash.loading_main_window": "Loading main window...",
    # Main window
    "toolbar.navigation": "Navigation",
    "status.ready": "Ready",
    "module.placeholder": "{title} module is not yet implemented.",
    "module.instructor": "Instructor",
    "module.course_coordinator": "Course Coordinator",
    "module.coordinator_short": "Coordinator",
    "module.po_analysis": "PO Analysis",
    "module.load_failed_title": "Module Load Error",
    "module.load_failed_body": "Could not load module '{module}'.\n\nDetails: {error}",
    "module.load_failed_status": "Failed to load module: {module}.",
    "nav.help": "Help",
    "nav.about": "About",
    # Settings module
    "settings.title": "Application Settings",
    "settings.theme": "Theme",
    "settings.language": "Language",
    "settings.theme.system": "System",
    "settings.theme.light": "Light",
    "settings.theme.dark": "Dark",
    "settings.apply": "Apply",
    "settings.saved.title": "Settings Updated",
    "settings.saved.body": "Language preference was applied.",
    "settings.saved.status": "Settings applied.",
    "language.switcher.button": "Language: {language}",
    "language.switcher.status": "Language {language}",
    "language.switcher.applied_status": "Language set to {language}.",
    # About
    "about.version": "Version {version}",
    "about.description": (
        "{app_name} is a software tool designed for computing Course Outcome (CO) "
        "attainment and performing structured outcome analysis based on direct "
        "and indirect assessments."
    ),
    "about.institution": "Developed at Kalasalingam Academy of Research and Education (KARE).",
    "about.copyright": "(c) {year} KARE. All rights reserved.",
    # Help module
    "help.doc_missing_title": "Help Document Missing",
    "help.doc_missing_body": "Could not find help PDF:\n{path}",
    "help.doc_error_title": "Help Document Error",
    "help.doc_error_body": "Failed to load help PDF.",
    "help.download_pdf": "Download PDF",
    "help.open_default_viewer": "Open in Default Viewer",
    "help.missing_file_title": "Missing File",
    "help.missing_file_body": "Help PDF is not available.",
    "help.save_title": "Save CO Attainment Document",
    "help.save_default_name": "CO_Calculation_Document.pdf",
    "help.save_filter_pdf": "PDF Files (*.pdf)",
    "help.save_failed_title": "Save Failed",
    "help.save_failed_body": "Error happened while saving help PDF.",
    "help.save_success_title": "Saved",
    "help.save_success_body": "Help PDF saved successfully.",
    "help.open_failed_title": "Open Failed",
    "help.open_failed_body": "Could not open help PDF in the default viewer.",
    "help.open_success_title": "Opened",
    "help.open_success_body": "Help PDF opened in the default viewer.",
    "help.status.doc_loaded": "Help document loaded.",
    "help.status.doc_missing": "Help document is missing.",
    "help.status.doc_error": "Failed to load help document.",
    "help.status.file_missing": "Help PDF is not available.",
    "help.status.save_success": "Help PDF saved successfully.",
    "help.status.save_failed": "Error happened while saving help PDF.",
    "help.status.open_success": "Help PDF opened in default viewer.",
    "help.status.open_failed": "Error happened while opening help PDF in default viewer.",
    # Instructor module
    "instructor.workflow_title": "CO Workflow",
    "instructor.progress": "{completed} / {total} completed",
    "instructor.step_button": "{number}. {title}",
    "instructor.step1.title": "Download Course Template",
    "instructor.step2.title": "Generate Marks Template",
    "instructor.step3.title": "Generate CO Marks Report",
    "instructor.step4.title": "Upload Filled Marks",
    "instructor.step5.title": "Generate Final CO Report",
    "instructor.step1.desc": "Download the blank template used for entering course details.",
    "instructor.step2.desc": "Upload the validated course-details file, then prepare and save the marks template.",
    "instructor.step3.desc": "Upload and validate the filled marks workbook, then generate the final CO report.",
    "instructor.step4.desc": "Upload the filled marks workbook.",
    "instructor.step5.desc": "Generate the final workbook with computed CO totals per student.",
    "instructor.badge.pending": "Pending",
    "instructor.badge.done": "Done",
    "instructor.badge.needs_update": "Needs update",
    "instructor.links.title": "Generated Outputs",
    "instructor.links.course_details_generated": "Course details template generated",
    "instructor.links.course_details_uploaded": "Course details file uploaded",
    "instructor.links.marks_template_generated": "Marks template generated",
    "instructor.links.marks_template_uploaded": "Marks template uploaded",
    "instructor.links.final_co_report_generated": "Final CO report generated",
    "instructor.links.open_file": "Open file",
    "instructor.links.open_folder": "Open folder",
    "instructor.links.not_available": "Not available yet",
    "instructor.links.open_failed": "Unable to open the selected path.",
    "instructor.file.none": "No file/path selected yet.",
    "instructor.note.default": "You can return and replace any completed step.",
    "instructor.note.outdated_current": "This step is outdated. Run this step again.",
    "instructor.note.outdated_downstream": "An upstream change was made. Downstream steps may need regeneration.",
    "instructor.active_title": "Step {number}: {title}",
    "instructor.action.step1.default": "Download Template",
    "instructor.action.step1.redo": "Redownload Template",
    "instructor.action.step2.default": "Upload & Build Marks Template",
    "instructor.action.step2.redo": "Replace & Rebuild Marks Template",
    "instructor.action.step2.upload": "Upload Course Details",
    "instructor.action.step2.prepare": "Prepare Marks Template",
    "instructor.action.step4.default": "Upload Filled Marks",
    "instructor.action.step4.redo": "Replace Filled Marks",
    "instructor.action.step5.default": "Generate Final CO Report",
    "instructor.action.step5.redo": "Regenerate Final CO Report",
    "instructor.require.step2": "Complete Step 2 first.",
    "instructor.require.step3": "Complete Step 3 first.",
    "instructor.msg.success_title": "Success",
    "instructor.msg.validation_title": "Validation Error",
    "instructor.msg.error_title": "Failed",
    "instructor.msg.step_completed": "Step {step} completed: {title}.",
    "instructor.msg.failed_to_do": "Failed to do {action}.",
    "instructor.msg.step_required_title": "Step Required",
    "instructor.dialog.filter.excel": "Excel Files (*.xlsx)",
    "instructor.dialog.filter.excel_open": "Excel Files (*.xlsx *.xlsm *.xls)",
    "instructor.dialog.step1.title": "Save Course Details Template",
    "instructor.dialog.step1.default_name": "course_details_template.xlsx",
    "instructor.dialog.step2.title": "Select Course Details File",
    "instructor.dialog.step3.title": "Select Filled Marks File",
    "instructor.dialog.step3.default_name": "marks_template.xlsx",
    "instructor.dialog.step4.title": "Save Final CO Report",
    "instructor.dialog.step4.default_name": "co_report.xlsx",
    "instructor.status.step1_selected": "Template download path selected.",
    "instructor.status.step2_validated": "Course details uploaded and validated. You can now prepare marks template.",
    "instructor.status.step2_uploaded": "Marks template generated.",
    "instructor.status.step2_changed": "Course details changed. Redo downstream steps.",
    "instructor.status.step3_selected": "Marks template generated.",
    "instructor.status.step3_uploaded": "Filled marks uploaded.",
    "instructor.status.step3_changed": "Filled marks changed. Regenerate final report.",
    "instructor.status.step4_selected": "Final CO report path selected.",
    "instructor.status.step4_changed": "Filled marks changed. Regenerate final report.",
    "instructor.status.step5_selected": "Final CO report path selected.",
    "instructor.status.operation_in_progress": "Operation in progress...",
    "instructor.status.operation_cancelled": "Operation cancelled.",
    "instructor.timer.idle": "",
    "instructor.timer.running": "Running... {elapsed}",
    "instructor.log.title": "Activity Log",
    "instructor.log.ready": "Activity log initialized.",
    "instructor.log.completed_process": "{process} completed successfully.",
    "instructor.log.error_while_process": "Error happened while {process}.",
    "instructor.log.process.generate_course_details_template": "generating course details template",
    "instructor.log.process.validate_course_details_workbook": "validating uploaded course details workbook",
    "instructor.log.process.generate_marks_template": "generating marks template",
    "instructor.log.process.upload_filled_marks_workbook": "uploading filled marks workbook",
    "instructor.log.process.generate_final_co_report": "generating final CO report",
    "instructor.validation.xlsxwriter_missing": "xlsxwriter is not installed. Install it to generate course templates.",
    "instructor.validation.sheet_single_header_row": "Sheet '{sheet_name}' must define exactly one header row.",
    "instructor.system.template_generate_failed": "Failed to generate course details template at '{output}'.",
    "instructor.validation.unknown_template": "Unknown workbook template '{template_id}'. Available templates: {available}.",
    "instructor.validation.invalid_sheet_name": "Invalid sheet name.",
    "instructor.validation.headers_empty": "Headers cannot be empty for sheet '{sheet_name}'.",
    "instructor.validation.headers_unique": "Headers must be unique for sheet '{sheet_name}'.",
    "instructor.validation.row_length_mismatch": "Row {row} length mismatch in '{sheet_name}': expected {expected}, got {found}.",
    "instructor.validation.openpyxl_missing": "openpyxl is not installed. Install it to validate uploaded course details.",
    "instructor.validation.workbook_not_found": "Course details workbook not found: {workbook}",
    "instructor.validation.workbook_open_failed": "Unable to open course details workbook '{workbook}'.",
    "instructor.validation.system_sheet_missing": "Missing required system sheet '{sheet}' in uploaded workbook.",
    "instructor.validation.system_hash_missing_template_id_header": "Invalid system hash sheet format: missing Template_ID header.",
    "instructor.validation.system_hash_missing_template_hash_header": "Invalid system hash sheet format: missing Template_Hash header.",
    "instructor.validation.system_hash_template_id_missing": "Template_ID is missing in system hash sheet.",
    "instructor.validation.system_hash_mismatch": "Template hash mismatch. Please use a valid generated template.",
    "instructor.validation.workbook_sheet_mismatch": "Workbook sheets do not match template '{template_id}'. Expected: {expected}. Found: {found}.",
    "instructor.validation.header_mismatch": "Header mismatch in sheet '{sheet_name}'. Expected: {expected}.",
    "instructor.validation.unexpected_header": "Unexpected header in sheet '{sheet_name}' at column {col}.",
    "instructor.validation.validator_missing": "No validator implemented for template '{template_id}'.",
    "instructor.validation.course_metadata_field_empty": "Course_Metadata row {row}: Field cannot be empty.",
    "instructor.validation.course_metadata_duplicate_field": "Course_Metadata row {row}: duplicate field '{field}'.",
    "instructor.validation.course_metadata_unknown_field": "Course_Metadata row {row}: unknown field '{field}'.",
    "instructor.validation.course_metadata_value_required": "Course_Metadata row {row}: Value is required for '{field}'.",
    "instructor.validation.course_metadata_missing_fields": "Course_Metadata is missing required fields: {fields}.",
    "instructor.validation.course_metadata_field_must_be_int": "Course_Metadata field '{field}' must be an integer.",
    "instructor.validation.course_metadata_field_must_be_non_empty_str": "Course_Metadata field '{field}' must be a non-empty string.",
    "instructor.validation.course_metadata_total_outcomes_invalid": "Course_Metadata field 'Total_Outcomes' must be an integer > 0.",
    "instructor.validation.yes_no_required": "{sheet_name} row {row}: '{field}' must be YES or NO.",
    "instructor.validation.assessment_component_required_one": "Assessment_Config must contain at least one component.",
    "instructor.validation.assessment_component_required": "Assessment_Config row {row}: Component is required.",
    "instructor.validation.assessment_component_duplicate": "Assessment_Config row {row}: duplicate component '{component}'.",
    "instructor.validation.assessment_weight_numeric": "Assessment_Config row {row}: Weight (%) must be numeric.",
    "instructor.validation.assessment_direct_missing": "Assessment_Config must have at least one direct component.",
    "instructor.validation.assessment_indirect_missing": "Assessment_Config must have at least one indirect component.",
    "instructor.validation.assessment_direct_total_invalid": "Assessment_Config direct component weights must total 100. Found: {found}.",
    "instructor.validation.assessment_indirect_total_invalid": "Assessment_Config indirect component weights must total 100. Found: {found}.",
    "instructor.validation.question_map_row_required_one": "Question_Map must contain at least one question row.",
    "instructor.validation.question_component_required": "Question_Map row {row}: Component is required.",
    "instructor.validation.question_component_unknown": "Question_Map row {row}: unknown component '{component}'.",
    "instructor.validation.question_label_required": "Question_Map row {row}: Q_No/Rubric_Parameter is required.",
    "instructor.validation.question_max_marks_numeric": "Question_Map row {row}: Max_Marks must be numeric.",
    "instructor.validation.question_max_marks_positive": "Question_Map row {row}: Max_Marks must be greater than zero.",
    "instructor.validation.question_co_required": "Question_Map row {row}: CO must contain at least one value.",
    "instructor.validation.question_co_no_repeat": "Question_Map row {row}: CO values cannot repeat.",
    "instructor.validation.question_co_out_of_range": "Question_Map row {row}: CO value out of range 1..{total_outcomes}.",
    "instructor.validation.question_co_wise_requires_one": "Question_Map row {row}: component '{component}' requires exactly one CO per question.",
    "instructor.validation.question_duplicate_for_component": "Question_Map row {row}: duplicate question '{question}' for component '{component}'.",
    "instructor.validation.students_row_required_one": "Students sheet must contain at least one student row.",
    "instructor.validation.students_reg_and_name_required": "Students row {row}: both Reg_No and Student_Name are required.",
    "instructor.validation.students_duplicate_reg_no": "Students row {row}: duplicate Reg_No '{reg_no}'.",
    "instructor.validation.filled_marks_workbook_invalid": "Filled marks workbook is invalid or not generated by this tool.",
    "instructor.validation.step3.layout_sheet_missing": "Missing required layout sheet '{sheet}' in filled marks workbook.",
    "instructor.validation.step3.layout_header_mismatch": "Invalid layout sheet header at {column}. Expected '{expected}'.",
    "instructor.validation.step3.layout_manifest_missing": "Layout manifest or layout hash is missing in system layout sheet.",
    "instructor.validation.step3.layout_hash_mismatch": "Layout hash mismatch. Please use an untampered generated marks template.",
    "instructor.validation.step3.layout_manifest_json_invalid": "Layout manifest JSON is invalid.",
    "instructor.validation.step3.template_validator_missing": "No Step 3 validator available for template '{template_id}'.",
    "instructor.validation.step3.manifest_root_invalid": "Layout manifest root must be an object.",
    "instructor.validation.step3.manifest_structure_invalid": "Layout manifest must contain both 'sheet_order' and 'sheets'.",
    "instructor.validation.step3.sheet_order_mismatch": "Filled marks sheets mismatch. Expected order: {expected}. Found: {found}.",
    "instructor.validation.step3.manifest_sheet_spec_invalid": "Layout manifest contains an invalid sheet specification.",
    "instructor.validation.step3.sheet_missing": "Expected sheet '{sheet_name}' is missing in workbook.",
    "instructor.validation.step3.header_row_invalid": "Sheet '{sheet_name}' has invalid header row metadata: {header_row}.",
    "instructor.validation.step3.headers_missing": "Sheet '{sheet_name}' is missing expected header definitions in layout manifest.",
    "instructor.validation.step3.anchor_spec_invalid": "Sheet '{sheet_name}' has invalid anchor specification in layout manifest.",
    "instructor.validation.step3.formula_anchor_spec_invalid": "Sheet '{sheet_name}' has invalid formula anchor specification in layout manifest.",
    "instructor.validation.step3.header_row_mismatch": "Sheet '{sheet_name}' header mismatch at row {row}. Expected: {expected}.",
    "instructor.validation.step3.anchor_value_mismatch": "Sheet '{sheet_name}' cell {cell} was modified. Expected '{expected}', found '{found}'.",
    "instructor.validation.step3.formula_mismatch": "Sheet '{sheet_name}' formula at {cell} was modified.",
    "instructor.validation.step3.no_component_sheets": "No component mark-entry sheets found in filled marks workbook.",
    "instructor.validation.step3.mark_entry_empty": "Sheet '{sheet_name}' has an empty mark-entry cell at {cell}. Fill all marks before upload.",
    "instructor.validation.step3.mark_value_invalid": "Sheet '{sheet_name}' cell {cell} has invalid mark value '{value}'. Allowed: A/a or numeric between {minimum} and {maximum}.",
    "instructor.validation.step3.mark_precision_invalid": "Sheet '{sheet_name}' cell {cell} has too many decimal places in '{value}'. Maximum allowed is {decimals}.",
    "instructor.validation.step3.indirect_mark_must_be_integer": "Sheet '{sheet_name}' cell {cell} has invalid indirect mark '{value}'. Use an integer Likert value.",
    "instructor.validation.step3.absence_policy_violation": "Sheet '{sheet_name}' row {row} has mixed absence and numeric entries in {range}. Enter either all A/a or all numeric marks.",
    "instructor.validation.step3.total_formula_mismatch": "Sheet '{sheet_name}' total formula was modified at {cell}.",
    "instructor.validation.step3.co_formula_mismatch": "Sheet '{sheet_name}' CO split formula was modified at {cell}.",
    "instructor.validation.step3.structure_snapshot_missing": "Sheet '{sheet_name}' is missing mark-structure metadata in layout manifest.",
    "instructor.validation.step3.structure_snapshot_mismatch": "Sheet '{sheet_name}' mark-structure cell {cell} was modified.",
    "instructor.validation.step3.student_identity_spec_invalid": "Sheet '{sheet_name}' has invalid student identity metadata in layout manifest.",
    "instructor.validation.step3.student_identity_mismatch": "Sheet '{sheet_name}' student Reg. No./Name rows were modified.",
    "instructor.validation.step3.student_reg_duplicate": "Sheet '{sheet_name}' has duplicate student Reg. No. '{reg_no}'.",
    "instructor.validation.step3.student_identity_cross_sheet_mismatch": "Student Reg. No./Name rows in sheet '{sheet_name}' do not match sheet '{reference_sheet}'.",
    "instructor.validation.final_report.layout_manifest_invalid": "Final report generation failed: layout manifest is invalid.",
    "instructor.validation.final_report.direct_component_sheet_missing": "Final report generation failed: missing direct component sheet for '{component}'.",
    "instructor.validation.final_report.direct_component_questions_missing": "Final report generation failed: component '{component}' has no question mapping.",
    "instructor.validation.final_report.direct_component_marks_shape_invalid": "Final report generation failed: invalid marks shape for component '{component}'.",
    "instructor.validation.final_report.no_direct_components": "Final report generation failed: no direct components found.",
    # Instructor template headers / labels
    "instructor.template.headers.course_metadata.field": "Field",
    "instructor.template.headers.course_metadata.value": "Value",
    "instructor.template.headers.assessment.component": "Component",
    "instructor.template.headers.assessment.weight": "Weight (%)",
    "instructor.template.headers.assessment.cia": "CIA",
    "instructor.template.headers.assessment.co_wise_breakup": "CO_Wise_Marks_Breakup",
    "instructor.template.headers.assessment.direct": "Direct",
    "instructor.template.headers.question_map.component": "Component",
    "instructor.template.headers.question_map.question": "Q_No/Rubric_Parameter",
    "instructor.template.headers.question_map.max_marks": "Max_Marks",
    "instructor.template.headers.question_map.co": "CO",
    "instructor.template.headers.students.reg_no": "Reg_No",
    "instructor.template.headers.students.student_name": "Student_Name",
    "instructor.template.validation.direct_title": "Direct",
    "instructor.template.validation.select_yes_no": "Select YES or NO",
    "instructor.marks.validation.error_title": "Invalid marks",
    "instructor.marks.validation.error_message": "Enter A/a or a numeric mark within allowed maximum.",
    "instructor.marks.validation.indirect_error_message": "Enter A/a or a numeric Likert value within allowed range.",
    "instructor.marks.row_header.serial_no": "#",
    "instructor.marks.row_header.reg_no": "Reg. No.",
    "instructor.marks.row_header.student_name": "Student Name",
    "instructor.marks.total_label": "Total",
    "instructor.marks.co_prefix": "CO",
    "instructor.marks.question_prefix": "Q",
    "instructor.marks.co_marks_label_prefix": "Marks for CO",
    "instructor.marks.cos_label": "COs",
    # Coordinator module
    "coordinator.title": "Coordinator File Collector",
    "coordinator.drop_hint": "Collect Final CO report workbooks generated from the Instructor module.",
    "coordinator.list_placeholder": "Drag and drop Final CO report workbooks here or double-click to browse",
    "coordinator.add_file": "Add File",
    "coordinator.calculate": "Calculate CO Attainment",
    "coordinator.browse_drop": "Double-click to browse Final CO reports, or drag and drop here",
    "coordinator.dialog.title": "Select Excel Files",
    "coordinator.dialog.filter": "Excel Files (*.xlsx *.xlsm *.xls)",
    "coordinator.links.uploaded_report": "Uploaded Final CO Report",
    "coordinator.links.downloaded_output": "Downloaded Output",
    "coordinator.summary": "Files added: {count}",
    "coordinator.empty": "No Excel files added yet.",
    "coordinator.file.remove_fallback": "Remove",
    "coordinator.remove_selected": "Remove Selected",
    "coordinator.clear_all": "Clear All",
    "coordinator.status.added": "{added} file(s) added. Total: {total}.",
    "coordinator.duplicate.title": "File Already Exists",
    "coordinator.duplicate.body": "{count} duplicate file(s) were skipped because they already exist in the list.",
    "coordinator.invalid_final_report.title": "Invalid Final CO Report",
    "coordinator.invalid_final_report.body": (
        "Only Final CO report workbooks generated from Instructor Step 3 are allowed.\n\n{files}"
    ),
    "coordinator.status.ignored": (
        "{count} file(s) were ignored (unsupported type, missing, duplicate, "
        "or invalid final report workbook)."
    ),
    "coordinator.status.removed": "{count} file(s) removed.",
    "coordinator.status.cleared": "{count} file(s) cleared.",
    "coordinator.cancel_processing": "Cancel Processing",
    "coordinator.status.processing_started": "Processing selected files...",
    "coordinator.status.queued": "{count} file(s) queued while current processing is running.",
    "coordinator.status.cancelling": "Cancelling coordinator processing...",
    "coordinator.status.operation_cancelled": "Coordinator processing cancelled.",
    "coordinator.status.processing_failed": "Coordinator processing failed.",
    "coordinator.status.calculate_pending": "CO attainment calculation is not yet implemented in this module.",
    "coordinator.status.calculate_completed": "CO attainment calculation completed and output workbook generated.",
}
