"""English text catalog for user-facing strings."""

TEXTS = {
    # Startup / main
    "app.already_running": "Application is already running.",
    "app.unexpected_error": "An unexpected error occurred. Please check the log file.",
    "app.subtitle": "Framework for Outcome Computation and Unification System",
    "app.main_window_title": "FOCUS - {subtitle}",
    "splash.starting": "Starting application...",
    "splash.loading_main_window": "Loading main window...",
    # Main window
    "toolbar.navigation": "Navigation",
    "status.ready": "Ready",
    "module.placeholder": "{title} module is not yet implemented.",
    "module.instructor": "Instructor",
    "module.course_coordinator": "Course Coordinator",
    "module.coordinator_short": "Coordinator",
    "module.po_analysis": "PO Analysis",
    "module.load_failed_title": "Module Load Error",
    "module.load_failed_body": "Could not load module '{module}'.\n\nDetails: {error}",
    "module.load_failed_status": "Failed to load module: {module}.",
    "nav.help": "Help",
    "nav.about": "About",
    # About
    "about.version": "Version {version}",
    "about.description": (
        "{app_name} is a software tool designed for computing Course Outcome (CO) "
        "attainment and performing structured outcome analysis based on direct "
        "and indirect assessments."
    ),
    "about.institution": "Developed at Kalasalingam Academy of Research and Education (KARE).",
    "about.copyright": "(c) {year} KARE. All rights reserved.",
    # Help module
    "help.doc_missing_title": "Help Document Missing",
    "help.doc_missing_body": "Could not find help PDF:\n{path}",
    "help.doc_error_title": "Help Document Error",
    "help.doc_error_body": "Failed to load help PDF.",
    "help.download_pdf": "Download PDF",
    "help.open_default_viewer": "Open in Default Viewer",
    "help.missing_file_title": "Missing File",
    "help.missing_file_body": "Help PDF is not available.",
    "help.save_title": "Save CO Attainment Document",
    "help.save_default_name": "CO_Calculation_Document.pdf",
    "help.save_filter_pdf": "PDF Files (*.pdf)",
    "help.save_failed_title": "Save Failed",
    "help.save_failed_body": "Error happened while saving help PDF.",
    "help.save_success_title": "Saved",
    "help.save_success_body": "Help PDF saved successfully.",
    "help.open_failed_title": "Open Failed",
    "help.open_failed_body": "Could not open help PDF in the default viewer.",
    "help.open_success_title": "Opened",
    "help.open_success_body": "Help PDF opened in the default viewer.",
    "help.status.doc_loaded": "Help document loaded.",
    "help.status.doc_missing": "Help document is missing.",
    "help.status.doc_error": "Failed to load help document.",
    "help.status.file_missing": "Help PDF is not available.",
    "help.status.save_success": "Help PDF saved successfully.",
    "help.status.save_failed": "Error happened while saving help PDF.",
    "help.status.open_success": "Help PDF opened in default viewer.",
    "help.status.open_failed": "Error happened while opening help PDF in default viewer.",
    # Instructor module
    "instructor.workflow_title": "CO Workflow",
    "instructor.progress": "{completed} / {total} completed",
    "instructor.step_button": "{number}. {title}",
    "instructor.step1.title": "Download Course Template",
    "instructor.step2.title": "Generate Marks Template",
    "instructor.step4.title": "Upload Filled Marks",
    "instructor.step5.title": "Generate Final CO Report",
    "instructor.step1.desc": "Download the blank template used for entering course details.",
    "instructor.step2.desc": "Upload the validated course-details file, then prepare and save the marks template.",
    "instructor.step4.desc": "Upload the filled marks workbook.",
    "instructor.step5.desc": "Generate the final workbook with computed CO totals per student.",
    "instructor.badge.pending": "Pending",
    "instructor.badge.done": "Done",
    "instructor.badge.needs_update": "Needs update",
    "instructor.file.none": "No file/path selected yet.",
    "instructor.note.default": "You can return and replace any completed step.",
    "instructor.note.outdated_current": "This step is outdated. Run this step again.",
    "instructor.note.outdated_downstream": "An upstream change was made. Downstream steps may need regeneration.",
    "instructor.active_title": "Step {number}: {title}",
    "instructor.action.step1.default": "Download Template",
    "instructor.action.step1.redo": "Redownload Template",
    "instructor.action.step2.default": "Upload & Build Marks Template",
    "instructor.action.step2.redo": "Replace & Rebuild Marks Template",
    "instructor.action.step2.upload": "Upload Course Details",
    "instructor.action.step2.prepare": "Prepare Marks Template",
    "instructor.action.step4.default": "Upload Filled Marks",
    "instructor.action.step4.redo": "Replace Filled Marks",
    "instructor.action.step5.default": "Generate Final CO Report",
    "instructor.action.step5.redo": "Regenerate Final CO Report",
    "instructor.require.step2": "Complete Step 2 first.",
    "instructor.require.step3": "Complete Step 3 first.",
    "instructor.msg.success_title": "Success",
    "instructor.msg.validation_title": "Validation Error",
    "instructor.msg.error_title": "Failed",
    "instructor.msg.step_completed": "Step {step} completed: {title}.",
    "instructor.msg.failed_to_do": "Failed to do {action}.",
    "instructor.msg.step_required_title": "Step Required",
    "instructor.dialog.filter.excel": "Excel Files (*.xlsx)",
    "instructor.dialog.filter.excel_open": "Excel Files (*.xlsx *.xlsm *.xls)",
    "instructor.dialog.step1.title": "Save Course Details Template",
    "instructor.dialog.step1.default_name": "course_details_template.xlsx",
    "instructor.dialog.step2.title": "Select Course Details File",
    "instructor.dialog.step3.title": "Select Filled Marks File",
    "instructor.dialog.step3.default_name": "marks_template.xlsx",
    "instructor.dialog.step4.title": "Save Final CO Report",
    "instructor.dialog.step4.default_name": "co_report.xlsx",
    "instructor.status.step1_selected": "Template download path selected.",
    "instructor.status.step2_validated": "Course details uploaded and validated. You can now prepare marks template.",
    "instructor.status.step2_uploaded": "Marks template generated.",
    "instructor.status.step2_changed": "Course details changed. Redo downstream steps.",
    "instructor.status.step3_selected": "Marks template generated.",
    "instructor.status.step3_uploaded": "Filled marks uploaded.",
    "instructor.status.step3_changed": "Filled marks changed. Regenerate final report.",
    "instructor.status.step4_selected": "Final CO report path selected.",
    "instructor.status.step4_changed": "Filled marks changed. Regenerate final report.",
    "instructor.log.title": "Activity Log",
    "instructor.log.ready": "Activity log initialized.",
    "instructor.validation.xlsxwriter_missing": "xlsxwriter is not installed. Install it to generate course templates.",
    "instructor.validation.sheet_single_header_row": "Sheet '{sheet_name}' must define exactly one header row.",
    "instructor.system.template_generate_failed": "Failed to generate course details template at '{output}'.",
    "instructor.validation.unknown_template": "Unknown workbook template '{template_id}'. Available templates: {available}.",
    "instructor.validation.invalid_sheet_name": "Invalid sheet name.",
    "instructor.validation.headers_empty": "Headers cannot be empty for sheet '{sheet_name}'.",
    "instructor.validation.headers_unique": "Headers must be unique for sheet '{sheet_name}'.",
    "instructor.validation.row_length_mismatch": "Row {row} length mismatch in '{sheet_name}': expected {expected}, got {found}.",
    "instructor.validation.openpyxl_missing": "openpyxl is not installed. Install it to validate uploaded course details.",
    "instructor.validation.workbook_not_found": "Course details workbook not found: {workbook}",
    "instructor.validation.workbook_open_failed": "Unable to open course details workbook '{workbook}'.",
    "instructor.validation.system_sheet_missing": "Missing required system sheet '{sheet}' in uploaded workbook.",
    "instructor.validation.system_hash_missing_template_id_header": "Invalid system hash sheet format: missing Template_ID header.",
    "instructor.validation.system_hash_missing_template_hash_header": "Invalid system hash sheet format: missing Template_Hash header.",
    "instructor.validation.system_hash_template_id_missing": "Template_ID is missing in system hash sheet.",
    "instructor.validation.system_hash_mismatch": "Template hash mismatch. Please use a valid generated template.",
    "instructor.validation.workbook_sheet_mismatch": "Workbook sheets do not match template '{template_id}'. Expected: {expected}. Found: {found}.",
    "instructor.validation.header_mismatch": "Header mismatch in sheet '{sheet_name}'. Expected: {expected}.",
    "instructor.validation.unexpected_header": "Unexpected header in sheet '{sheet_name}' at column {col}.",
    "instructor.validation.validator_missing": "No validator implemented for template '{template_id}'.",
    "instructor.validation.course_metadata_field_empty": "Course_Metadata row {row}: Field cannot be empty.",
    "instructor.validation.course_metadata_duplicate_field": "Course_Metadata row {row}: duplicate field '{field}'.",
    "instructor.validation.course_metadata_unknown_field": "Course_Metadata row {row}: unknown field '{field}'.",
    "instructor.validation.course_metadata_value_required": "Course_Metadata row {row}: Value is required for '{field}'.",
    "instructor.validation.course_metadata_missing_fields": "Course_Metadata is missing required fields: {fields}.",
    "instructor.validation.course_metadata_field_must_be_int": "Course_Metadata field '{field}' must be an integer.",
    "instructor.validation.course_metadata_field_must_be_non_empty_str": "Course_Metadata field '{field}' must be a non-empty string.",
    "instructor.validation.course_metadata_total_outcomes_invalid": "Course_Metadata field 'Total_Outcomes' must be an integer > 0.",
    "instructor.validation.yes_no_required": "{sheet_name} row {row}: '{field}' must be YES or NO.",
    "instructor.validation.assessment_component_required_one": "Assessment_Config must contain at least one component.",
    "instructor.validation.assessment_component_required": "Assessment_Config row {row}: Component is required.",
    "instructor.validation.assessment_component_duplicate": "Assessment_Config row {row}: duplicate component '{component}'.",
    "instructor.validation.assessment_weight_numeric": "Assessment_Config row {row}: Weight (%) must be numeric.",
    "instructor.validation.assessment_direct_missing": "Assessment_Config must have at least one direct component.",
    "instructor.validation.assessment_indirect_missing": "Assessment_Config must have at least one indirect component.",
    "instructor.validation.assessment_direct_total_invalid": "Assessment_Config direct component weights must total 100. Found: {found}.",
    "instructor.validation.assessment_indirect_total_invalid": "Assessment_Config indirect component weights must total 100. Found: {found}.",
    "instructor.validation.question_map_row_required_one": "Question_Map must contain at least one question row.",
    "instructor.validation.question_component_required": "Question_Map row {row}: Component is required.",
    "instructor.validation.question_component_unknown": "Question_Map row {row}: unknown component '{component}'.",
    "instructor.validation.question_label_required": "Question_Map row {row}: Q_No/Rubric_Parameter is required.",
    "instructor.validation.question_max_marks_numeric": "Question_Map row {row}: Max_Marks must be numeric.",
    "instructor.validation.question_max_marks_positive": "Question_Map row {row}: Max_Marks must be greater than zero.",
    "instructor.validation.question_co_required": "Question_Map row {row}: CO must contain at least one value.",
    "instructor.validation.question_co_no_repeat": "Question_Map row {row}: CO values cannot repeat.",
    "instructor.validation.question_co_out_of_range": "Question_Map row {row}: CO value out of range 1..{total_outcomes}.",
    "instructor.validation.question_co_wise_requires_one": "Question_Map row {row}: component '{component}' requires exactly one CO per question.",
    "instructor.validation.question_duplicate_for_component": "Question_Map row {row}: duplicate question '{question}' for component '{component}'.",
    "instructor.validation.students_row_required_one": "Students sheet must contain at least one student row.",
    "instructor.validation.students_reg_and_name_required": "Students row {row}: both Reg_No and Student_Name are required.",
    "instructor.validation.students_duplicate_reg_no": "Students row {row}: duplicate Reg_No '{reg_no}'.",
    # Instructor template headers / labels
    "instructor.template.headers.course_metadata.field": "Field",
    "instructor.template.headers.course_metadata.value": "Value",
    "instructor.template.headers.assessment.component": "Component",
    "instructor.template.headers.assessment.weight": "Weight (%)",
    "instructor.template.headers.assessment.cia": "CIA",
    "instructor.template.headers.assessment.co_wise_breakup": "CO_Wise_Marks_Breakup",
    "instructor.template.headers.assessment.direct": "Direct",
    "instructor.template.headers.question_map.component": "Component",
    "instructor.template.headers.question_map.question": "Q_No/Rubric_Parameter",
    "instructor.template.headers.question_map.max_marks": "Max_Marks",
    "instructor.template.headers.question_map.co": "CO",
    "instructor.template.headers.students.reg_no": "Reg_No",
    "instructor.template.headers.students.student_name": "Student_Name",
    "instructor.template.validation.direct_title": "Direct",
    "instructor.template.validation.select_yes_no": "Select YES or NO",
    "instructor.marks.validation.error_title": "Invalid marks",
    "instructor.marks.validation.error_message": "Enter A/a or a numeric mark within allowed maximum.",
    "instructor.marks.validation.indirect_error_message": "Enter A/a or a numeric Likert value within allowed range.",
    "instructor.marks.row_header.serial_no": "Sl. No.",
    "instructor.marks.row_header.reg_no": "Reg. No.",
    "instructor.marks.row_header.student_name": "Student Name",
    "instructor.marks.total_label": "Total",
    "instructor.marks.co_prefix": "CO",
    "instructor.marks.question_prefix": "Q",
    "instructor.marks.co_marks_label_prefix": "Marks for CO",
    "instructor.marks.cos_label": "COs",
    # Coordinator module
    "coordinator.title": "Coordinator File Collector",
    "coordinator.drop_hint": "Drag and drop Excel files here to collect them for coordinator workflow.",
    "coordinator.empty": "No Excel files added yet.",
    "coordinator.remove_selected": "Remove Selected",
    "coordinator.clear_all": "Clear All",
    "coordinator.status.added": "{added} file(s) added. Total: {total}.",
    "coordinator.duplicate.title": "File Already Exists",
    "coordinator.duplicate.body": "{count} duplicate file(s) were skipped because they already exist in the list.",
    "coordinator.invalid_register.title": "Missing Register Header",
    "coordinator.invalid_register.body": (
        "File must contain Register Number.\n\n{files}"
    ),
    "coordinator.status.ignored": (
        "{count} file(s) were ignored (unsupported type, missing, duplicate, "
        "or missing register header)."
    ),
    "coordinator.status.removed": "{count} file(s) removed.",
    "coordinator.status.cleared": "{count} file(s) cleared.",
}
