"""English text catalog for user-facing strings."""

TEXTS = {
    # Startup / main
    "app.already_running": "Application is already running.",
    "app.unexpected_error": "An unexpected error occurred. Please check the log file.",
    "splash.starting": "Starting application...",
    "splash.loading_main_window": "Loading main window...",
    # Main window
    "toolbar.navigation": "Navigation",
    "status.ready": "Ready",
    "module.placeholder": "{title} module is not yet implemented.",
    "module.instructor": "Instructor",
    "module.course_coordinator": "Course Coordinator",
    "module.coordinator_short": "Coordinator",
    "module.po_analysis": "PO Analysis",
    "module.load_failed_title": "Module Load Error",
    "module.load_failed_body": "Could not load module '{module}'.\n\nDetails: {error}",
    "nav.help": "Help",
    "nav.about": "About",
    # About
    "about.version": "Version {version}",
    "about.description": (
        "{app_name} is a software tool designed for computing Course Outcome (CO) "
        "attainment and performing structured outcome analysis based on direct "
        "and indirect assessments."
    ),
    "about.institution": "Developed at Kalasalingam Academy of Research and Education (KARE).",
    "about.copyright": "(c) {year} KARE. All rights reserved.",
    # Help module
    "help.doc_missing_title": "Help Document Missing",
    "help.doc_missing_body": "Could not find help PDF:\n{path}",
    "help.doc_error_title": "Help Document Error",
    "help.doc_error_body": "Failed to load help PDF.",
    "help.download_pdf": "Download PDF",
    "help.open_default_viewer": "Open in Default Viewer",
    "help.missing_file_title": "Missing File",
    "help.missing_file_body": "Help PDF is not available.",
    "help.save_title": "Save CO Attainment Document",
    "help.save_default_name": "CO_Calculation_Document.pdf",
    "help.save_filter_pdf": "PDF Files (*.pdf)",
    "help.save_failed_title": "Save Failed",
    "help.save_failed_body": "Could not save PDF:\n{error}",
    "help.open_failed_title": "Open Failed",
    "help.open_failed_body": "Could not open help PDF in the default viewer.",
    # Instructor module
    "instructor.workflow_title": "CO Workflow",
    "instructor.progress": "{completed} / {total} completed",
    "instructor.step_button": "{number}. {title}",
    "instructor.step1.title": "Download Course Template",
    "instructor.step2.title": "Upload Course Details",
    "instructor.step3.title": "Generate Marks Template",
    "instructor.step4.title": "Upload Filled Marks",
    "instructor.step5.title": "Generate Final CO Report",
    "instructor.step1.desc": "Download the blank template used for entering course details.",
    "instructor.step2.desc": "Select the filled course-details workbook.",
    "instructor.step3.desc": "Create a marks-entry workbook based on uploaded course details.",
    "instructor.step4.desc": "Upload the filled marks workbook.",
    "instructor.step5.desc": "Generate the final workbook with computed CO totals per student.",
    "instructor.badge.pending": "Pending",
    "instructor.badge.done": "Done",
    "instructor.badge.needs_update": "Needs update",
    "instructor.file.none": "No file/path selected yet.",
    "instructor.note.default": "You can return and replace any completed step.",
    "instructor.note.outdated_current": "This step is outdated. Run this step again.",
    "instructor.note.outdated_downstream": "An upstream change was made. Downstream steps may need regeneration.",
    "instructor.active_title": "Step {number}: {title}",
    "instructor.action.step1.default": "Download Template",
    "instructor.action.step1.redo": "Redownload Template",
    "instructor.action.step2.default": "Upload Course Details",
    "instructor.action.step2.redo": "Replace Course Details",
    "instructor.action.step3.default": "Generate Marks Template",
    "instructor.action.step3.redo": "Regenerate Marks Template",
    "instructor.action.step4.default": "Upload Filled Marks",
    "instructor.action.step4.redo": "Replace Filled Marks",
    "instructor.action.step5.default": "Generate Final CO Report",
    "instructor.action.step5.redo": "Regenerate Final CO Report",
    "instructor.require.step2": "Complete Step 2 first.",
    "instructor.require.step3": "Complete Step 3 first.",
    "instructor.require.step4": "Complete Step 4 first.",
    "instructor.msg.step_required_title": "Step Required",
    "instructor.dialog.filter.excel": "Excel Files (*.xlsx)",
    "instructor.dialog.filter.excel_open": "Excel Files (*.xlsx *.xlsm *.xls)",
    "instructor.dialog.step1.title": "Save Course Details Template",
    "instructor.dialog.step1.default_name": "course_details_template.xlsx",
    "instructor.dialog.step2.title": "Select Course Details File",
    "instructor.dialog.step3.title": "Save Marks Template",
    "instructor.dialog.step3.default_name": "marks_template.xlsx",
    "instructor.dialog.step4.title": "Select Filled Marks File",
    "instructor.dialog.step5.title": "Save Final CO Report",
    "instructor.dialog.step5.default_name": "co_report.xlsx",
    "instructor.status.step1_selected": "Template download path selected.",
    "instructor.status.step2_uploaded": "Course details uploaded.",
    "instructor.status.step2_changed": "Course details changed. Redo downstream steps.",
    "instructor.status.step3_selected": "Marks template generated path selected.",
    "instructor.status.step4_uploaded": "Filled marks uploaded.",
    "instructor.status.step4_changed": "Filled marks changed. Regenerate final report.",
    "instructor.status.step5_selected": "Final CO report path selected.",
    # Coordinator module
    "coordinator.title": "Coordinator File Collector",
    "coordinator.drop_hint": "Drag and drop Excel files here to collect them for coordinator workflow.",
    "coordinator.empty": "No Excel files added yet.",
    "coordinator.remove_selected": "Remove Selected",
    "coordinator.clear_all": "Clear All",
    "coordinator.status.added": "{added} file(s) added. Total: {total}.",
    "coordinator.duplicate.title": "File Already Exists",
    "coordinator.duplicate.body": "{count} duplicate file(s) were skipped because they already exist in the list.",
    "coordinator.invalid_register.title": "Missing Register Header",
    "coordinator.invalid_register.body": (
        "File must contain Register Number.\n\n{files}"
    ),
    "coordinator.status.ignored": (
        "{count} file(s) were ignored (unsupported type, missing, duplicate, "
        "or missing register header)."
    ),
    "coordinator.status.removed": "{count} file(s) removed.",
    "coordinator.status.cleared": "{count} file(s) cleared.",
}
