"""Hindi text catalog for user-facing strings."""

TEXTS = {
    'app.already_running': 'एप्लिकेशन पहले से ही चल रहा है।',
    'app.unexpected_error': 'एक अप्रत्याशित त्रुटि हुई। कृपया लॉग फ़ाइल देखें।',
    'app.startup.workbook_secret_missing_frozen': 'वर्कबुक सीक्रेट उपलब्ध नहीं है। कृपया सॉफ़्टवेयर को फिर से इंस्टॉल करें या सहायता टीम से संपर्क करें।',
    'app.startup.workbook_secret_missing_dev': 'वर्कबुक सीक्रेट उपलब्ध नहीं है। स्थानीय वर्कबुक सीक्रेट स्टोर को हटाएँ और एप्लिकेशन को फिर से शुरू करें।',
    'app.main_window_title': 'फोकस',
    'splash.starting': 'एप्लिकेशन शुरू हो रहा है...',
    'splash.loading_main_window': 'मुख्य विंडो लोड हो रही है...',
    'toolbar.navigation': 'नेविगेशन',
    'status.ready': 'तैयार',
    'common.dropzone.placeholder': 'फ़ाइलें जोड़ने के लिए Drag and Drop करें, या Ctrl + O दबाएँ, या एक बार क्लिक करें',
    'module.placeholder': '{title} मॉड्यूल अभी तक लागू नहीं किया गया है।',
    'module.instructor': 'प्रशिक्षक',
    'module.coordinator_short': 'समन्वयक',
    'module.po_analysis': 'PO विश्लेषण',
    'module.co_analysis': 'CO विश्लेषण',
    'module.load_failed_title': 'मॉड्यूल लोड त्रुटि',
    'module.load_failed_body': "मॉड्यूल '{module}' लोड नहीं किया जा सका।\n\nविवरण: {error}",
    'module.load_failed_status': 'मॉड्यूल लोड करने में विफल: {module}.',
    'nav.help': 'सहायता',
    'nav.about': 'हमारे बारे में',
    'language.switcher.button': 'भाषा: {language}',
    'language.switcher.applied_status': 'भाषा {language} पर सेट की गई।',
    'about.version': 'संस्करण {version}',
    'about.subtitle': 'फ्रेमवर्क फॉर आउटकम कम्प्यूटेशन एंड यूनिफिकेशन सिस्टम',
    'about.description': "{app_name} एक सॉफ्टवेयर टूल है जिसे 'कोर्स आउटकम' (CO) की प्राप्ति की गणना करने, और प्रत्यक्ष व अप्रत्यक्ष मूल्यांकन के आधार पर संरचित परिणाम विश्लेषण करने के लिए डिज़ाइन किया गया है।",
    'about.institution': 'कलासलिंगम एकेडमी ऑफ़ रिसर्च एंड एजुकेशन (KARE) में, निम्नलिखित योगदानकर्ताओं द्वारा विकसित:',
    'about.copyright': '(c) {year} KARE. सभी अधिकार सुरक्षित।',
    'about.contributors.none': 'योगदानकर्ताओं की जानकारी उपलब्ध नहीं है।',
    'about.repository.link_label': 'गिटहब रिपॉजिटरी',
    'about.meta_line_html': '{copyright} | <a href="{url}">{link_label}</a>',
    'help.doc_missing_title': 'सहायता दस्तावेज़ गायब',
    'help.doc_missing_body': 'सहायता PDF नहीं मिल सकी:\\n{path}',
    'help.doc_error_title': 'सहायता दस्तावेज़ त्रुटि',
    'help.doc_error_body': 'सहायता PDF लोड करने में विफलता।',
    'help.download_pdf': 'PDF डाउनलोड करें',
    'help.open_default_viewer': 'डिफ़ॉल्ट व्यूअर में खोलें',
    'help.missing_file_title': 'फ़ाइल गायब',
    'help.save_title': 'CO प्राप्ति दस्तावेज़ सहेजें',
    'help.save_default_name': 'CO_Calculation_Document.pdf',
    'help.save_filter_pdf': 'PDF फ़ाइलें (*.pdf)',
    'help.save_failed_title': 'सहेजने में विफलता',
    'help.save_success_title': 'सहेज लिया गया',
    'help.open_failed_title': 'खोलने में विफलता',
    'help.open_failed_body': 'डिफ़ॉल्ट व्यूअर में सहायता PDF नहीं खोली जा सकी।',
    'help.open_success_title': 'खोल दिया गया',
    'help.open_success_body': 'सहायता PDF डिफ़ॉल्ट व्यूअर में खोल दी गई है।',
    'help.status.doc_loaded': 'सहायता दस्तावेज़ लोड हो गया है।',
    'help.status.doc_missing': 'सहायता दस्तावेज़ उपलब्ध नहीं है।',
    'help.status.doc_error': 'सहायता दस्तावेज़ लोड करने में विफलता हुई।',
    'help.status.file_missing': 'सहायता PDF उपलब्ध नहीं है।',
    'help.status.save_success': 'सहायता PDF सफलतापूर्वक सहेज ली गई है।',
    'help.status.save_failed': 'सहायता PDF सहेजते समय त्रुटि हुई।',
    'help.status.open_success': 'सहायता PDF डिफ़ॉल्ट व्यूअर में खोल दी गई है।',
    'help.status.open_failed': 'डिफ़ॉल्ट व्यूअर में सहायता PDF खोलते समय त्रुटि हुई।',
    'outputs.title': 'बने हुए Outputs',
    'activity.log.title': 'सक्रियता लॉग',
    'activity.log.ready': 'गतिविधि लॉग प्रारंभ किया गया।',
    'outputs.none_generated': 'कोई आउटपुट तैयार नहीं हुआ।',
    'outputs.open_file': 'फ़ाइल खोलें',
    'outputs.open_folder': 'फ़ोल्डर खोलें',
    'outputs.open_failed': 'चुना गया पाथ खोला नहीं जा सका।',
    'instructor.workflow_title': 'CO कार्यप्रवाह',
    'instructor.links.title': 'बने हुए Outputs',
    'instructor.links.course_details_generated': 'कोर्स विवरण टेम्पलेट तैयार हुआ',
    'instructor.links.marks_template_generated': 'मार्क्स टेम्पलेट तैयार हुआ',
    'instructor.links.open_file': 'फ़ाइल खोलें',
    'instructor.links.open_folder': 'फ़ोल्डर खोलें',
    'instructor.links.open_failed': 'चुना गया पाथ खोला नहीं जा सका।',
    'instructor.action.download_course_template': 'कोर्स टेम्प्लेट डाउनलोड करें',
    'instructor.action.download_course_template_link_html': '<a href="{href}">{text}</a>',
    'instructor.action.generate_marks_template': 'मार्क्स टेम्प्लेट तैयार करें',
    'instructor.msg.success_title': 'सफलता',
    'instructor.msg.validation_title': 'वैलिडेशन एरर',
    'instructor.msg.error_title': 'असफल',
    'instructor.msg.failed_to_do': '{action} करने में असफल.',
    'instructor.dialog.filter.excel': 'Excel फ़ाइलें (*.xlsx)',
    'instructor.dialog.filter.excel_open': 'Excel फ़ाइलें (*.xlsx *.xlsm *.xls)',
    'instructor.dialog.course_template.save_title': 'कोर्स विवरण टेम्प्लेट सहेजें',
    'instructor.dialog.course_template.default_name': 'course_details_template.xlsx',
    'instructor.dialog.course_details.select_title': 'कोर्स विवरण फ़ाइल चुनें',
    'instructor.dialog.marks_template.save_title': 'मार्क्स टेम्प्लेट सहेजें',
    'instructor.dialog.marks_template.default_name': 'marks_template.xlsx',
    'instructor.status.template_download_path_selected': 'टेम्प्लेट डाउनलोड पाथ चुन लिया गया है।',
    'instructor.status.course_details_validated': 'कोर्स विवरण अपलोड और वैलिडेट हो गए हैं। अब आप मार्क्स टेम्प्लेट तैयार कर सकते हैं।',
    'instructor.status.marks_template_generated': 'मार्क्स टेम्प्लेट तैयार हो गया है।',
    'instructor.status.course_details_replaced': 'कोर्स विवरण बदल गए हैं। आगे के स्टेप्स फिर से चलाएँ।',
    'instructor.status.operation_cancelled': 'ऑपरेशन रद्द कर दिया गया है।',
    'instructor.status.course_details_drop_browse_requested': 'ड्रैग-एंड-ड्रॉप विजेट से कोर्स डिटेल्स फ़ाइल चुनने का अनुरोध किया गया।',
    'instructor.status.course_details_drop_files_dropped': 'कोर्स डिटेल्स विजेट में {count} फ़ाइल(ें) ड्रॉप की गईं।',
    'instructor.status.course_details_drop_files_changed': 'कोर्स डिटेल्स विजेट में अब {count} फ़ाइल(ें) हैं।',
    'instructor.status.course_details_drop_files_rejected': 'कोर्स डिटेल्स विजेट में ड्रॉप की गई {count} फ़ाइल(ें) अस्वीकार कर दी गईं।',
    'instructor.status.course_details_validation_progress': 'मान्य फ़ाइलों का वैलिडेशन पूरा: {valid}/{total}।',
    'instructor.status.marks_template_generation_progress': 'मार्क्स टेम्प्लेट प्रोसेस किए गए: {processed}/{total}।',
    'instructor.status.marks_template_per_file_failures': 'मार्क्स-टेम्प्लेट प्रति-फ़ाइल विफलताएँ: {details}',
    'instructor.drop.summary': 'फ़ाइलें: {count}',
    'instructor.toast.course_details_validation_summary': 'वैलिडेशन पूरा: {valid} मान्य, {invalid} अमान्य, {mismatched} गलत टेम्प्लेट, {duplicates} डुप्लिकेट इनपुट।',
    'instructor.toast.marks_template_generation_summary': 'मार्क्स टेम्प्लेट जनरेशन पूरा: प्रोसेस्ड {processed}/{total}, जनरेटेड {generated}, विफल {failed}, स्किप्ड {skipped}।',
    'instructor.log.process.generate_course_details_template': 'कोर्स विवरण टेम्पलेट बनाई जा रही है',
    'instructor.log.process.validate_course_details_workbook': 'अपलोड की गई कोर्स विवरण वर्कबुक का सत्यापन किया जा रहा है',
    'instructor.log.process.generate_marks_template': 'मार्क्स टेम्पलेट बनाई जा रही है',
    'instructor.validation.file_issue_line': '{file}: [{code}] {reason}',
    'instructor.validation.course_details_missing': 'मार्क्स टेम्प्लेट बनाने से पहले कम से कम एक वैध कोर्स विवरण वर्कबुक अपलोड करें।',
    'validation.course_details.duplicate_path': 'Duplicate file path skipped: {workbook}.',
    'validation.course_details.duplicate_section': "Duplicate section skipped for this cohort (section '{section}') in file: {workbook}.",
    'validation.course_details.cohort_mismatch': 'Cohort mismatch in {workbook}. These fields must match the first valid file: {fields}.',
    'validation.course_details.unexpected_rejection': 'File was skipped due to an unexpected validation failure: {workbook}.',
    'coordinator.thresholds.l1.label': 'L1 सीमा:',
    'coordinator.thresholds.l2.label': 'L2 सीमा:',
    'coordinator.thresholds.l3.label': 'L3 सीमा:',
    'coordinator.thresholds.invalid_rule': 'थ्रेशोल्ड नियम उल्लंघन: 0 < L1 < L2 < L3 < 100 रखें।',
    'coordinator.co_attainment.description': 'यदि निम्न % विद्यार्थी तय स्तर और उससे ऊपर हैं, तो प्राप्त माना जाएगा।',
    'coordinator.co_attainment.percent.label': 'CO AT%:',
    'coordinator.co_attainment.level.label': 'CO AT स्तर:',
    'coordinator.co_attainment.invalid_percent': 'अमान्य CO AT%: मान 0 से 100 के बीच होना चाहिए।',
    'coordinator.dialog.title': 'Excel फ़ाइलें चुनें',
    'coordinator.links.downloaded_output': 'डाउनलोड किया गया आउटपुट',
    'coordinator.summary': 'फ़ाइलें: {count}',
    'coordinator.file.remove_fallback': 'हटाएँ',
    'coordinator.file.remove_tooltip': 'फ़ाइल हटाएँ',
    'coordinator.clear_all': 'सभी साफ़ करें',
    'coordinator.status.added': '{added} फ़ाइल(ें) जोड़ी गईं। कुल: {total}।',
    'coordinator.duplicate.title': 'फ़ाइल पहले से मौजूद है',
    'coordinator.duplicate.body': '{count} डुप्लीकेट फ़ाइल(ें) छोड़ दी गईं क्योंकि वे पहले से ही सूची में मौजूद हैं।',
    'coordinator.invalid_final_report.title': 'अमान्य फ़ाइनल CO रिपोर्ट',
    'coordinator.invalid_final_report.body': 'केवल वैध फ़ाइनल CO रिपोर्ट वर्कबुक की अनुमति है।\\n\\n{files}',
    'coordinator.invalid_final_report.details_prefix': 'विवरण:',
    'coordinator.invalid_final_report.detail_line': '{file}: {reason}',
    'coordinator.status.ignored': '{count} फ़ाइल(ें) नज़रअंदाज़ कर दी गईं (असमर्थित प्रकार, गुम, डुप्लीकेट, या अमान्य फ़ाइनल रिपोर्ट वर्कबुक)।',
    'coordinator.status.removed': '{count} फ़ाइलें हटाई गईं।',
    'coordinator.status.cleared': '{count} फ़ाइलें साफ़ की गईं।',
    'coordinator.status.processing_started': 'चुनी गई फ़ाइलों की प्रोसेसिंग हो रही है...',
    'coordinator.status.queued': 'जब मौजूदा प्रोसेसिंग चल रही थी, तब {count} फ़ाइलें कतार में लगाई गईं।',
    'coordinator.status.operation_cancelled': 'कोऑर्डिनेटर प्रोसेसिंग रद्द कर दी गई।',
    'coordinator.status.processing_failed': 'कोऑर्डिनेटर प्रोसेसिंग असफल रही।',
    'coordinator.status.processing_completed': 'कोऑर्डिनेटर प्रोसेसिंग पूरी हो गई।',
    'coordinator.status.calculate_completed': 'CO प्राप्ति की गणना पूरी हो गई और आउटपुट वर्कबुक तैयार हो गई।',
    'coordinator.regno_dedup.title': 'डुप्लीकेट रजिस्टर नंबर हटाए गए',
    'coordinator.regno_dedup.body': 'CO प्राप्ति बनाते समय {count} डुप्लीकेट रजिस्टर नंबर प्रविष्टियाँ हटाई गईं।',
    'coordinator.regno_dedup.log_body': '{count} डुप्लीकेट रजिस्टर नंबर प्रविष्टियाँ हटाई गईं:\\n{details}',
    'coordinator.regno_dedup.log_detail': 'रजिस्टर नंबर: {reg_no} | वर्कशीट: {worksheet} | वर्कबुक: {workbook}',
    'coordinator.regno_dedup.log_detail_unavailable': 'डुप्लीकेट प्रविष्टि का विवरण उपलब्ध नहीं है।',
    'coordinator.join_drop.body': 'कुछ पंक्तियों को नज़रअंदाज़ किया गया क्योंकि वे केवल Direct या केवल Indirect शीट में थीं। हटाई गई पंक्तियाँ: {count}। विवरण के लिए एक्टिविटी लॉग देखें।',
    'co_analysis.status.duplicate_reg_numbers': 'डुप्लीकेट रजिस्टर नंबर के कारण {count} फ़ाइल(ें) अस्वीकार की गईं।',
    'co_analysis.status.co_count_mismatch': 'कुल परिणाम संख्या असंगति के कारण {count} फ़ाइल(ें) अस्वीकार की गईं।',
    'co_analysis.status.validation_warnings': '{count} वैलिडेशन चेतावनी(याँ) रिपोर्ट हुईं।',
    'co_analysis.status.rejected_code_with_context': 'अस्वीकृत {file}: {code} ({context})',
    'co_analysis.dialog.select_files': 'विश्लेषण के लिए फ़ाइलें चुनें',
    'co_analysis.validation.co_count_mismatch_body': 'चयनित बैच से कुल परिणाम संख्या अलग होने के कारण {count} फ़ाइल(ें) अस्वीकार की गईं।',
    'co_analysis.validation.anomaly_warnings_body': 'अपलोड की गई फ़ाइलों में {count} वैलिडेशन विसंगति चेतावनी(याँ) रिपोर्ट हुईं।',
    'co_analysis.validation.rejection_breakdown_title': 'CO Analysis फ़ाइल अस्वीकृति',
    'co_analysis.validation.rejection_breakdown_body': (
        'कारण अनुसार अस्वीकृत फ़ाइलें:\\n'
        'असमर्थित/गायब: {unsupported_or_missing}\\n'
        'अमान्य वर्कबुक: {invalid_workbook}\\n'
        'सिस्टम हैश/पहचान विफल: {invalid_hash}\\n'
        'अधूरे मार्क्स: {marks_unfilled}\\n'
        'लेआउट/मैनिफेस्ट विफल: {layout_manifest}\\n'
        'टेम्प्लेट असंगति: {template_mismatch}\\n'
        'अमान्य मार्क वैल्यू/फॉर्मेट: {mark_value}\\n'
        'अन्य वैलिडेशन विफल: {invalid_other}\\n'
        'डुप्लीकेट: {duplicates}\\n'
        'डुप्लीकेट रजिस्टर नंबर: {duplicate_reg}\\n'
        'कुल परिणाम संख्या असंगति: {co_count_mismatch}'
    ),
    'co_analysis.status.ignored_summary': (
        '{count} फ़ाइल(ें) अनदेखी की गईं। '
        '{part1}{sep1_2}{part2}{sep2_3}{part3}{sep3_4}{part4}{sep4_5}{part5}{sep5_6}{part6}'
        '{sep6_7}{part7}{sep7_8}{part8}{sep8_9}{part9}{sep9_10}{part10}{sep10_11}{part11}{sep11_12}{part12}'
    ),
    'co_analysis.status.ignored_total': '{count} फ़ाइल(ें) अनदेखी की गईं।',
    'co_analysis.status.ignored_reason.unsupported_or_missing': 'असमर्थित/गायब={count}',
    'co_analysis.status.ignored_reason.invalid_workbook': 'अमान्य वर्कबुक={count}',
    'co_analysis.status.ignored_reason.invalid_hash': 'हैश={count}',
    'co_analysis.status.ignored_reason.marks_unfilled': 'अधूरे मार्क्स={count}',
    'co_analysis.status.ignored_reason.layout_manifest': 'लेआउट/मैनिफेस्ट={count}',
    'co_analysis.status.ignored_reason.template_mismatch': 'टेम्प्लेट असंगति={count}',
    'co_analysis.status.ignored_reason.mark_value': 'अमान्य मार्क वैल्यू={count}',
    'co_analysis.status.ignored_reason.invalid_other': 'अन्य वैलिडेशन={count}',
    'co_analysis.status.ignored_reason.duplicates': 'डुप्लीकेट={count}',
    'co_analysis.status.ignored_reason.duplicate_reg': 'डुप्लीकेट रजिस्टर नंबर={count}',
    'co_analysis.status.ignored_reason.co_count_mismatch': 'कुल परिणाम संख्या असंगति={count}',
}







