"""Hindi text catalog for user-facing strings."""

TEXTS = {
    'app.already_running': 'एप्लिकेशन पहले से ही चल रहा है।',
    'app.unexpected_error': 'एक अप्रत्याशित त्रुटि हुई। कृपया लॉग फ़ाइल देखें।',
    'app.startup.workbook_secret_missing_frozen': 'वर्कबुक सीक्रेट उपलब्ध नहीं है। कृपया सॉफ़्टवेयर को फिर से इंस्टॉल करें या सहायता टीम से संपर्क करें।',
    'app.startup.workbook_secret_missing_dev': 'वर्कबुक सीक्रेट उपलब्ध नहीं है। स्थानीय वर्कबुक सीक्रेट स्टोर को हटाएँ और एप्लिकेशन को फिर से शुरू करें।',
    'app.main_window_title': 'फोकस',
    'splash.starting': 'एप्लिकेशन शुरू हो रहा है...',
    'splash.loading_main_window': 'मुख्य विंडो लोड हो रही है...',
    'toolbar.navigation': 'नेविगेशन',
    'status.ready': 'तैयार',
    'module.placeholder': '{title} मॉड्यूल अभी तक लागू नहीं किया गया है।',
    'module.instructor': 'प्रशिक्षक',
    'module.coordinator_short': 'समन्वयक',
    'module.po_analysis': 'PO विश्लेषण',
    'module.co_analysis': 'CO विश्लेषण',
    'module.load_failed_title': 'मॉड्यूल लोड त्रुटि',
    'module.load_failed_body': "मॉड्यूल '{module}' लोड नहीं किया जा सका।\n\nविवरण: {error}",
    'module.load_failed_status': 'मॉड्यूल लोड करने में विफल: {module}.',
    'nav.help': 'सहायता',
    'nav.about': 'हमारे बारे में',
    'language.switcher.button': 'भाषा: {language}',
    'language.switcher.applied_status': 'भाषा {language} पर सेट की गई।',
    'about.version': 'संस्करण {version}',
    'about.subtitle': 'फ्रेमवर्क फॉर आउटकम कम्प्यूटेशन एंड यूनिफिकेशन सिस्टम',
    'about.description': "{app_name} एक सॉफ्टवेयर टूल है जिसे 'कोर्स आउटकम' (CO) की प्राप्ति की गणना करने, और प्रत्यक्ष व अप्रत्यक्ष मूल्यांकन के आधार पर संरचित परिणाम विश्लेषण करने के लिए डिज़ाइन किया गया है।",
    'about.institution': 'कलासलिंगम एकेडमी ऑफ़ रिसर्च एंड एजुकेशन (KARE) में, निम्नलिखित योगदानकर्ताओं द्वारा विकसित:',
    'about.copyright': '(c) {year} KARE. सभी अधिकार सुरक्षित।',
    'about.contributors.none': 'योगदानकर्ताओं की जानकारी उपलब्ध नहीं है।',
    'about.repository.link_label': 'गिटहब रिपॉजिटरी',
    'about.meta_line_html': '{copyright} | <a href="{url}">{link_label}</a>',
    'help.doc_missing_title': 'सहायता दस्तावेज़ गायब',
    'help.doc_missing_body': 'सहायता PDF नहीं मिल सकी:\\n{path}',
    'help.doc_error_title': 'सहायता दस्तावेज़ त्रुटि',
    'help.doc_error_body': 'सहायता PDF लोड करने में विफलता।',
    'help.download_pdf': 'PDF डाउनलोड करें',
    'help.open_default_viewer': 'डिफ़ॉल्ट व्यूअर में खोलें',
    'help.missing_file_title': 'फ़ाइल गायब',
    'help.save_title': 'CO प्राप्ति दस्तावेज़ सहेजें',
    'help.save_default_name': 'CO_Calculation_Document.pdf',
    'help.save_filter_pdf': 'PDF फ़ाइलें (*.pdf)',
    'help.save_failed_title': 'सहेजने में विफलता',
    'help.save_success_title': 'सहेज लिया गया',
    'help.open_failed_title': 'खोलने में विफलता',
    'help.open_failed_body': 'डिफ़ॉल्ट व्यूअर में सहायता PDF नहीं खोली जा सकी।',
    'help.open_success_title': 'खोल दिया गया',
    'help.open_success_body': 'सहायता PDF डिफ़ॉल्ट व्यूअर में खोल दी गई है।',
    'help.status.doc_loaded': 'सहायता दस्तावेज़ लोड हो गया है।',
    'help.status.doc_missing': 'सहायता दस्तावेज़ उपलब्ध नहीं है।',
    'help.status.doc_error': 'सहायता दस्तावेज़ लोड करने में विफलता हुई।',
    'help.status.file_missing': 'सहायता PDF उपलब्ध नहीं है।',
    'help.status.save_success': 'सहायता PDF सफलतापूर्वक सहेज ली गई है।',
    'help.status.save_failed': 'सहायता PDF सहेजते समय त्रुटि हुई।',
    'help.status.open_success': 'सहायता PDF डिफ़ॉल्ट व्यूअर में खोल दी गई है।',
    'help.status.open_failed': 'डिफ़ॉल्ट व्यूअर में सहायता PDF खोलते समय त्रुटि हुई।',
    'outputs.none_generated': 'कोई आउटपुट तैयार नहीं हुआ।',
    'instructor.workflow_title': 'CO कार्यप्रवाह',
    'instructor.step1.title': 'मार्क्स टेम्पलेट बनाएं',
    'instructor.step2.title': 'CO मार्क्स रिपोर्ट बनाएं',
    'instructor.step1.desc': 'जांची गई Course-details फ़ाइल Upload करें, फिर Marks टेम्पलेट तैयार करें और Save करें।',
    'instructor.links.title': 'बने हुए Outputs',
    'instructor.links.course_details_generated': 'कोर्स विवरण टेम्पलेट तैयार हुआ',
    'instructor.links.marks_template_generated': 'मार्क्स टेम्पलेट तैयार हुआ',
    'instructor.links.final_co_report_generated': 'अंतिम CO रिपोर्ट तैयार हुई',
    'instructor.links.open_file': 'फ़ाइल खोलें',
    'instructor.links.open_folder': 'फ़ोल्डर खोलें',
    'instructor.links.open_failed': 'चुना गया पाथ खोला नहीं जा सका।',
    'instructor.note.default': 'आप चाहें तो पूरा किए गए किसी भी स्टेप पर वापस जाकर उसे बदल सकते हैं।',
    'instructor.note.outdated_current': 'यह स्टेप पुराना हो गया है। इसे फिर से चलाएँ।',
    'instructor.note.outdated_downstream': 'ऊपरी स्टेप में बदलाव हुआ है। नीचे के स्टेप्स को फिर से चलाने की ज़रूरत पड़ सकती है।',
    'instructor.action.step1.default': 'कोर्स टेम्प्लेट डाउनलोड करें',
    'instructor.action.step1.link_html': '<a href="{href}">{text}</a>',
    'instructor.action.step1.upload': 'कोर्स की जानकारी अपलोड करें',
    'instructor.action.step1.prepare': 'मार्क्स टेम्प्लेट तैयार करें',
    'instructor.action.step2.upload.default': 'भरे हुए मार्क्स अपलोड करें',
    'instructor.action.step2.generate.default': 'फाइनल CO रिपोर्ट बनाएँ',
    'instructor.msg.success_title': 'सफलता',
    'instructor.msg.validation_title': 'वैलिडेशन एरर',
    'instructor.msg.error_title': 'असफल',
    'instructor.msg.step_completed': 'स्टेप {step} पूरा हुआ: {title}.',
    'instructor.msg.failed_to_do': '{action} करने में असफल.',
    'instructor.dialog.filter.excel': 'Excel फ़ाइलें (*.xlsx)',
    'instructor.dialog.filter.excel_open': 'Excel फ़ाइलें (*.xlsx *.xlsm *.xls)',
    'instructor.dialog.step1.title': 'कोर्स विवरण टेम्प्लेट सहेजें',
    'instructor.dialog.step1.default_name': 'course_details_template.xlsx',
    'instructor.dialog.step2.title': 'कोर्स विवरण फ़ाइल चुनें',
    'instructor.dialog.step1.prepare.title': 'मार्क्स टेम्प्लेट सहेजें',
    'instructor.dialog.step1.prepare.default_name': 'marks_template.xlsx',
    'instructor.dialog.step2.upload.title': 'भरी हुई अंकों की फ़ाइल चुनें',
    'instructor.dialog.step2.generate.title': 'अंतिम CO रिपोर्ट सहेजें',
    'instructor.status.step1_selected': 'टेम्प्लेट डाउनलोड पाथ चुन लिया गया है।',
    'instructor.status.step1_validated': 'कोर्स विवरण अपलोड और वैलिडेट हो गए हैं। अब आप मार्क्स टेम्प्लेट तैयार कर सकते हैं।',
    'instructor.status.step1_prepared': 'मार्क्स टेम्प्लेट तैयार हो गया है।',
    'instructor.status.step1_changed': 'कोर्स विवरण बदल गए हैं। आगे के स्टेप्स फिर से चलाएँ।',
    'instructor.status.step2_uploaded_filled': 'भरे हुए मार्क्स अपलोड हो गए हैं।',
    'instructor.status.step2_changed_filled': 'भरे हुए मार्क्स बदल गए हैं। अंतिम रिपोर्ट फिर से बनाएँ।',
    'instructor.status.step2_generated': 'अंतिम CO रिपोर्ट का पाथ चुन लिया गया है।',
    'instructor.status.operation_cancelled': 'ऑपरेशन रद्द कर दिया गया है।',
    'instructor.status.step1_drop_browse_requested': 'ड्रैग-एंड-ड्रॉप विजेट से कोर्स डिटेल्स फ़ाइल चुनने का अनुरोध किया गया।',
    'instructor.status.step1_drop_files_dropped': 'कोर्स डिटेल्स विजेट में {count} फ़ाइल(ें) ड्रॉप की गईं।',
    'instructor.status.step1_drop_files_changed': 'कोर्स डिटेल्स विजेट में अब {count} फ़ाइल(ें) हैं।',
    'instructor.status.step1_drop_files_rejected': 'कोर्स डिटेल्स विजेट में ड्रॉप की गई {count} फ़ाइल(ें) अस्वीकार कर दी गईं।',
    'instructor.status.step2_drop_browse_requested': 'ड्रैग-एंड-ड्रॉप विजेट से भरे हुए मार्क्स फ़ाइल चुनने का अनुरोध किया गया।',
    'instructor.status.step2_drop_files_dropped': 'भरे हुए मार्क्स विजेट में {count} फ़ाइल(ें) ड्रॉप की गईं।',
    'instructor.status.step2_drop_files_changed': 'भरे हुए मार्क्स विजेट में अब {count} फ़ाइल(ें) हैं।',
    'instructor.status.step2_drop_files_rejected': 'भरे हुए मार्क्स विजेट में ड्रॉप की गई {count} फ़ाइल(ें) अस्वीकार कर दी गईं।',
    'instructor.status.step2_validation_warnings': 'वैलिडेशन असामान्यता चेतावनियाँ: {details}',
    'instructor.status.step2_generate_per_file_failures': 'अंतिम रिपोर्ट प्रति-फ़ाइल विफलताएँ: {details}',
    'instructor.status.step1_validating_progress': 'कोर्स टेम्प्लेट फ़ाइलों का वैलिडेशन: {processed}/{total}।',
    'instructor.status.step1_validated_progress': 'मान्य फ़ाइलों का वैलिडेशन पूरा: {valid}/{total}।',
    'instructor.status.step1_prepare_progress': 'मार्क्स टेम्प्लेट प्रोसेस किए गए: {processed}/{total}।',
    'instructor.status.step1_prepare_per_file_failures': 'मार्क्स-टेम्प्लेट प्रति-फ़ाइल विफलताएँ: {details}',
    'instructor.step1.drop.summary': 'फ़ाइलें: {count}',
    'common.dropzone.placeholder': 'फ़ाइलें जोड़ने के लिए Drag and Drop करें, या Ctrl + O दबाएँ, या एक बार क्लिक करें',
    'common.validation_failed_invalid_data': 'अमान्य डेटा के कारण वैलिडेशन असफल हुआ।',
    'common.error_while_process': '{process} के दौरान कोई गड़बड़ हो गई।',
    'instructor.toast.step1_validation_summary': 'वैलिडेशन पूरा: {valid} मान्य, {invalid} अमान्य, {mismatched} गलत टेम्प्लेट, {duplicates} डुप्लिकेट इनपुट।',
    'instructor.toast.step1_prepare_summary': 'मार्क्स टेम्प्लेट जनरेशन पूरा: प्रोसेस्ड {processed}/{total}, जनरेटेड {generated}, विफल {failed}, स्किप्ड {skipped}।',
    'instructor.toast.step2_generate_summary': 'CO रिपोर्ट जनरेशन पूरा: प्रोसेस्ड {processed}/{total}, जनरेटेड {generated}, विफल {failed}, स्किप्ड {skipped}।',
    'instructor.toast.step2_upload_reject_summary': 'कुछ फ़ाइलें स्वीकार नहीं की गईं। अमान्य={invalid}, डुप्लिकेट={duplicates}।',
    'instructor.toast.validation_warnings_title': 'वैलिडेशन चेतावनियाँ',
    'instructor.toast.validation_warnings_body': 'वैलिडेशन असामान्यता चेतावनियों के साथ पूरा हुआ। विवरण के लिए एक्टिविटी लॉग देखें।',
    'instructor.log.title': 'एक्टिविटी लॉग',
    'instructor.log.ready': 'एक्टिविटी लॉग शुरू हो गया है।',
    'instructor.log.completed_process': '{process} सफलतापूर्वक पूरा हो गया है।',
    'instructor.log.error_while_process': '{process} के दौरान कोई गड़बड़ हो गई।',
    'instructor.log.process.generate_course_details_template': 'कोर्स डिटेल्स टेम्प्लेट बनाया जा रहा है',
    'instructor.log.process.validate_course_details_workbook': 'अपलोड की गई कोर्स डिटेल्स वर्कबुक की जाँच की जा रही है',
    'instructor.log.process.generate_marks_template': 'मार्क्स टेम्प्लेट बनाया जा रहा है',
    'instructor.log.process.upload_filled_marks_workbook': 'भरी हुई मार्क्स वर्कबुक अपलोड की जा रही है',
    'instructor.log.process.generate_final_co_report': 'अंतिम CO रिपोर्ट बनाई जा रही है',
    'instructor.validation.xlsxwriter_missing': 'xlsxwriter इंस्टॉल नहीं है। कोर्स टेम्प्लेट बनाने के लिए इसे इंस्टॉल करें।',
    'instructor.validation.sheet_single_header_row': "शीट '{sheet_name}' में ठीक एक हेडर रो होनी चाहिए।",
    'instructor.system.template_generate_failed': "'{output}' पर कोर्स डिटेल्स टेम्प्लेट बनाने में गड़बड़ हो गई।",
    'instructor.validation.unknown_template': "अज्ञात वर्कबुक टेम्प्लेट '{template_id}'। उपलब्ध टेम्प्लेट: {available}।",
    'instructor.validation.invalid_sheet_name': 'शीट का नाम गलत है।',
    'instructor.validation.headers_empty': "शीट '{sheet_name}' के लिए हेडर खाली नहीं हो सकते।",
    'instructor.validation.headers_unique': "शीट '{sheet_name}' के लिए हेडर अलग-अलग होने चाहिए।",
    'instructor.validation.row_length_mismatch': "'{sheet_name}' में रो {row} की लंबाई मेल नहीं खा रही: अपेक्षित {expected}, मिला {found}।",
    'instructor.validation.openpyxl_missing': 'openpyxl इंस्टॉल नहीं है। अपलोड की गई कोर्स डिटेल्स की जाँच करने के लिए इसे इंस्टॉल करें।',
    'instructor.validation.workbook_not_found': 'कोर्स डिटेल्स वर्कबुक नहीं मिली: {workbook}',
    'instructor.validation.workbook_open_failed': "कोर्स डिटेल्स वर्कबुक '{workbook}' खोलने में असमर्थ।",
    'instructor.validation.system_sheet_missing': "अपलोड की गई वर्कबुक में ज़रूरी सिस्टम शीट '{sheet}' मौजूद नहीं है।",
    'instructor.validation.system_hash_missing_template_id_header': 'सिस्टम हैश शीट का फ़ॉर्मेट गलत है: Template_ID हेडर मौजूद नहीं है।',
    'instructor.validation.system_hash_missing_template_hash_header': 'सिस्टम हैश शीट का फ़ॉर्मेट गलत है: Template_Hash हेडर मौजूद नहीं है।',
    'instructor.validation.system_hash_template_id_missing': 'सिस्टम हैश शीट में Template_ID मौजूद नहीं है।',
    'instructor.validation.system_hash_mismatch': 'टेम्पलेट हैश मेल नहीं खा रहा है। कृपया एक सही, जेनरेट किया हुआ टेम्पलेट इस्तेमाल करें।',
    'instructor.validation.workbook_sheet_mismatch': "वर्कबुक की शीटें टेम्पलेट '{template_id}' से मेल नहीं खातीं। उम्मीद थी: {expected}. मिला: {found}.",
    'instructor.validation.header_mismatch': "शीट '{sheet_name}' में हेडर मेल नहीं खा रहा है। उम्मीद थी: {expected}.",
    'instructor.validation.unexpected_header': "शीट '{sheet_name}' में कॉलम {col} पर एक ऐसा हेडर मिला जिसकी उम्मीद नहीं थी।",
    'instructor.validation.validator_missing': "टेम्पलेट '{template_id}' के लिए कोई Validator लागू नहीं किया गया है।",
    'instructor.validation.course_metadata_field_empty': 'Course_Metadata पंक्ति {row}: फ़ील्ड खाली नहीं हो सकता।',
    'instructor.validation.course_metadata_duplicate_field': "Course_Metadata पंक्ति {row}: डुप्लीकेट फ़ील्ड '{field}'।",
    'instructor.validation.course_metadata_unknown_field': "Course_Metadata पंक्ति {row}: अज्ञात फ़ील्ड '{field}'।",
    'instructor.validation.course_metadata_value_required': "Course_Metadata पंक्ति {row}: '{field}' के लिए मान आवश्यक है।",
    'instructor.validation.course_metadata_missing_fields': 'Course_Metadata में आवश्यक फ़ील्ड्स गायब हैं: {fields}।',
    'instructor.validation.course_metadata_field_must_be_int': "Course_Metadata फ़ील्ड '{field}' एक पूर्णांक होना चाहिए।",
    'instructor.validation.course_metadata_field_must_be_non_empty_str': "Course_Metadata फ़ील्ड '{field}' एक गैर-खाली स्ट्रिंग होना चाहिए।",
    'instructor.validation.course_metadata_total_outcomes_invalid': "Course_Metadata फ़ील्ड 'Total_Outcomes' एक पूर्णांक (> 0) होना चाहिए।",
    'instructor.validation.yes_no_required': "{sheet_name} पंक्ति {row}: '{field}' YES या NO होना चाहिए।",
    'instructor.validation.assessment_component_required_one': 'Assessment_Config में कम से कम एक घटक होना चाहिए।',
    'instructor.validation.assessment_component_required': 'Assessment_Config पंक्ति {row}: घटक आवश्यक है।',
    'instructor.validation.assessment_component_duplicate': "Assessment_Config पंक्ति {row}: डुप्लीकेट घटक '{component}'।",
    'instructor.validation.assessment_weight_numeric': 'Assessment_Config पंक्ति {row}: Weight (%) संख्यात्मक होना चाहिए।',
    'instructor.validation.assessment_direct_missing': 'Assessment_Config में कम से कम एक प्रत्यक्ष घटक होना चाहिए।',
    'instructor.validation.assessment_indirect_missing': 'Assessment_Config में कम से कम एक अप्रत्यक्ष घटक होना चाहिए।',
    'instructor.validation.assessment_direct_total_invalid': 'Assessment_Config प्रत्यक्ष घटक भार का कुल योग 100 होना चाहिए। प्राप्त: {found}।',
    'instructor.validation.assessment_indirect_total_invalid': 'Assessment_Config के अप्रत्यक्ष घटक के वज़नों का कुल योग 100 होना चाहिए। मिला: {found}।',
    'instructor.validation.question_map_row_required_one': 'Question_Map में कम से कम एक प्रश्न पंक्ति होनी चाहिए।',
    'instructor.validation.question_component_required': 'Question_Map पंक्ति {row}: घटक (घटक) आवश्यक है।',
    'instructor.validation.question_component_unknown': "Question_Map पंक्ति {row}: अज्ञात घटक '{component}'।",
    'instructor.validation.question_label_required': 'Question_Map पंक्ति {row}: Q_No/Rubric_Parameter आवश्यक है।',
    'instructor.validation.question_max_marks_numeric': 'Question_Map पंक्ति {row}: Max_Marks संख्यात्मक होना चाहिए।',
    'instructor.validation.question_max_marks_positive': 'Question_Map पंक्ति {row}: Max_Marks शून्य से अधिक होना चाहिए।',
    'instructor.validation.question_co_required': 'Question_Map पंक्ति {row}: CO में कम से कम एक मान होना चाहिए।',
    'instructor.validation.question_co_no_repeat': 'Question_Map पंक्ति {row}: CO मान दोहराए नहीं जा सकते।',
    'instructor.validation.question_co_out_of_range': 'Question_Map पंक्ति {row}: CO मान 1..{total_outcomes} की सीमा से बाहर है।',
    'instructor.validation.question_co_wise_requires_one': "Question_Map पंक्ति {row}: घटक '{component}' के लिए प्रति प्रश्न ठीक एक CO आवश्यक है।",
    'instructor.validation.question_duplicate_for_component': "Question_Map पंक्ति {row}: घटक '{component}' के लिए प्रश्न '{question}' दोहराया गया है।",
    'instructor.validation.students_row_required_one': 'Students शीट में कम से कम एक छात्र पंक्ति होनी चाहिए।',
    'instructor.validation.students_reg_and_name_required': 'Students पंक्ति {row}: Reg_No और Student_Name, दोनों आवश्यक हैं।',
    'instructor.validation.students_duplicate_reg_no': "Students पंक्ति {row}: Reg_No '{reg_no}' दोहराया गया है।",
    'instructor.validation.step2.layout_sheet_missing': "भरी हुई मार्क्स वर्कबुक में ज़रूरी लेआउट शीट '{sheet}' मौजूद नहीं है।",
    'instructor.validation.step2.layout_header_mismatch': "{column} पर लेआउट शीट का हेडर गलत है। अपेक्षित: '{expected}'।",
    'instructor.validation.step2.layout_manifest_missing': 'सिस्टम लेआउट शीट में लेआउट मैनिफ़ेस्ट या लेआउट हैश मौजूद नहीं है।',
    'instructor.validation.step2.layout_hash_mismatch': 'लेआउट हैश मेल नहीं खाया। कृपया बिना बदलाव वाला, जनरेट किया हुआ मार्क्स टेम्पलेट इस्तेमाल करें।',
    'instructor.validation.step2.layout_manifest_json_invalid': 'लेआउट मैनिफेस्ट JSON अमान्य है।',
    'instructor.validation.step2.template_validator_missing': "टेम्पलेट '{template_id}' के लिए Step 2 वैलिडेटर उपलब्ध नहीं है।",
    'instructor.validation.step2.manifest_root_invalid': 'लेआउट मैनिफेस्ट का रूट ऑब्जेक्ट होना चाहिए।',
    'instructor.validation.step2.manifest_structure_invalid': "लेआउट मैनिफेस्ट में 'sheet_order' और 'sheets' दोनों होने चाहिए।",
    'instructor.validation.step2.sheet_order_mismatch': 'भरे हुए मार्क्स की शीटों का क्रम मेल नहीं खाया। अपेक्षित क्रम: {expected}। मिला: {found}।',
    'instructor.validation.step2.manifest_sheet_spec_invalid': 'लेआउट मैनिफेस्ट में शीट स्पेसिफिकेशन अमान्य है।',
    'instructor.validation.step2.sheet_missing': "वर्कबुक में अपेक्षित शीट '{sheet_name}' मौजूद नहीं है।",
    'instructor.validation.step2.header_row_invalid': "शीट '{sheet_name}' के हेडर रो का मेटाडेटा गलत है: {header_row}।",
    'instructor.validation.step2.headers_missing': "शीट '{sheet_name}' के लिए लेआउट मैनिफ़ेस्ट में अपेक्षित हेडर परिभाषाएँ मौजूद नहीं हैं।",
    'instructor.validation.step2.anchor_spec_invalid': "शीट '{sheet_name}' के लिए लेआउट मैनिफ़ेस्ट में एंकर का विवरण गलत है।",
    'instructor.validation.step2.formula_anchor_spec_invalid': "शीट '{sheet_name}' के लिए लेआउट मैनिफ़ेस्ट में फ़ॉर्मूला एंकर का विवरण गलत है।",
    'instructor.validation.step2.header_row_mismatch': "शीट '{sheet_name}' का हेडर रो {row} पर मेल नहीं खा रहा है। अपेक्षित: {expected}.",
    'instructor.validation.step2.anchor_value_mismatch': "Sheet '{sheet_name}' का सेल {cell} संशोधित किया गया है। अपेक्षित '{expected}', मिला '{found}'।",
    'instructor.validation.step2.formula_mismatch': "Sheet '{sheet_name}' में {cell} पर मौजूद फ़ॉर्मूला बदल दिया गया है।",
    'instructor.validation.step2.no_component_sheets': 'भरी हुई मार्क्स वर्कबुक में कोई भी कंपोनेंट मार्क्स-एंट्री शीट नहीं मिली।',
    'instructor.validation.step2.mark_entry_empty': "Sheet '{sheet_name}' में {cell} पर मार्क्स-एंट्री वाला सेल खाली है। अपलोड करने से पहले सभी मार्क्स भरें।",
    'instructor.validation.step2.mark_value_invalid': "Sheet '{sheet_name}' के सेल {cell} में मार्क्स की वैल्यू '{value}' गलत है। मान्य वैल्यू: A/a या {minimum} और {maximum} के बीच कोई संख्या।",
    'instructor.validation.step2.mark_precision_invalid': "Sheet '{sheet_name}' के सेल {cell} में '{value}' में दशमलव के बाद बहुत ज़्यादा अंक हैं। दशमलव के बाद अधिकतम {decimals} अंक ही मान्य हैं।",
    'instructor.validation.step2.indirect_mark_must_be_integer': "Sheet '{sheet_name}' के सेल {cell} में अप्रत्यक्ष मार्क्स की वैल्यू '{value}' गलत है। कृपया पूर्णांक (integer) Likert वैल्यू का उपयोग करें।",
    'instructor.validation.step2.absence_policy_violation': "Sheet '{sheet_name}' की पंक्ति {row} में {range} के अंतर्गत अनुपस्थिति (A/a) और संख्यात्मक प्रविष्टियाँ मिली-जुली हैं। कृपया या तो सभी A/a प्रविष्टियाँ करें या सभी संख्यात्मक मार्क्स भरें।",
    'instructor.validation.step2.total_formula_mismatch': "Sheet '{sheet_name}' में {cell} पर मौजूद कुल (Total) मार्क्स का फ़ॉर्मूला बदल दिया गया है।",
    'instructor.validation.step2.co_formula_mismatch': "Sheet '{sheet_name}' में {cell} पर मौजूद CO विभाजन (split) का फ़ॉर्मूला बदल दिया गया है।",
    'instructor.validation.step2.structure_snapshot_missing': "Sheet '{sheet_name}' के लेआउट मैनिफ़ेस्ट में मार्क्स-संरचना (mark-structure) से संबंधित मेटाडेटा मौजूद नहीं है।",
    'instructor.validation.step2.structure_snapshot_mismatch': "Sheet '{sheet_name}' में मार्क्स-संरचना से संबंधित सेल {cell} बदल दिया गया है।",
    'instructor.validation.step2.student_identity_spec_invalid': "Sheet '{sheet_name}' के लेआउट मैनिफ़ेस्ट में छात्र की पहचान से संबंधित मेटाडेटा गलत है।",
    'instructor.validation.step2.student_identity_mismatch': "Sheet '{sheet_name}' में छात्रों के पंजीकरण संख्या (Reg. No.)/नाम वाली पंक्तियों में बदलाव किया गया है। संशोधित किया गया।",
    'instructor.validation.step2.student_reg_duplicate': "शीट '{sheet_name}' में छात्र का पंजीकरण क्रमांक '{reg_no}' डुप्लीकेट है।",
    'instructor.validation.step2.student_identity_cross_sheet_mismatch': "शीट '{sheet_name}' में छात्र के पंजीकरण क्रमांक/नाम वाली पंक्तियाँ, शीट '{reference_sheet}' से मेल नहीं खातीं।",
    'instructor.validation.final_report.layout_manifest_invalid': 'अंतिम रिपोर्ट तैयार नहीं हो सकी: लेआउट मैनिफेस्ट अमान्य है।',
    'instructor.validation.final_report.direct_component_sheet_missing': "अंतिम रिपोर्ट तैयार नहीं हो सकी: '{component}' के लिए प्रत्यक्ष घटक शीट मौजूद नहीं है।",
    'instructor.validation.final_report.direct_component_marks_shape_invalid': "अंतिम रिपोर्ट तैयार नहीं हो सकी: घटक '{component}' के लिए अंकों का आकार अमान्य है।",
    'instructor.validation.final_report.no_direct_components': 'अंतिम रिपोर्ट तैयार नहीं हो सकी: कोई प्रत्यक्ष घटक (प्रत्यक्ष घटक) नहीं मिला।',
    'coordinator.title': 'कोर्स अटेनमेंट',
    'coordinator.drop_hint': 'इंस्ट्रक्टर मॉड्यूल से तैयार की गई अंतिम CO रिपोर्ट वर्कबुक्स अपलोड करें।',
    'coordinator.calculate': 'CO प्राप्ति की गणना करें',
    'coordinator.thresholds.title': 'CO प्राप्ति सीमाएँ',
    'coordinator.thresholds.description': (
        '- L1 सीमा - पाठ्यक्रम का पास अंक या पिछली विनियमन में चलाए गए 3 बैचों का पाठ्यक्रम औसत।\n'
        '- L2 सीमा - प्रथम श्रेणी।\n'
        '- L3 सीमा - विशिष्ट श्रेणी।'
    ),
    'coordinator.thresholds.l1.label': 'L1 सीमा:',
    'coordinator.thresholds.l2.label': 'L2 सीमा:',
    'coordinator.thresholds.l3.label': 'L3 सीमा:',
    'coordinator.thresholds.invalid_rule': 'थ्रेशोल्ड नियम उल्लंघन: 0 < L1 < L2 < L3 < 100 रखें।',
    'coordinator.co_attainment.description': 'यदि निम्न % विद्यार्थी तय स्तर और उससे ऊपर हैं, तो प्राप्त माना जाएगा।',
    'coordinator.co_attainment.percent.label': 'CO AT%:',
    'coordinator.co_attainment.level.label': 'CO AT स्तर:',
    'coordinator.co_attainment.invalid_percent': 'अमान्य CO AT%: मान 0 से 100 के बीच होना चाहिए।',
    'coordinator.dialog.title': 'Excel फ़ाइलें चुनें',
    'coordinator.links.downloaded_output': 'डाउनलोड किया गया आउटपुट',
    'coordinator.summary': 'फ़ाइलें: {count}',
    'coordinator.file.remove_fallback': 'हटाएँ',
    'coordinator.file.remove_tooltip': 'फ़ाइल हटाएँ',
    'coordinator.clear_all': 'सभी साफ़ करें',
    'coordinator.status.added': '{added} फ़ाइल(ें) जोड़ी गईं। कुल: {total}।',
    'coordinator.duplicate.title': 'फ़ाइल पहले से मौजूद है',
    'coordinator.duplicate.body': '{count} डुप्लीकेट फ़ाइल(ें) छोड़ दी गईं क्योंकि वे पहले से ही सूची में मौजूद हैं।',
    'coordinator.invalid_final_report.title': 'अमान्य फ़ाइनल CO रिपोर्ट',
    'coordinator.invalid_final_report.body': 'केवल इंस्ट्रक्टर चरण 2 से जेनरेट की गई फ़ाइनल CO रिपोर्ट वर्कबुक की अनुमति है।\\n\\n{files}',
    'coordinator.invalid_final_report.details_prefix': 'विवरण:',
    'coordinator.invalid_final_report.detail_line': '{file}: {reason}',
    'coordinator.status.ignored': '{count} फ़ाइल(ें) नज़रअंदाज़ कर दी गईं (असमर्थित प्रकार, गुम, डुप्लीकेट, या अमान्य फ़ाइनल रिपोर्ट वर्कबुक)।',
    'coordinator.status.removed': '{count} फ़ाइलें हटाई गईं।',
    'coordinator.status.cleared': '{count} फ़ाइलें साफ़ की गईं।',
    'coordinator.status.processing_started': 'चुनी गई फ़ाइलों की प्रोसेसिंग हो रही है...',
    'coordinator.status.queued': 'जब मौजूदा प्रोसेसिंग चल रही थी, तब {count} फ़ाइलें कतार में लगाई गईं।',
    'coordinator.status.operation_cancelled': 'कोऑर्डिनेटर प्रोसेसिंग रद्द कर दी गई।',
    'coordinator.status.processing_failed': 'कोऑर्डिनेटर प्रोसेसिंग असफल रही।',
    'coordinator.status.processing_completed': 'कोऑर्डिनेटर प्रोसेसिंग पूरी हो गई।',
    'coordinator.status.calculate_completed': 'CO प्राप्ति की गणना पूरी हो गई और आउटपुट वर्कबुक तैयार हो गई।',
    'coordinator.regno_dedup.title': 'डुप्लीकेट रजिस्टर नंबर हटाए गए',
    'coordinator.regno_dedup.body': 'CO प्राप्ति बनाते समय {count} डुप्लीकेट रजिस्टर नंबर प्रविष्टियाँ हटाई गईं।',
    'coordinator.regno_dedup.log_body': '{count} डुप्लीकेट रजिस्टर नंबर प्रविष्टियाँ हटाई गईं:\\n{details}',
    'coordinator.regno_dedup.log_detail': 'रजिस्टर नंबर: {reg_no} | वर्कशीट: {worksheet} | वर्कबुक: {workbook}',
    'coordinator.regno_dedup.log_detail_unavailable': 'डुप्लीकेट प्रविष्टि का विवरण उपलब्ध नहीं है।',
    'coordinator.join_drop.body': 'कुछ पंक्तियों को नज़रअंदाज़ किया गया क्योंकि वे केवल Direct या केवल Indirect शीट में थीं। हटाई गई पंक्तियाँ: {count}। विवरण के लिए एक्टिविटी लॉग देखें।',
    'co_analysis.status.duplicate_reg_numbers': 'डुप्लीकेट रजिस्टर नंबर के कारण {count} फ़ाइल(ें) अस्वीकार की गईं।',
    'co_analysis.status.co_count_mismatch': 'कुल परिणाम संख्या असंगति के कारण {count} फ़ाइल(ें) अस्वीकार की गईं।',
    'co_analysis.status.validation_warnings': '{count} वैलिडेशन चेतावनी(याँ) रिपोर्ट हुईं।',
    'co_analysis.status.rejected_code_with_context': 'अस्वीकृत {file}: {code} ({context})',
    'co_analysis.validation.co_count_mismatch_body': 'चयनित बैच से कुल परिणाम संख्या अलग होने के कारण {count} फ़ाइल(ें) अस्वीकार की गईं।',
    'co_analysis.validation.anomaly_warnings_body': 'अपलोड की गई फ़ाइलों में {count} वैलिडेशन विसंगति चेतावनी(याँ) रिपोर्ट हुईं।',
    'co_analysis.validation.rejection_breakdown_title': 'CO Analysis फ़ाइल अस्वीकृति',
    'co_analysis.validation.rejection_breakdown_body': (
        'कारण अनुसार अस्वीकृत फ़ाइलें:\\n'
        'असमर्थित/गायब: {unsupported_or_missing}\\n'
        'अमान्य वर्कबुक: {invalid_workbook}\\n'
        'सिस्टम हैश/पहचान विफल: {invalid_hash}\\n'
        'अधूरे मार्क्स: {marks_unfilled}\\n'
        'लेआउट/मैनिफेस्ट विफल: {layout_manifest}\\n'
        'टेम्प्लेट असंगति: {template_mismatch}\\n'
        'अमान्य मार्क वैल्यू/फॉर्मेट: {mark_value}\\n'
        'अन्य वैलिडेशन विफल: {invalid_other}\\n'
        'डुप्लीकेट: {duplicates}\\n'
        'डुप्लीकेट रजिस्टर नंबर: {duplicate_reg}\\n'
        'कुल परिणाम संख्या असंगति: {co_count_mismatch}'
    ),
    'co_analysis.status.ignored_summary': (
        '{count} फ़ाइल(ें) अनदेखी की गईं। '
        '{part1}{sep1_2}{part2}{sep2_3}{part3}{sep3_4}{part4}{sep4_5}{part5}{sep5_6}{part6}'
        '{sep6_7}{part7}{sep7_8}{part8}{sep8_9}{part9}{sep9_10}{part10}{sep10_11}{part11}{sep11_12}{part12}'
    ),
    'co_analysis.status.ignored_total': '{count} फ़ाइल(ें) अनदेखी की गईं।',
    'co_analysis.status.ignored_reason.unsupported_or_missing': 'असमर्थित/गायब={count}',
    'co_analysis.status.ignored_reason.invalid_workbook': 'अमान्य वर्कबुक={count}',
    'co_analysis.status.ignored_reason.invalid_hash': 'हैश={count}',
    'co_analysis.status.ignored_reason.marks_unfilled': 'अधूरे मार्क्स={count}',
    'co_analysis.status.ignored_reason.layout_manifest': 'लेआउट/मैनिफेस्ट={count}',
    'co_analysis.status.ignored_reason.template_mismatch': 'टेम्प्लेट असंगति={count}',
    'co_analysis.status.ignored_reason.mark_value': 'अमान्य मार्क वैल्यू={count}',
    'co_analysis.status.ignored_reason.invalid_other': 'अन्य वैलिडेशन={count}',
    'co_analysis.status.ignored_reason.duplicates': 'डुप्लीकेट={count}',
    'co_analysis.status.ignored_reason.duplicate_reg': 'डुप्लीकेट रजिस्टर नंबर={count}',
    'co_analysis.status.ignored_reason.co_count_mismatch': 'कुल परिणाम संख्या असंगति={count}',
}




