"""Tamil (India) text catalog for user-facing strings."""

TEXTS = {
    # Startup / main
    "app.already_running": "à®ªà®¯à®©à¯à®ªà®¾à®Ÿà¯ à®à®±à¯à®•à®©à®µà¯‡ à®‡à®¯à®™à¯à®•à®¿à®•à¯à®•à¯Šà®£à¯à®Ÿà®¿à®°à¯à®•à¯à®•à®¿à®±à®¤à¯.",
    "app.unexpected_error": "à®Žà®¤à®¿à®°à¯à®ªà®¾à®°à®¾à®¤ à®ªà®¿à®´à¯ˆ à®à®±à¯à®ªà®Ÿà¯à®Ÿà®¤à¯. à®ªà®¤à®¿à®µà¯ à®•à¯‹à®ªà¯à®ªà¯ˆ à®šà®°à®¿à®ªà®¾à®°à¯à®•à¯à®•à®µà¯à®®à¯.",
    "app.subtitle": "Framework for Outcome Computation and Unification System",
    "app.main_window_title": "FOCUS",
    "splash.starting": "à®ªà®¯à®©à¯à®ªà®¾à®Ÿà¯ à®¤à¯Šà®Ÿà®™à¯à®•à¯à®•à®¿à®±à®¤à¯...",
    "splash.loading_main_window": "à®®à¯à®¤à®©à¯à®®à¯ˆ à®šà®¾à®³à®°à®®à¯ à®à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®•à®¿à®±à®¤à¯...",
    # Main window
    "toolbar.navigation": "à®µà®´à®¿à®šà¯†à®²à¯à®¤à¯à®¤à®²à¯",
    "status.ready": "à®¤à®¯à®¾à®°à¯",
    "module.placeholder": "{title} à®¤à¯Šà®•à¯à®¤à®¿ à®‡à®©à¯à®©à¯à®®à¯ à®šà¯†à®¯à®²à¯à®ªà®Ÿà¯à®¤à¯à®¤à®ªà¯à®ªà®Ÿà®µà®¿à®²à¯à®²à¯ˆ.",
    "module.instructor": "à®ªà®¯à®¿à®±à¯à®±à¯à®¨à®°à¯",
    "module.course_coordinator": "à®ªà®¾à®Ÿ à®’à®°à¯à®™à¯à®•à®¿à®£à¯ˆà®ªà¯à®ªà®¾à®³à®°à¯",
    "module.coordinator_short": "à®’à®°à¯à®™à¯à®•à®¿à®£à¯ˆà®ªà¯à®ªà®¾à®³à®°à¯",
    "module.po_analysis": "PO à®ªà®•à¯à®ªà¯à®ªà®¾à®¯à¯à®µà¯",
    "module.load_failed_title": "à®¤à¯Šà®•à¯à®¤à®¿ à®à®±à¯à®±à®ªà¯ à®ªà®¿à®´à¯ˆ",
    "module.load_failed_body": "'{module}' à®¤à¯Šà®•à¯à®¤à®¿à®¯à¯ˆ à®à®±à¯à®± à®®à¯à®Ÿà®¿à®¯à®µà®¿à®²à¯à®²à¯ˆ.\n\nà®µà®¿à®µà®°à®®à¯: {error}",
    "module.load_failed_status": "à®¤à¯Šà®•à¯à®¤à®¿à®¯à¯ˆ à®à®±à¯à®± à®®à¯à®Ÿà®¿à®¯à®µà®¿à®²à¯à®²à¯ˆ: {module}.",
    "nav.help": "à®‰à®¤à®µà®¿",
    "nav.about": "à®ªà®±à¯à®±à®¿",
    # Settings module
    "settings.title": "à®ªà®¯à®©à¯à®ªà®¾à®Ÿà¯à®Ÿà¯ à®…à®®à¯ˆà®ªà¯à®ªà¯à®•à®³à¯",
    "settings.theme": "à®¤à¯€à®®à¯",
    "settings.language": "à®®à¯Šà®´à®¿",
    "settings.theme.system": "à®•à®£à®¿à®©à®¿ à®‡à®¯à®²à¯à®ªà¯à®¨à®¿à®²à¯ˆ",
    "settings.theme.light": "à®’à®³à®¿",
    "settings.theme.dark": "à®‡à®°à¯à®³à¯",
    "settings.language.system": "à®•à®£à®¿à®©à®¿ à®®à¯Šà®´à®¿",
    "settings.apply": "à®ªà®¯à®©à¯à®ªà®Ÿà¯à®¤à¯à®¤à¯",
    "settings.saved.title": "à®…à®®à¯ˆà®ªà¯à®ªà¯à®•à®³à¯ à®ªà¯à®¤à¯à®ªà¯à®ªà®¿à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®©",
    "settings.saved.body": "à®®à¯Šà®´à®¿ à®µà®¿à®°à¯à®ªà¯à®ªà®®à¯ à®šà¯†à®¯à®²à¯à®ªà®Ÿà¯à®¤à¯à®¤à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "settings.saved.status": "à®…à®®à¯ˆà®ªà¯à®ªà¯à®•à®³à¯ à®ªà®¯à®©à¯à®ªà®Ÿà¯à®¤à¯à®¤à®ªà¯à®ªà®Ÿà¯à®Ÿà®©.",
    "language.switcher.button": "à®®à¯Šà®´à®¿: {language}",
    "language.switcher.status": "à®®à¯Šà®´à®¿ {language}",
    "language.switcher.applied_status": "à®®à¯Šà®´à®¿ {language} à®†à®• à®…à®®à¯ˆà®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "language.name.en": "à®†à®™à¯à®•à®¿à®²à®®à¯",
    "language.name.ta-in": "à®¤à®®à®¿à®´à¯ (à®‡à®¨à¯à®¤à®¿à®¯à®¾)",
    # About
    "about.version": "à®ªà®¤à®¿à®ªà¯à®ªà¯ {version}",
    "about.description": (
        "{app_name} à®Žà®©à¯à®ªà®¤à¯ Course Outcome (CO) à®…à®Ÿà¯ˆà®µà¯ˆ à®•à®£à®•à¯à®•à®¿à®Ÿà®µà¯à®®à¯, "
        "à®¨à¯‡à®°à®Ÿà®¿ à®®à®±à¯à®±à¯à®®à¯ à®®à®±à¯ˆà®®à¯à®• à®®à®¤à®¿à®ªà¯à®ªà¯€à®Ÿà¯à®•à®³à¯ˆ à®…à®Ÿà®¿à®ªà¯à®ªà®Ÿà¯ˆà®¯à®¾à®•à®•à¯ à®•à¯Šà®£à¯à®Ÿà¯ "
        "à®•à®Ÿà¯à®Ÿà®®à¯ˆà®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à¯à®Ÿà®¿à®µà¯ à®ªà®•à¯à®ªà¯à®ªà®¾à®¯à¯à®µà¯ˆ à®šà¯†à®¯à¯à®¯à®µà¯à®®à¯ à®µà®Ÿà®¿à®µà®®à¯ˆà®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à¯†à®©à¯à®ªà¯Šà®°à¯à®³à¯ à®•à®°à¯à®µà®¿."
    ),
    "about.institution": "à®•à®²à®šà®²à®¿à®™à¯à®•à®®à¯ à®†à®°à®¾à®¯à¯à®šà¯à®šà®¿ à®®à®±à¯à®±à¯à®®à¯ à®•à®²à¯à®µà®¿ à®•à®´à®•à®®à¯ (KARE) à®‡à®²à¯ à®‰à®°à¯à®µà®¾à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "about.copyright": "(c) {year} KARE. à®…à®©à¯ˆà®¤à¯à®¤à¯ à®‰à®°à®¿à®®à¯ˆà®•à®³à¯à®®à¯ à®ªà®¾à®¤à¯à®•à®¾à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®µà¯ˆ.",
    # Help module
    "help.doc_missing_title": "à®‰à®¤à®µà®¿ à®†à®µà®£à®®à¯ à®‡à®²à¯à®²à¯ˆ",
    "help.doc_missing_body": "à®‰à®¤à®µà®¿ PDF à®•à®¿à®Ÿà¯ˆà®•à¯à®•à®µà®¿à®²à¯à®²à¯ˆ:\n{path}",
    "help.doc_error_title": "à®‰à®¤à®µà®¿ à®†à®µà®£à®ªà¯ à®ªà®¿à®´à¯ˆ",
    "help.doc_error_body": "à®‰à®¤à®µà®¿ PDF à® à®à®±à¯à®± à®®à¯à®Ÿà®¿à®¯à®µà®¿à®²à¯à®²à¯ˆ.",
    "help.download_pdf": "PDF à®ªà®¤à®¿à®µà®¿à®±à®•à¯à®•à¯",
    "help.open_default_viewer": "à®‡à®¯à®²à¯à®ªà¯à®¨à®¿à®²à¯ˆ à®ªà®¾à®°à¯à®µà®¿à®¯à®¿à®²à¯ à®¤à®¿à®±",
    "help.missing_file_title": "à®•à¯‹à®ªà¯à®ªà¯ à®‡à®²à¯à®²à¯ˆ",
    "help.missing_file_body": "à®‰à®¤à®µà®¿ PDF à®•à®¿à®Ÿà¯ˆà®•à¯à®•à®µà®¿à®²à¯à®²à¯ˆ.",
    "help.save_title": "CO à®…à®Ÿà¯ˆà®µà¯ à®†à®µà®£à®¤à¯à®¤à¯ˆ à®šà¯‡à®®à®¿",
    "help.save_default_name": "CO_Calculation_Document.pdf",
    "help.save_filter_pdf": "PDF à®•à¯‹à®ªà¯à®ªà¯à®•à®³à¯ (*.pdf)",
    "help.save_failed_title": "à®šà¯‡à®®à®¿à®¤à¯à®¤à®²à¯ à®¤à¯‹à®²à¯à®µà®¿",
    "help.save_failed_body": "à®‰à®¤à®µà®¿ PDF à®šà¯‡à®®à®¿à®•à¯à®•à¯à®®à¯ à®ªà¯‹à®¤à¯ à®ªà®¿à®´à¯ˆ à®à®±à¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "help.save_success_title": "à®šà¯‡à®®à®¿à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯",
    "help.save_success_body": "à®‰à®¤à®µà®¿ PDF à®µà¯†à®±à¯à®±à®¿à®•à®°à®®à®¾à®• à®šà¯‡à®®à®¿à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "help.open_failed_title": "à®¤à®¿à®±à®¤à¯à®¤à®²à¯ à®¤à¯‹à®²à¯à®µà®¿",
    "help.open_failed_body": "à®‡à®¯à®²à¯à®ªà¯à®¨à®¿à®²à¯ˆ à®ªà®¾à®°à¯à®µà®¿à®¯à®¿à®²à¯ à®‰à®¤à®µà®¿ PDF à® à®¤à®¿à®±à®•à¯à®• à®®à¯à®Ÿà®¿à®¯à®µà®¿à®²à¯à®²à¯ˆ.",
    "help.open_success_title": "à®¤à®¿à®±à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯",
    "help.open_success_body": "à®‰à®¤à®µà®¿ PDF à®‡à®¯à®²à¯à®ªà¯à®¨à®¿à®²à¯ˆ à®ªà®¾à®°à¯à®µà®¿à®¯à®¿à®²à¯ à®¤à®¿à®±à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "help.status.doc_loaded": "à®‰à®¤à®µà®¿ à®†à®µà®£à®®à¯ à®à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "help.status.doc_missing": "à®‰à®¤à®µà®¿ à®†à®µà®£à®®à¯ à®‡à®²à¯à®²à¯ˆ.",
    "help.status.doc_error": "à®‰à®¤à®µà®¿ à®†à®µà®£à®¤à¯à®¤à¯ˆ à®à®±à¯à®± à®®à¯à®Ÿà®¿à®¯à®µà®¿à®²à¯à®²à¯ˆ.",
    "help.status.file_missing": "à®‰à®¤à®µà®¿ PDF à®•à®¿à®Ÿà¯ˆà®•à¯à®•à®µà®¿à®²à¯à®²à¯ˆ.",
    "help.status.save_success": "à®‰à®¤à®µà®¿ PDF à®µà¯†à®±à¯à®±à®¿à®•à®°à®®à®¾à®• à®šà¯‡à®®à®¿à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "help.status.save_failed": "à®‰à®¤à®µà®¿ PDF à®šà¯‡à®®à®¿à®•à¯à®•à¯à®®à¯ à®ªà¯‹à®¤à¯ à®ªà®¿à®´à¯ˆ à®à®±à¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "help.status.open_success": "à®‰à®¤à®µà®¿ PDF à®‡à®¯à®²à¯à®ªà¯à®¨à®¿à®²à¯ˆ à®ªà®¾à®°à¯à®µà®¿à®¯à®¿à®²à¯ à®¤à®¿à®±à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "help.status.open_failed": "à®‰à®¤à®µà®¿ PDF à®¤à®¿à®±à®•à¯à®•à¯à®®à¯ à®ªà¯‹à®¤à¯ à®ªà®¿à®´à¯ˆ à®à®±à¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    # Instructor module
    "instructor.workflow_title": "CO à®ªà®£à®¿à®šà¯à®šà¯à®±à¯à®±à¯",
    "instructor.progress": "{completed} / {total} à®®à¯à®Ÿà®¿à®¨à¯à®¤à®¤à¯",
    "instructor.step_button": "{number}. {title}",
    "instructor.step1.title": "à®ªà®¾à®Ÿ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯ˆ à®ªà®¤à®¿à®µà®¿à®±à®•à¯à®•à¯",
    "instructor.step2.title": "à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯ˆ à®‰à®°à¯à®µà®¾à®•à¯à®•à¯",
    "instructor.step3.title": "CO à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®…à®±à®¿à®•à¯à®•à¯ˆà®¯à¯ˆ à®‰à®°à¯à®µà®¾à®•à¯à®•à¯",
    "instructor.step4.title": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯à®•à®³à¯ˆ à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à¯",
    "instructor.step5.title": "à®‡à®±à¯à®¤à®¿ CO à®…à®±à®¿à®•à¯à®•à¯ˆà®¯à¯ˆ à®‰à®°à¯à®µà®¾à®•à¯à®•à¯",
    "instructor.step1.desc": "à®ªà®¾à®Ÿ à®µà®¿à®µà®°à®™à¯à®•à®³à¯ˆ à®‰à®³à¯à®³à®¿à®Ÿ à®ªà®¯à®©à¯à®ªà®Ÿà¯à®¤à¯à®¤à®ªà¯à®ªà®Ÿà¯à®®à¯ à®•à®¾à®²à®¿ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯ˆ à®ªà®¤à®¿à®µà®¿à®±à®•à¯à®•à®µà¯à®®à¯.",
    "instructor.step2.desc": "à®šà®°à®¿à®ªà®¾à®°à¯à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®ªà®¾à®Ÿ à®µà®¿à®µà®° à®•à¯‹à®ªà¯à®ªà¯ˆ à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à®¿, à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯ˆ à®¤à®¯à®¾à®°à®¿à®¤à¯à®¤à¯ à®šà¯‡à®®à®¿à®•à¯à®•à®µà¯à®®à¯.",
    "instructor.step3.desc": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®ªà®£à®¿à®ªà¯à®ªà¯à®¤à¯à®¤à®•à®¤à¯à®¤à¯ˆ à®šà®°à®¿à®ªà®¾à®°à¯à®¤à¯à®¤à¯ à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à®¿, à®‡à®±à¯à®¤à®¿ CO à®…à®±à®¿à®•à¯à®•à¯ˆà®¯à¯ˆ à®‰à®°à¯à®µà®¾à®•à¯à®•à®µà¯à®®à¯.",
    "instructor.step4.desc": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®ªà®£à®¿à®ªà¯à®ªà¯à®¤à¯à®¤à®•à®¤à¯à®¤à¯ˆ à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à®µà¯à®®à¯.",
    "instructor.step5.desc": "à®’à®µà¯à®µà¯Šà®°à¯ à®®à®¾à®£à®µà®°à¯à®•à¯à®•à¯à®®à¯ à®•à®£à®•à¯à®•à®¿à®Ÿà®ªà¯à®ªà®Ÿà¯à®Ÿ CO à®®à¯Šà®¤à¯à®¤à®™à¯à®•à®³à¯à®Ÿà®©à¯ à®‡à®±à¯à®¤à®¿ à®ªà®£à®¿à®ªà¯à®ªà¯à®¤à¯à®¤à®•à®¤à¯à®¤à¯ˆ à®‰à®°à¯à®µà®¾à®•à¯à®•à®µà¯à®®à¯.",
    "instructor.badge.pending": "à®¨à®¿à®²à¯à®µà¯ˆà®¯à®¿à®²à¯",
    "instructor.badge.done": "à®®à¯à®Ÿà®¿à®¨à¯à®¤à®¤à¯",
    "instructor.badge.needs_update": "à®ªà¯à®¤à¯à®ªà¯à®ªà®¿à®ªà¯à®ªà¯ à®¤à¯‡à®µà¯ˆ",
    "instructor.links.title": "à®‰à®°à¯à®µà®¾à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®µà¯†à®³à®¿à®¯à¯€à®Ÿà¯à®•à®³à¯",
    "instructor.links.course_details_generated": "à®‰à®°à¯à®µà®¾à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®ªà®¾à®Ÿ à®µà®¿à®µà®° à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯",
    "instructor.links.course_details_uploaded": "à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿ à®ªà®¾à®Ÿ à®µà®¿à®µà®° à®•à¯‹à®ªà¯à®ªà¯",
    "instructor.links.marks_template_generated": "à®‰à®°à¯à®µà®¾à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯",
    "instructor.links.marks_template_uploaded": "à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯",
    "instructor.links.open_file": "à®•à¯‹à®ªà¯à®ªà¯ˆ à®¤à®¿à®±",
    "instructor.links.open_folder": "à®•à¯‹à®ªà¯à®ªà¯à®±à¯ˆà®¯à¯ˆ à®¤à®¿à®±",
    "instructor.links.not_available": "à®‡à®©à¯à®©à¯à®®à¯ à®•à®¿à®Ÿà¯ˆà®•à¯à®•à®µà®¿à®²à¯à®²à¯ˆ",
    "instructor.links.open_failed": "à®¤à¯‡à®°à¯à®¨à¯à®¤à¯†à®Ÿà¯à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®ªà®¾à®¤à¯ˆà®¯à¯ˆ à®¤à®¿à®±à®•à¯à®• à®®à¯à®Ÿà®¿à®¯à®µà®¿à®²à¯à®²à¯ˆ.",
    "instructor.file.none": "à®‡à®©à¯à®©à¯à®®à¯ à®•à¯‹à®ªà¯à®ªà¯/à®ªà®¾à®¤à¯ˆ à®¤à¯‡à®°à¯à®µà¯ à®šà¯†à®¯à¯à®¯à®ªà¯à®ªà®Ÿà®µà®¿à®²à¯à®²à¯ˆ.",
    "instructor.note.default": "à®®à¯à®Ÿà®¿à®¤à¯à®¤ à®Žà®¨à¯à®¤ à®ªà®Ÿà®¿à®¯à¯ˆà®¯à¯à®®à¯ à®®à¯€à®£à¯à®Ÿà¯à®®à¯ à®¤à®¿à®±à®¨à¯à®¤à¯ à®®à®¾à®±à¯à®±à®²à®¾à®®à¯.",
    "instructor.note.outdated_current": "à®‡à®¨à¯à®¤ à®ªà®Ÿà®¿ à®•à®¾à®²à®¾à®µà®¤à®¿à®¯à®¾à®©à®¤à¯. à®‡à®¨à¯à®¤ à®ªà®Ÿà®¿à®¯à¯ˆ à®®à¯€à®£à¯à®Ÿà¯à®®à¯ à®‡à®¯à®•à¯à®•à®µà¯à®®à¯.",
    "instructor.note.outdated_downstream": "à®®à¯‡à®²à¯à®¨à®¿à®²à¯ˆ à®®à®¾à®±à¯à®±à®®à¯ à®šà¯†à®¯à¯à®¯à®ªà¯à®ªà®Ÿà¯à®Ÿà¯à®³à¯à®³à®¤à¯. à®…à®Ÿà¯à®¤à¯à®¤ à®ªà®Ÿà®¿à®•à®³à¯ˆ à®®à¯€à®£à¯à®Ÿà¯à®®à¯ à®‰à®°à¯à®µà®¾à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà®¿ à®‡à®°à¯à®•à¯à®•à®²à®¾à®®à¯.",
    "instructor.active_title": "à®ªà®Ÿà®¿ {number}: {title}",
    "instructor.action.step1.default": "à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯ˆ à®ªà®¤à®¿à®µà®¿à®±à®•à¯à®•à¯",
    "instructor.action.step1.redo": "à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯ˆ à®®à¯€à®£à¯à®Ÿà¯à®®à¯ à®ªà®¤à®¿à®µà®¿à®±à®•à¯à®•à¯",
    "instructor.action.step2.default": "à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à¯ & à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯ à®‰à®°à¯à®µà®¾à®•à¯à®•à¯",
    "instructor.action.step2.redo": "à®®à®¾à®±à¯à®±à®¿ & à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯ à®®à¯€à®£à¯à®Ÿà¯à®®à¯ à®‰à®°à¯à®µà®¾à®•à¯à®•à¯",
    "instructor.action.step2.upload": "à®ªà®¾à®Ÿ à®µà®¿à®µà®°à®™à¯à®•à®³à¯ˆ à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à¯",
    "instructor.action.step2.prepare": "à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯ˆ à®¤à®¯à®¾à®°à®¿",
    "instructor.action.step4.default": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯à®•à®³à¯ˆ à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à¯",
    "instructor.action.step4.redo": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯à®•à®³à¯ˆ à®®à®¾à®±à¯à®±à¯",
    "instructor.action.step5.default": "à®‡à®±à¯à®¤à®¿ CO à®…à®±à®¿à®•à¯à®•à¯ˆà®¯à¯ˆ à®‰à®°à¯à®µà®¾à®•à¯à®•à¯",
    "instructor.action.step5.redo": "à®‡à®±à¯à®¤à®¿ CO à®…à®±à®¿à®•à¯à®•à¯ˆà®¯à¯ˆ à®®à¯€à®£à¯à®Ÿà¯à®®à¯ à®‰à®°à¯à®µà®¾à®•à¯à®•à¯",
    "instructor.require.step2": "à®®à¯à®¤à®²à®¿à®²à¯ à®ªà®Ÿà®¿ 2 à® à®®à¯à®Ÿà®¿à®•à¯à®•à®µà¯à®®à¯.",
    "instructor.require.step3": "à®®à¯à®¤à®²à®¿à®²à¯ à®ªà®Ÿà®¿ 3 à® à®®à¯à®Ÿà®¿à®•à¯à®•à®µà¯à®®à¯.",
    "instructor.msg.success_title": "à®µà¯†à®±à¯à®±à®¿",
    "instructor.msg.validation_title": "à®šà®°à®¿à®ªà®¾à®°à¯à®ªà¯à®ªà¯ à®ªà®¿à®´à¯ˆ",
    "instructor.msg.error_title": "à®¤à¯‹à®²à¯à®µà®¿",
    "instructor.msg.step_completed": "à®ªà®Ÿà®¿ {step} à®®à¯à®Ÿà®¿à®¨à¯à®¤à®¤à¯: {title}.",
    "instructor.msg.failed_to_do": "{action} à®šà¯†à®¯à¯à®¯ à®®à¯à®Ÿà®¿à®¯à®µà®¿à®²à¯à®²à¯ˆ.",
    "instructor.msg.step_required_title": "à®ªà®Ÿà®¿ à®¤à¯‡à®µà¯ˆ",
    "instructor.dialog.filter.excel": "Excel à®•à¯‹à®ªà¯à®ªà¯à®•à®³à¯ (*.xlsx)",
    "instructor.dialog.filter.excel_open": "Excel à®•à¯‹à®ªà¯à®ªà¯à®•à®³à¯ (*.xlsx *.xlsm *.xls)",
    "instructor.dialog.step1.title": "à®ªà®¾à®Ÿ à®µà®¿à®µà®° à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯ˆ à®šà¯‡à®®à®¿à®•à¯à®•",
    "instructor.dialog.step1.default_name": "course_details_template.xlsx",
    "instructor.dialog.step2.title": "à®ªà®¾à®Ÿ à®µà®¿à®µà®° à®•à¯‹à®ªà¯à®ªà¯ˆ à®¤à¯‡à®°à¯à®µà¯ à®šà¯†à®¯à¯à®¯",
    "instructor.dialog.step3.title": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®•à¯‹à®ªà¯à®ªà¯ˆ à®¤à¯‡à®°à¯à®µà¯ à®šà¯†à®¯à¯à®¯",
    "instructor.dialog.step3.default_name": "marks_template.xlsx",
    "instructor.dialog.step4.title": "à®‡à®±à¯à®¤à®¿ CO à®…à®±à®¿à®•à¯à®•à¯ˆà®¯à¯ˆ à®šà¯‡à®®à®¿à®•à¯à®•",
    "instructor.dialog.step4.default_name": "co_report.xlsx",
    "instructor.status.step1_selected": "à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯ à®ªà®¤à®¿à®µà®¿à®±à®•à¯à®•à®ªà¯ à®ªà®¾à®¤à¯ˆ à®¤à¯‡à®°à¯à®µà¯ à®šà¯†à®¯à¯à®¯à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "instructor.status.step2_validated": "à®ªà®¾à®Ÿ à®µà®¿à®µà®°à®™à¯à®•à®³à¯ à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿà¯ à®šà®°à®¿à®ªà®¾à®°à¯à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®©. à®‡à®ªà¯à®ªà¯‹à®¤à¯ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯ˆ à®¤à®¯à®¾à®°à®¿à®•à¯à®•à®²à®¾à®®à¯.",
    "instructor.status.step2_uploaded": "à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯ à®‰à®°à¯à®µà®¾à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "instructor.status.step2_changed": "à®ªà®¾à®Ÿ à®µà®¿à®µà®°à®™à¯à®•à®³à¯ à®®à®¾à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿà®©. à®…à®Ÿà¯à®¤à¯à®¤ à®ªà®Ÿà®¿à®•à®³à¯ˆ à®®à¯€à®£à¯à®Ÿà¯à®®à¯ à®šà¯†à®¯à¯à®¯à®µà¯à®®à¯.",
    "instructor.status.step3_selected": "à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯ à®‰à®°à¯à®µà®¾à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "instructor.status.step3_uploaded": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯à®•à®³à¯ à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿà®©.",
    "instructor.status.step3_changed": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯à®•à®³à¯ à®®à®¾à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿà®©. à®‡à®±à¯à®¤à®¿ à®…à®±à®¿à®•à¯à®•à¯ˆà®¯à¯ˆ à®®à¯€à®£à¯à®Ÿà¯à®®à¯ à®‰à®°à¯à®µà®¾à®•à¯à®•à®µà¯à®®à¯.",
    "instructor.status.step4_selected": "à®‡à®±à¯à®¤à®¿ CO à®…à®±à®¿à®•à¯à®•à¯ˆà®ªà¯ à®ªà®¾à®¤à¯ˆ à®¤à¯‡à®°à¯à®µà¯ à®šà¯†à®¯à¯à®¯à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "instructor.status.step4_changed": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯à®•à®³à¯ à®®à®¾à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿà®©. à®‡à®±à¯à®¤à®¿ à®…à®±à®¿à®•à¯à®•à¯ˆà®¯à¯ˆ à®®à¯€à®£à¯à®Ÿà¯à®®à¯ à®‰à®°à¯à®µà®¾à®•à¯à®•à®µà¯à®®à¯.",
    "instructor.status.operation_in_progress": "à®šà¯†à®¯à®²à¯ à®¨à®Ÿà¯ˆà®ªà¯†à®±à¯à®±à¯ à®•à¯Šà®£à¯à®Ÿà®¿à®°à¯à®•à¯à®•à®¿à®±à®¤à¯...",
    "instructor.status.operation_cancelled": "à®šà¯†à®¯à®²à¯ à®°à®¤à¯à®¤à¯ à®šà¯†à®¯à¯à®¯à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "instructor.log.title": "à®šà¯†à®¯à®²à¯ à®ªà®¤à®¿à®µà¯",
    "instructor.log.ready": "à®šà¯†à®¯à®²à¯ à®ªà®¤à®¿à®µà¯ à®¤à¯Šà®Ÿà®™à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "instructor.log.completed_process": "{process} à®µà¯†à®±à¯à®±à®¿à®•à®°à®®à®¾à®• à®®à¯à®Ÿà®¿à®¨à¯à®¤à®¤à¯.",
    "instructor.log.error_while_process": "{process} à®šà¯†à®¯à¯à®¯à¯à®®à¯ à®ªà¯‹à®¤à¯ à®ªà®¿à®´à¯ˆ à®à®±à¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    "instructor.log.process.generate_course_details_template": "à®ªà®¾à®Ÿ à®µà®¿à®µà®° à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯ˆ à®‰à®°à¯à®µà®¾à®•à¯à®•à¯à®¤à®²à¯",
    "instructor.log.process.validate_course_details_workbook": "à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿ à®ªà®¾à®Ÿ à®µà®¿à®µà®° workbook-à® à®šà®°à®¿à®ªà®¾à®°à¯à®¤à¯à®¤à®²à¯",
    "instructor.log.process.generate_marks_template": "à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯ˆ à®‰à®°à¯à®µà®¾à®•à¯à®•à¯à®¤à®²à¯",
    "instructor.log.process.upload_filled_marks_workbook": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ workbook-à® à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à¯à®¤à®²à¯",
    "instructor.log.process.generate_final_co_report": "à®‡à®±à¯à®¤à®¿ CO à®…à®±à®¿à®•à¯à®•à¯ˆà®¯à¯ˆ à®‰à®°à¯à®µà®¾à®•à¯à®•à¯à®¤à®²à¯",
    "instructor.validation.xlsxwriter_missing": "xlsxwriter à®¨à®¿à®±à¯à®µà®ªà¯à®ªà®Ÿà®µà®¿à®²à¯à®²à¯ˆ. à®ªà®¾à®Ÿ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®•à¯à®•à®³à¯ˆ à®‰à®°à¯à®µà®¾à®•à¯à®• à®…à®¤à¯ˆ à®¨à®¿à®±à¯à®µà®µà¯à®®à¯.",
    "instructor.validation.sheet_single_header_row": "'{sheet_name}' à®¤à®¾à®³à®¿à®²à¯ à®¤à¯à®²à¯à®²à®¿à®¯à®®à®¾à®• à®’à®°à¯ à®¤à®²à¯ˆà®ªà¯à®ªà¯ à®µà®°à®¿ à®®à®Ÿà¯à®Ÿà¯à®®à¯‡ à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.system.template_generate_failed": "'{output}' à®‡à®Ÿà®¤à¯à®¤à®¿à®²à¯ à®ªà®¾à®Ÿ à®µà®¿à®µà®° à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯ˆ à®‰à®°à¯à®µà®¾à®•à¯à®• à®®à¯à®Ÿà®¿à®¯à®µà®¿à®²à¯à®²à¯ˆ.",
    "instructor.validation.unknown_template": "à®…à®±à®¿à®¯à®ªà¯à®ªà®Ÿà®¾à®¤ workbook à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯ '{template_id}'. à®•à®¿à®Ÿà¯ˆà®•à¯à®•à¯à®®à¯ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®•à¯à®•à®³à¯: {available}.",
    "instructor.validation.invalid_sheet_name": "à®¤à®µà®±à®¾à®© à®¤à®¾à®³à¯ à®ªà¯†à®¯à®°à¯.",
    "instructor.validation.headers_empty": "'{sheet_name}' à®¤à®¾à®³à¯à®•à¯à®•à®¾à®© à®¤à®²à¯ˆà®ªà¯à®ªà¯à®•à®³à¯ à®•à®¾à®²à®¿à®¯à®¾à®• à®‡à®°à¯à®•à¯à®•à®•à¯à®•à¯‚à®Ÿà®¾à®¤à¯.",
    "instructor.validation.headers_unique": "'{sheet_name}' à®¤à®¾à®³à®¿à®²à¯ à®¤à®²à¯ˆà®ªà¯à®ªà¯à®•à®³à¯ à®¤à®©à®¿à®¤à¯à®¤à¯à®µà®®à®¾à®• à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.row_length_mismatch": "'{sheet_name}' à®¤à®¾à®³à®¿à®²à¯ à®µà®°à®¿ {row} à®¨à¯€à®³à®®à¯ à®ªà¯Šà®°à¯à®¨à¯à®¤à®µà®¿à®²à¯à®²à¯ˆ: à®Žà®¤à®¿à®°à¯à®ªà®¾à®°à¯à®ªà¯à®ªà¯ {expected}, à®•à®¿à®Ÿà¯ˆà®¤à¯à®¤à®¤à¯ {found}.",
    "instructor.validation.openpyxl_missing": "openpyxl à®¨à®¿à®±à¯à®µà®ªà¯à®ªà®Ÿà®µà®¿à®²à¯à®²à¯ˆ. à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿ à®ªà®¾à®Ÿ à®µà®¿à®µà®°à®™à¯à®•à®³à¯ˆ à®šà®°à®¿à®ªà®¾à®°à¯à®•à¯à®• à®…à®¤à¯ˆ à®¨à®¿à®±à¯à®µà®µà¯à®®à¯.",
    "instructor.validation.workbook_not_found": "à®ªà®¾à®Ÿ à®µà®¿à®µà®° workbook à®•à®¿à®Ÿà¯ˆà®•à¯à®•à®µà®¿à®²à¯à®²à¯ˆ: {workbook}",
    "instructor.validation.workbook_open_failed": "à®ªà®¾à®Ÿ à®µà®¿à®µà®° workbook '{workbook}' à® à®¤à®¿à®±à®•à¯à®• à®®à¯à®Ÿà®¿à®¯à®µà®¿à®²à¯à®²à¯ˆ.",
    "instructor.validation.system_sheet_missing": "à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿ workbook à®‡à®²à¯ à®¤à¯‡à®µà¯ˆà®¯à®¾à®© system à®¤à®¾à®³à¯ '{sheet}' à®‡à®²à¯à®²à¯ˆ.",
    "instructor.validation.system_hash_missing_template_id_header": "à®¤à®µà®±à®¾à®© system hash à®¤à®¾à®³à¯ à®µà®Ÿà®¿à®µà®®à¯: Template_ID header à®‡à®²à¯à®²à¯ˆ.",
    "instructor.validation.system_hash_missing_template_hash_header": "à®¤à®µà®±à®¾à®© system hash à®¤à®¾à®³à¯ à®µà®Ÿà®¿à®µà®®à¯: Template_Hash header à®‡à®²à¯à®²à¯ˆ.",
    "instructor.validation.system_hash_template_id_missing": "system hash à®¤à®¾à®³à®¿à®²à¯ Template_ID à®‡à®²à¯à®²à¯ˆ.",
    "instructor.validation.system_hash_mismatch": "Template hash à®ªà¯Šà®°à¯à®¨à¯à®¤à®µà®¿à®²à¯à®²à¯ˆ. à®šà®°à®¿à®¯à®¾à®© à®‰à®°à¯à®µà®¾à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯ˆà®ªà¯ à®ªà®¯à®©à¯à®ªà®Ÿà¯à®¤à¯à®¤à®µà¯à®®à¯.",
    "instructor.validation.workbook_sheet_mismatch": "Workbook à®¤à®¾à®³à¯à®•à®³à¯ '{template_id}' à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯à®Ÿà®©à¯ à®ªà¯Šà®°à¯à®¨à¯à®¤à®µà®¿à®²à¯à®²à¯ˆ. à®Žà®¤à®¿à®°à¯à®ªà®¾à®°à¯à®ªà¯à®ªà¯: {expected}. à®•à®¿à®Ÿà¯ˆà®¤à¯à®¤à®¤à¯: {found}.",
    "instructor.validation.header_mismatch": "'{sheet_name}' à®¤à®¾à®³à®¿à®²à¯ header à®ªà¯Šà®°à¯à®¨à¯à®¤à®µà®¿à®²à¯à®²à¯ˆ. à®Žà®¤à®¿à®°à¯à®ªà®¾à®°à¯à®ªà¯à®ªà¯: {expected}.",
    "instructor.validation.unexpected_header": "'{sheet_name}' à®¤à®¾à®³à®¿à®©à¯ à®¨à¯†à®Ÿà¯à®µà®°à®¿à®šà¯ˆ {col} à®‡à®²à¯ à®Žà®¤à®¿à®°à¯à®ªà®¾à®°à®¾à®¤ header.",
    "instructor.validation.validator_missing": "'{template_id}' à®µà®¾à®°à¯à®ªà¯à®ªà¯à®°à¯à®µà¯à®•à¯à®•à¯ validator à®‡à®²à¯à®²à¯ˆ.",
    "instructor.validation.course_metadata_field_empty": "Course_Metadata à®µà®°à®¿ {row}: Field à®•à®¾à®²à®¿à®¯à®¾à®• à®‡à®°à¯à®•à¯à®•à®•à¯à®•à¯‚à®Ÿà®¾à®¤à¯.",
    "instructor.validation.course_metadata_duplicate_field": "Course_Metadata à®µà®°à®¿ {row}: à®¨à®•à®²à¯ field '{field}'.",
    "instructor.validation.course_metadata_unknown_field": "Course_Metadata à®µà®°à®¿ {row}: à®…à®±à®¿à®¯à®ªà¯à®ªà®Ÿà®¾à®¤ field '{field}'.",
    "instructor.validation.course_metadata_value_required": "Course_Metadata à®µà®°à®¿ {row}: '{field}' à®•à¯à®•à¯ Value à®…à®µà®šà®¿à®¯à®®à¯.",
    "instructor.validation.course_metadata_missing_fields": "Course_Metadata à®‡à®²à¯ à®¤à¯‡à®µà¯ˆà®¯à®¾à®© fields à®‡à®²à¯à®²à¯ˆ: {fields}.",
    "instructor.validation.course_metadata_field_must_be_int": "Course_Metadata field '{field}' à®®à¯à®´à¯ à®Žà®£à¯à®£à®¾à®• à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.course_metadata_field_must_be_non_empty_str": "Course_Metadata field '{field}' à®•à®¾à®²à®¿à®¯à®²à¯à®²à®¾à®¤ à®‰à®°à¯ˆà®¯à®¾à®• à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.course_metadata_total_outcomes_invalid": "Course_Metadata field 'Total_Outcomes' 0-à® à®µà®¿à®Ÿ à®ªà¯†à®°à®¿à®¯ à®®à¯à®´à¯ à®Žà®£à¯à®£à®¾à®• à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.yes_no_required": "{sheet_name} à®µà®°à®¿ {row}: '{field}' à®Žà®©à¯à®ªà®¤à¯ YES à®…à®²à¯à®²à®¤à¯ NO à®†à®• à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.assessment_component_required_one": "Assessment_Config à®‡à®²à¯ à®•à¯à®±à¯ˆà®¨à¯à®¤à®¤à¯ à®’à®°à¯ component à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.assessment_component_required": "Assessment_Config à®µà®°à®¿ {row}: Component à®…à®µà®šà®¿à®¯à®®à¯.",
    "instructor.validation.assessment_component_duplicate": "Assessment_Config à®µà®°à®¿ {row}: à®¨à®•à®²à¯ component '{component}'.",
    "instructor.validation.assessment_weight_numeric": "Assessment_Config à®µà®°à®¿ {row}: Weight (%) à®Žà®£à¯ à®®à®¤à®¿à®ªà¯à®ªà®¾à®• à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.assessment_direct_missing": "Assessment_Config à®‡à®²à¯ à®•à¯à®±à¯ˆà®¨à¯à®¤à®¤à¯ à®’à®°à¯ direct component à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.assessment_indirect_missing": "Assessment_Config à®‡à®²à¯ à®•à¯à®±à¯ˆà®¨à¯à®¤à®¤à¯ à®’à®°à¯ indirect component à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.assessment_direct_total_invalid": "Assessment_Config direct component weights à®®à¯Šà®¤à¯à®¤à®®à¯ 100 à®†à®• à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯. à®•à®¿à®Ÿà¯ˆà®¤à¯à®¤à®¤à¯: {found}.",
    "instructor.validation.assessment_indirect_total_invalid": "Assessment_Config indirect component weights à®®à¯Šà®¤à¯à®¤à®®à¯ 100 à®†à®• à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯. à®•à®¿à®Ÿà¯ˆà®¤à¯à®¤à®¤à¯: {found}.",
    "instructor.validation.question_map_row_required_one": "Question_Map à®‡à®²à¯ à®•à¯à®±à¯ˆà®¨à¯à®¤à®¤à¯ à®’à®°à¯ à®•à¯‡à®³à¯à®µà®¿ à®µà®°à®¿ à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.question_component_required": "Question_Map à®µà®°à®¿ {row}: Component à®…à®µà®šà®¿à®¯à®®à¯.",
    "instructor.validation.question_component_unknown": "Question_Map à®µà®°à®¿ {row}: à®…à®±à®¿à®¯à®ªà¯à®ªà®Ÿà®¾à®¤ component '{component}'.",
    "instructor.validation.question_label_required": "Question_Map à®µà®°à®¿ {row}: Q_No/Rubric_Parameter à®…à®µà®šà®¿à®¯à®®à¯.",
    "instructor.validation.question_max_marks_numeric": "Question_Map à®µà®°à®¿ {row}: Max_Marks à®Žà®£à¯ à®®à®¤à®¿à®ªà¯à®ªà®¾à®• à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.question_max_marks_positive": "Question_Map à®µà®°à®¿ {row}: Max_Marks à®ªà¯‚à®œà¯à®¯à®¤à¯à®¤à¯ˆ à®µà®¿à®Ÿ à®ªà¯†à®°à®¿à®¯à®¤à®¾à®• à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.question_co_required": "Question_Map à®µà®°à®¿ {row}: CO à®‡à®²à¯ à®•à¯à®±à¯ˆà®¨à¯à®¤à®¤à¯ à®’à®°à¯ à®®à®¤à®¿à®ªà¯à®ªà¯ à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.question_co_no_repeat": "Question_Map à®µà®°à®¿ {row}: CO à®®à®¤à®¿à®ªà¯à®ªà¯à®•à®³à¯ à®®à¯€à®£à¯à®Ÿà¯à®®à¯ à®µà®°à®•à¯à®•à¯‚à®Ÿà®¾à®¤à¯.",
    "instructor.validation.question_co_out_of_range": "Question_Map à®µà®°à®¿ {row}: CO à®®à®¤à®¿à®ªà¯à®ªà¯ 1..{total_outcomes} à®µà®°à®®à¯à®ªà®¿à®±à¯à®•à¯ à®µà¯†à®³à®¿à®¯à¯‡ à®‰à®³à¯à®³à®¤à¯.",
    "instructor.validation.question_co_wise_requires_one": "Question_Map à®µà®°à®¿ {row}: '{component}' component-à®•à¯à®•à¯ à®’à®µà¯à®µà¯Šà®°à¯ à®•à¯‡à®³à¯à®µà®¿à®•à¯à®•à¯à®®à¯ à®¤à¯à®²à¯à®²à®¿à®¯à®®à®¾à®• à®’à®°à¯ CO à®®à®Ÿà¯à®Ÿà¯à®®à¯ à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.question_duplicate_for_component": "Question_Map à®µà®°à®¿ {row}: '{component}' component-à®•à¯à®•à¯ à®¨à®•à®²à¯ à®•à¯‡à®³à¯à®µà®¿ '{question}'.",
    "instructor.validation.students_row_required_one": "Students à®¤à®¾à®³à®¿à®²à¯ à®•à¯à®±à¯ˆà®¨à¯à®¤à®¤à¯ à®’à®°à¯ à®®à®¾à®£à®µà®°à¯ à®µà®°à®¿ à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.students_reg_and_name_required": "Students à®µà®°à®¿ {row}: Reg_No à®®à®±à¯à®±à¯à®®à¯ Student_Name à®‡à®°à®£à¯à®Ÿà¯à®®à¯ à®…à®µà®šà®¿à®¯à®®à¯.",
    "instructor.validation.students_duplicate_reg_no": "Students à®µà®°à®¿ {row}: à®¨à®•à®²à¯ Reg_No '{reg_no}'.",
    "instructor.validation.filled_marks_workbook_invalid": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®ªà®£à®¿à®ªà¯à®ªà¯à®¤à¯à®¤à®•à®®à¯ à®¤à®µà®±à®¾à®©à®¤à¯ à®…à®²à¯à®²à®¤à¯ à®‡à®¨à¯à®¤ à®•à®°à¯à®µà®¿ à®®à¯‚à®²à®®à¯ à®‰à®°à¯à®µà®¾à®•à¯à®•à®ªà¯à®ªà®Ÿà®µà®¿à®²à¯à®²à¯ˆ.",
    "instructor.validation.step3.layout_sheet_missing": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ workbook-à®‡à®²à¯ à®¤à¯‡à®µà¯ˆà®¯à®¾à®© layout à®¤à®¾à®³à¯ '{sheet}' à®‡à®²à¯à®²à¯ˆ.",
    "instructor.validation.step3.layout_header_mismatch": "Layout à®¤à®¾à®³à®¿à®©à¯ {column} header à®¤à®µà®±à®¾à®©à®¤à¯. à®Žà®¤à®¿à®°à¯à®ªà®¾à®°à¯à®ªà¯à®ªà¯ '{expected}'.",
    "instructor.validation.step3.layout_manifest_missing": "System layout à®¤à®¾à®³à®¿à®²à¯ layout manifest à®…à®²à¯à®²à®¤à¯ hash à®‡à®²à¯à®²à¯ˆ.",
    "instructor.validation.step3.layout_hash_mismatch": "Layout hash à®ªà¯Šà®°à¯à®¨à¯à®¤à®µà®¿à®²à¯à®²à¯ˆ. à®®à®¾à®±à¯à®±à®®à®¿à®²à¯à®²à®¾ à®‰à®°à¯à®µà®¾à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ marks template-à® à®ªà®¯à®©à¯à®ªà®Ÿà¯à®¤à¯à®¤à®µà¯à®®à¯.",
    "instructor.validation.step3.layout_manifest_json_invalid": "Layout manifest JSON à®¤à®µà®±à®¾à®© à®µà®Ÿà®¿à®µà®¤à¯à®¤à®¿à®²à¯ à®‰à®³à¯à®³à®¤à¯.",
    "instructor.validation.step3.template_validator_missing": "Template '{template_id}' à®•à¯à®•à®¾à®© Step 3 validator à®‡à®²à¯à®²à¯ˆ.",
    "instructor.validation.step3.manifest_root_invalid": "Layout manifest root à®’à®°à¯ object à®†à®• à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.step3.manifest_structure_invalid": "Layout manifest-à®‡à®²à¯ 'sheet_order' à®®à®±à¯à®±à¯à®®à¯ 'sheets' à®‡à®°à®£à¯à®Ÿà¯à®®à¯ à®‡à®°à¯à®•à¯à®• à®µà¯‡à®£à¯à®Ÿà¯à®®à¯.",
    "instructor.validation.step3.sheet_order_mismatch": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ marks à®¤à®¾à®³à¯à®•à®³à¯ à®ªà¯Šà®°à¯à®¨à¯à®¤à®µà®¿à®²à¯à®²à¯ˆ. à®Žà®¤à®¿à®°à¯à®ªà®¾à®°à¯à®ªà¯à®ªà¯: {expected}. à®•à®¿à®Ÿà¯ˆà®¤à¯à®¤à®¤à¯: {found}.",
    "instructor.validation.step3.manifest_sheet_spec_invalid": "Layout manifest-à®‡à®²à¯ à®¤à®µà®±à®¾à®© sheet specification à®‰à®³à¯à®³à®¤à¯.",
    "instructor.validation.step3.sheet_missing": "à®Žà®¤à®¿à®°à¯à®ªà®¾à®°à¯à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ '{sheet_name}' à®¤à®¾à®³à¯ workbook-à®‡à®²à¯ à®‡à®²à¯à®²à¯ˆ.",
    "instructor.validation.step3.header_row_invalid": "'{sheet_name}' à®¤à®¾à®³à®¿à®©à¯ header row metadata à®¤à®µà®±à®¾à®©à®¤à¯: {header_row}.",
    "instructor.validation.step3.headers_missing": "'{sheet_name}' à®¤à®¾à®³à¯à®•à¯à®•à®¾à®© à®Žà®¤à®¿à®°à¯à®ªà®¾à®°à¯à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ headers layout manifest-à®‡à®²à¯ à®‡à®²à¯à®²à¯ˆ.",
    "instructor.validation.step3.anchor_spec_invalid": "'{sheet_name}' à®¤à®¾à®³à¯à®•à¯à®•à®¾à®© anchor specification à®¤à®µà®±à®¾à®©à®¤à¯.",
    "instructor.validation.step3.formula_anchor_spec_invalid": "'{sheet_name}' à®¤à®¾à®³à¯à®•à¯à®•à®¾à®© formula anchor specification à®¤à®µà®±à®¾à®©à®¤à¯.",
    "instructor.validation.step3.header_row_mismatch": "'{sheet_name}' à®¤à®¾à®³à®¿à®©à¯ row {row} header à®ªà¯Šà®°à¯à®¨à¯à®¤à®µà®¿à®²à¯à®²à¯ˆ. à®Žà®¤à®¿à®°à¯à®ªà®¾à®°à¯à®ªà¯à®ªà¯: {expected}.",
    "instructor.validation.step3.anchor_value_mismatch": "'{sheet_name}' à®¤à®¾à®³à®¿à®©à¯ {cell} à®šà¯†à®²à¯à®²à®¿à®©à¯ à®®à®¤à®¿à®ªà¯à®ªà¯ à®®à®¾à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿà¯à®³à¯à®³à®¤à¯. à®Žà®¤à®¿à®°à¯à®ªà®¾à®°à¯à®ªà¯à®ªà¯ '{expected}', à®•à®¿à®Ÿà¯ˆà®¤à¯à®¤à®¤à¯ '{found}'.",
    "instructor.validation.step3.formula_mismatch": "'{sheet_name}' à®¤à®¾à®³à®¿à®©à¯ {cell} formula à®®à®¾à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿà¯à®³à¯à®³à®¤à¯.",
    "instructor.validation.step3.no_component_sheets": "à®¨à®¿à®°à®ªà¯à®ªà®ªà¯à®ªà®Ÿà¯à®Ÿ marks workbook-à®‡à®²à¯ component mark-entry à®¤à®¾à®³à¯à®•à®³à¯ à®‡à®²à¯à®²à¯ˆ.",
    "instructor.validation.step3.mark_entry_empty": "'{sheet_name}' à®¤à®¾à®³à®¿à®²à¯ {cell} à®‡à®²à¯ mark-entry à®•à®¾à®²à®¿à®¯à®¾à®• à®‰à®³à¯à®³à®¤à¯. à®ªà®¤à®¿à®µà¯‡à®±à¯à®±à¯à®®à¯ à®®à¯à®©à¯ à®…à®©à¯ˆà®¤à¯à®¤à¯ marks-à®à®¯à¯à®®à¯ à®¨à®¿à®°à®ªà¯à®ªà®µà¯à®®à¯.",
    "instructor.validation.step3.mark_value_invalid": "'{sheet_name}' à®¤à®¾à®³à®¿à®©à¯ {cell} à®šà¯†à®²à¯à®²à®¿à®²à¯ '{value}' à®¤à®µà®±à®¾à®© mark value à®‰à®³à¯à®³à®¤à¯. à®…à®©à¯à®®à®¤à®¿: A/a à®…à®²à¯à®²à®¤à¯ {minimum} à®®à¯à®¤à®²à¯ {maximum} à®µà®°à¯ˆà®¯à®¿à®²à®¾à®© à®Žà®£à¯.",
    "instructor.validation.step3.mark_precision_invalid": "'{sheet_name}' à®¤à®¾à®³à®¿à®©à¯ {cell} à®šà¯†à®²à¯à®²à®¿à®²à¯ '{value}' à®…à®¤à®¿à®• à®¤à®šà®® à®‡à®²à®•à¯à®•à®™à¯à®•à®³à¯ à®‰à®³à¯à®³à®©. à®…à®¤à®¿à®•à®ªà®Ÿà¯à®šà®®à¯ {decimals} à®®à®Ÿà¯à®Ÿà¯à®®à¯ à®…à®©à¯à®®à®¤à®¿.",
    "instructor.validation.step3.indirect_mark_must_be_integer": "'{sheet_name}' à®¤à®¾à®³à®¿à®©à¯ {cell} à®šà¯†à®²à¯à®²à®¿à®²à¯ '{value}' à®¤à®µà®±à®¾à®© indirect mark. à®®à¯à®´à¯ à®Žà®£à¯ Likert à®®à®¤à®¿à®ªà¯à®ªà¯ˆ à®®à®Ÿà¯à®Ÿà¯à®®à¯‡ à®ªà®¯à®©à¯à®ªà®Ÿà¯à®¤à¯à®¤à®µà¯à®®à¯.",
    "instructor.validation.step3.absence_policy_violation": "'{sheet_name}' à®¤à®¾à®³à®¿à®©à¯ à®µà®°à®¿ {row} à®‡à®²à¯ {range} à®ªà®•à¯à®¤à®¿à®¯à®¿à®²à¯ absence à®®à®±à¯à®±à¯à®®à¯ à®Žà®£à¯ à®®à®¤à®¿à®ªà¯à®ªà¯à®•à®³à¯ à®•à®²à®¨à¯à®¤à¯à®³à¯à®³à®¤à¯. à®®à¯à®´à¯à®µà®¤à¯à®®à¯ A/a à®…à®²à¯à®²à®¤à¯ à®®à¯à®´à¯à®µà®¤à¯à®®à¯ à®Žà®£à¯ à®®à®¤à®¿à®ªà¯à®ªà¯à®•à®³à¯ à®®à®Ÿà¯à®Ÿà¯à®®à¯‡ à®‰à®³à¯à®³à®¿à®Ÿà®µà¯à®®à¯.",
    "instructor.validation.step3.total_formula_mismatch": "'{sheet_name}' à®¤à®¾à®³à®¿à®©à¯ {cell} à®‡à®²à¯ total formula à®®à®¾à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿà¯à®³à¯à®³à®¤à¯.",
    "instructor.validation.step3.co_formula_mismatch": "'{sheet_name}' à®¤à®¾à®³à®¿à®©à¯ {cell} à®‡à®²à¯ CO split formula à®®à®¾à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿà¯à®³à¯à®³à®¤à¯.",
    "instructor.validation.step3.structure_snapshot_missing": "'{sheet_name}' à®¤à®¾à®³à¯à®•à¯à®•à®¾à®© mark-structure metadata layout manifest-à®‡à®²à¯ à®‡à®²à¯à®²à¯ˆ.",
    "instructor.validation.step3.structure_snapshot_mismatch": "'{sheet_name}' à®¤à®¾à®³à®¿à®©à¯ mark-structure {cell} à®šà¯†à®²à¯à®²à®¿à®©à¯ à®®à®¤à®¿à®ªà¯à®ªà¯ à®®à®¾à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿà¯à®³à¯à®³à®¤à¯.",
    "instructor.validation.step3.student_identity_spec_invalid": "'{sheet_name}' à®¤à®¾à®³à¯à®•à¯à®•à®¾à®© student identity metadata layout manifest-à®‡à®²à¯ à®¤à®µà®±à®¾à®• à®‰à®³à¯à®³à®¤à¯.",
    "instructor.validation.step3.student_identity_mismatch": "'{sheet_name}' à®¤à®¾à®³à®¿à®²à¯ à®®à®¾à®£à®µà®°à¯ Reg. No./Name à®µà®°à®¿à®šà¯ˆà®•à®³à¯ à®®à®¾à®±à¯à®±à®ªà¯à®ªà®Ÿà¯à®Ÿà¯à®³à¯à®³à®©.",
    "instructor.validation.step3.student_reg_duplicate": "'{sheet_name}' à®¤à®¾à®³à®¿à®²à¯ à®®à®¾à®£à®µà®°à¯ Reg. No. '{reg_no}' à®¨à®•à®²à®¾à®• à®‰à®³à¯à®³à®¤à¯.",
    "instructor.validation.step3.student_identity_cross_sheet_mismatch": "'{sheet_name}' à®¤à®¾à®³à®¿à®©à¯ à®®à®¾à®£à®µà®°à¯ Reg. No./Name à®µà®°à®¿à®šà¯ˆà®•à®³à¯ '{reference_sheet}' à®¤à®¾à®³à¯à®Ÿà®©à¯ à®ªà¯Šà®°à¯à®¨à¯à®¤à®µà®¿à®²à¯à®²à¯ˆ.",
    # Instructor template headers / labels
    "instructor.template.headers.course_metadata.field": "à®ªà¯à®²à®®à¯",
    "instructor.template.headers.course_metadata.value": "à®®à®¤à®¿à®ªà¯à®ªà¯",
    "instructor.template.headers.assessment.component": "à®•à¯‚à®±à¯",
    "instructor.template.headers.assessment.weight": "à®Žà®Ÿà¯ˆ (%)",
    "instructor.template.headers.assessment.cia": "CIA",
    "instructor.template.headers.assessment.co_wise_breakup": "CO_Wise_Marks_Breakup",
    "instructor.template.headers.assessment.direct": "à®¨à¯‡à®°à®Ÿà®¿",
    "instructor.template.headers.question_map.component": "à®•à¯‚à®±à¯",
    "instructor.template.headers.question_map.question": "Q_No/à®®à®¤à®¿à®ªà¯à®ªà¯€à®Ÿà¯à®Ÿà¯_à®…à®³à®µà¯à®•à¯‹à®²à¯",
    "instructor.template.headers.question_map.max_marks": "à®…à®¤à®¿à®•à®ªà®Ÿà¯à®š_à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯",
    "instructor.template.headers.question_map.co": "CO",
    "instructor.template.headers.students.reg_no": "à®ªà®¤à®¿à®µà¯_à®Žà®£à¯",
    "instructor.template.headers.students.student_name": "à®®à®¾à®£à®µà®°à¯_à®ªà¯†à®¯à®°à¯",
    "instructor.template.validation.direct_title": "à®¨à¯‡à®°à®Ÿà®¿",
    "instructor.template.validation.select_yes_no": "YES à®…à®²à¯à®²à®¤à¯ NO à®¤à¯‡à®°à¯à®µà¯ à®šà¯†à®¯à¯à®¯à®µà¯à®®à¯",
    "instructor.marks.validation.error_title": "à®¤à®µà®±à®¾à®© à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯",
    "instructor.marks.validation.error_message": "A/a à®…à®²à¯à®²à®¤à¯ à®…à®©à¯à®®à®¤à®¿à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®µà®°à®®à¯à®ªà®¿à®±à¯à®•à¯à®³à¯ à®Žà®£à¯ à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯ à®‰à®³à¯à®³à®¿à®Ÿà®µà¯à®®à¯.",
    "instructor.marks.validation.indirect_error_message": "A/a à®…à®²à¯à®²à®¤à¯ à®…à®©à¯à®®à®¤à®¿à®•à¯à®•à®ªà¯à®ªà®Ÿà¯à®Ÿ à®µà®°à®®à¯à®ªà®¿à®±à¯à®•à¯à®³à¯ à®Žà®£à¯ Likert à®®à®¤à®¿à®ªà¯à®ªà¯ à®‰à®³à¯à®³à®¿à®Ÿà®µà¯à®®à¯.",
    "instructor.marks.row_header.serial_no": "#",
    "instructor.marks.row_header.reg_no": "à®ªà®¤à®¿à®µà¯ à®Žà®£à¯",
    "instructor.marks.row_header.student_name": "à®®à®¾à®£à®µà®°à¯ à®ªà¯†à®¯à®°à¯",
    "instructor.marks.total_label": "à®®à¯Šà®¤à¯à®¤à®®à¯",
    "instructor.marks.co_prefix": "CO",
    "instructor.marks.question_prefix": "Q",
    "instructor.marks.co_marks_label_prefix": "CO à®•à¯à®•à®¾à®© à®®à®¤à®¿à®ªà¯à®ªà¯†à®£à¯",
    "instructor.marks.cos_label": "COà®•à¯à®•à®³à¯",
    "instructor.status.step5_selected": "à®‡à®±à¯à®¤à®¿ CO à®…à®±à®¿à®•à¯à®•à¯ˆ à®ªà®¾à®¤à¯ˆ à®¤à¯‡à®°à¯à®µà¯ à®šà¯†à®¯à¯à®¯à®ªà¯à®ªà®Ÿà¯à®Ÿà®¤à¯.",
    # Coordinator module
    "coordinator.title": "Coordinator File Collector",
    "coordinator.drop_hint": "Drag and drop Excel files here to collect them for coordinator workflow.",
    "coordinator.empty": "No Excel files added yet.",
    "coordinator.remove_selected": "Remove Selected",
    "coordinator.clear_all": "Clear All",
    "coordinator.status.added": "{added} file(s) added. Total: {total}.",
    "coordinator.duplicate.title": "File Already Exists",
    "coordinator.duplicate.body": "{count} duplicate file(s) were skipped because they already exist in the list.",
    "coordinator.invalid_register.title": "Missing Register Header",
    "coordinator.invalid_register.body": (
        "File must contain Register Number.\n\n{files}"
    ),
    "coordinator.status.ignored": (
        "{count} file(s) were ignored (unsupported type, missing, duplicate, "
        "or missing register header)."
    ),
    "coordinator.status.removed": "{count} file(s) removed.",
    "coordinator.status.cleared": "{count} file(s) cleared.",
}

