"""Tamil (India) text catalog for user-facing strings."""

TEXTS = {
    # Startup / main
    "app.already_running": "பயன்பாடு ஏற்கனவே இயங்கிக்கொண்டிருக்கிறது.",
    "app.unexpected_error": "எதிர்பாராத பிழை ஏற்பட்டது. பதிவு கோப்பை சரிபார்க்கவும்.",
    "app.startup.workbook_secret_missing_frozen": "பணிப்புத்தகம் ரகசியம் கிடைக்கவில்லை. மென்பொருளை மீண்டும் நிறுவவும் அல்லது ஆதரவைக் தொடர்புகொள்ளவும்.",
    "app.startup.workbook_secret_missing_dev": "பணிப்புத்தகம் ரகசிய சேமிப்பகத்தை உள்ளூரில் நீக்கி பயன்பாட்டை மீண்டும் தொடங்கவும்.",
    "app.main_window_title": "FOCUS",
    "splash.starting": "பயன்பாடு தொடங்குகிறது...",
    "splash.loading_main_window": "முதன்மை சாளரம் ஏற்றப்படுகிறது...",
    # Main window
    "toolbar.navigation": "வழிசெலுத்தல்",
    "status.ready": "தயார்",
    "module.placeholder": "{title} தொகுதி இன்னும் செயல்படுத்தப்படவில்லை.",
    "module.instructor": "பயிற்றுநர்",
    "module.coordinator_short": "ஒருங்கிணைப்பாளர்",
    "module.po_analysis": "PO பகுப்பாய்வு",
    "module.load_failed_title": "தொகுதி ஏற்றப் பிழை",
    "module.load_failed_body": "'{module}' தொகுதியை ஏற்ற முடியவில்லை.\n\nவிவரம்: {error}",
    "module.load_failed_status": "தொகுதியை ஏற்ற முடியவில்லை: {module}.",
    "nav.help": "உதவி",
    "nav.about": "பற்றி",
    # Settings module
    "language.switcher.button": "மொழி: {language}",
    "language.switcher.applied_status": "மொழி {language} ஆக அமைக்கப்பட்டது.",
    # About
    "about.version": "பதிப்பு {version}",
    "about.subtitle": "விளைவு கணக்கீடு மற்றும் ஒருங்கிணைப்பு அமைப்புக்கான கட்டமைப்பு",
    "about.description": (
        "{app_name} என்பது Course Outcome (CO) அடைவை கணக்கிடவும், "
        "நேரடி மற்றும் மறைமுக மதிப்பீடுகளை அடிப்படையாகக் கொண்டு "
        "கட்டமைக்கப்பட்ட முடிவு பகுப்பாய்வை செய்யவும் வடிவமைக்கப்பட்ட மென்பொருள் கருவி."
    ),
    "about.institution": "கலசலிங்கம் ஆராய்ச்சி மற்றும் கல்வி கழகம் (KARE) இல் உருவாக்கப்பட்டது.",
    "about.copyright": "(c) {year} KARE. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    # Help module
    "help.doc_missing_title": "உதவி ஆவணம் இல்லை",
    "help.doc_missing_body": "உதவி PDF கிடைக்கவில்லை:\\n{path}",
    "help.doc_error_title": "உதவி ஆவணப் பிழை",
    "help.doc_error_body": "உதவி PDF ஐ ஏற்ற முடியவில்லை.",
    "help.download_pdf": "PDF பதிவிறக்கு",
    "help.open_default_viewer": "இயல்புநிலை பார்வியில் திற",
    "help.missing_file_title": "கோப்பு இல்லை",
    "help.save_title": "CO அடைவு ஆவணத்தை சேமி",
    "help.save_default_name": "CO_Calculation_Document.pdf",
    "help.save_filter_pdf": "PDF கோப்புகள் (*.pdf)",
    "help.save_failed_title": "சேமித்தல் தோல்வி",
    "help.save_success_title": "சேமிக்கப்பட்டது",
    "help.open_failed_title": "திறத்தல் தோல்வி",
    "help.open_failed_body": "இயல்புநிலை பார்வியில் உதவி PDF ஐ திறக்க முடியவில்லை.",
    "help.open_success_title": "திறக்கப்பட்டது",
    "help.open_success_body": "உதவி PDF இயல்புநிலை பார்வியில் திறக்கப்பட்டது.",
    "help.status.doc_loaded": "உதவி ஆவணம் ஏற்றப்பட்டது.",
    "help.status.doc_missing": "உதவி ஆவணம் இல்லை.",
    "help.status.doc_error": "உதவி ஆவணத்தை ஏற்ற முடியவில்லை.",
    "help.status.file_missing": "உதவி PDF கிடைக்கவில்லை.",
    "help.status.save_success": "உதவி PDF வெற்றிகரமாக சேமிக்கப்பட்டது.",
    "help.status.save_failed": "உதவி PDF சேமிக்கும் போது பிழை ஏற்பட்டது.",
    "help.status.open_success": "உதவி PDF இயல்புநிலை பார்வியில் திறக்கப்பட்டது.",
    "help.status.open_failed": "உதவி PDF திறக்கும் போது பிழை ஏற்பட்டது.",
    # Instructor module
    "instructor.workflow_title": "CO பணிச்சுற்று",
    "instructor.step1.title": "மதிப்பெண் வார்ப்புருவை உருவாக்கு",
    "instructor.step2.title": "CO மதிப்பெண் அறிக்கையை உருவாக்கு",
    "instructor.step1.desc": "சரிபார்க்கப்பட்ட பாட விவர கோப்பை பதிவேற்றி, மதிப்பெண் வார்ப்புருவை தயாரித்து சேமிக்கவும்.",
    "instructor.step2.desc": "நிரப்பப்பட்ட மதிப்பெண் பணிப்புத்தகத்தை சரிபார்த்து பதிவேற்றி, இறுதி CO அறிக்கையை உருவாக்கவும்.",
    "instructor.links.title": "உருவாக்கப்பட்ட வெளியீடுகள்",
    "instructor.links.course_details_generated": "உருவாக்கப்பட்ட பாட விவர வார்ப்புரு",
    "instructor.links.course_details_uploaded": "பதிவேற்றப்பட்ட பாட விவர கோப்பு",
    "instructor.links.marks_template_generated": "உருவாக்கப்பட்ட மதிப்பெண் வார்ப்புரு",
    "instructor.links.marks_template_uploaded": "பதிவேற்றப்பட்ட மதிப்பெண் வார்ப்புரு",
    "instructor.links.final_co_report_generated": "உருவாக்கப்பட்ட இறுதி CO அறிக்கை",
    "instructor.links.open_file": "கோப்பை திற",
    "instructor.links.open_folder": "கோப்புறையை திற",
    "instructor.links.not_available": "இன்னும் கிடைக்கவில்லை",
    "instructor.links.open_failed": "தேர்ந்தெடுக்கப்பட்ட பாதையை திறக்க முடியவில்லை.",
    "instructor.note.default": "முடித்த எந்த படியையும் மீண்டும் திறந்து மாற்றலாம்.",
    "instructor.note.outdated_current": "இந்த படி காலாவதியானது. இந்த படியை மீண்டும் இயக்கவும்.",
    "instructor.note.outdated_downstream": "மேல்நிலை மாற்றம் செய்யப்பட்டுள்ளது. அடுத்த படிகளை மீண்டும் உருவாக்க வேண்டி இருக்கலாம்.",
    "instructor.action.step1.default": "வார்ப்புருவை பதிவிறக்கு",
    "instructor.action.step1.upload": "பாட விவரங்களை பதிவேற்று",
    "instructor.action.step1.prepare": "மதிப்பெண் வார்ப்புருவை தயாரி",
    "instructor.action.step2.upload.default": "நிரப்பப்பட்ட மதிப்பெண்களை பதிவேற்று",
    "instructor.action.step2.generate.default": "இறுதி CO அறிக்கையை உருவாக்கு",
    "instructor.require.step2": "முதலில் படி 1 ஐ முடிக்கவும்.",
    "instructor.require.step1": "முதலில் படி 1 ஐ முடிக்கவும்.",
    "instructor.msg.success_title": "வெற்றி",
    "instructor.msg.validation_title": "சரிபார்ப்பு பிழை",
    "instructor.msg.error_title": "தோல்வி",
    "instructor.msg.step_completed": "படி {step} முடிந்தது: {title}.",
    "instructor.msg.failed_to_do": "{action} செய்ய முடியவில்லை.",
    "instructor.msg.step_required_title": "படி தேவை",
    "instructor.dialog.filter.excel": "Excel கோப்புகள் (*.xlsx)",
    "instructor.dialog.filter.excel_open": "Excel கோப்புகள் (*.xlsx *.xlsm *.xls)",
    "instructor.dialog.step1.title": "பாட விவர வார்ப்புருவை சேமிக்க",
    "instructor.dialog.step1.default_name": "course_details_template.xlsx",
    "instructor.dialog.step2.title": "பாட விவர கோப்பை தேர்வு செய்ய",
    "instructor.dialog.step1.prepare.title": "மதிப்பெண் வார்ப்புருவை சேமிக்க",
    "instructor.dialog.step1.prepare.default_name": "marks_template.xlsx",
    "instructor.dialog.step2.upload.title": "நிரப்பப்பட்ட மதிப்பெண் கோப்பை தேர்வு செய்ய",
    "instructor.dialog.step2.generate.title": "இறுதி CO அறிக்கையை சேமிக்க",
    "instructor.status.step1_selected": "வார்ப்புரு பதிவிறக்கப் பாதை தேர்வு செய்யப்பட்டது.",
    "instructor.status.step1_validated": "பாட விவரங்கள் பதிவேற்றப்பட்டு சரிபார்க்கப்பட்டன. இப்போது மதிப்பெண் வார்ப்புருவை தயாரிக்கலாம்.",
    "instructor.status.step1_prepared": "மதிப்பெண் வார்ப்புரு உருவாக்கப்பட்டது.",
    "instructor.status.step1_changed": "பாட விவரங்கள் மாற்றப்பட்டன. அடுத்த படிகளை மீண்டும் செய்யவும்.",
    "instructor.status.step2_uploaded_filled": "நிரப்பப்பட்ட மதிப்பெண்கள் பதிவேற்றப்பட்டன.",
    "instructor.status.step2_changed_filled": "நிரப்பப்பட்ட மதிப்பெண்கள் மாற்றப்பட்டன. இறுதி அறிக்கையை மீண்டும் உருவாக்கவும்.",
    "instructor.status.step2_generated": "இறுதி CO அறிக்கைப் பாதை தேர்வு செய்யப்பட்டது.",
    "instructor.status.operation_cancelled": "செயல் ரத்து செய்யப்பட்டது.",
    "instructor.status.step1_drop_browse_requested": "இழுத்து-விடும் விட்ஜெட்டில் பாட விவர கோப்பு தேர்வு கோரப்பட்டது.",
    "instructor.status.step1_drop_files_dropped": "பாட விவர விட்ஜெட்டில் {count} கோப்பு(கள்) விடப்பட்டது.",
    "instructor.status.step1_drop_files_changed": "பாட விவர விட்ஜெட்டில் இப்போது {count} கோப்பு(கள்) உள்ளன.",
    "instructor.status.step1_drop_files_rejected": "பாட விவர விட்ஜெட்டில் விடப்பட்ட {count} கோப்பு(கள்) நிராகரிக்கப்பட்டன.",
    "instructor.status.step2_drop_browse_requested": "Filled marks browse requested from drag-and-drop widget.",
    "instructor.status.step2_drop_files_dropped": "{count} file(s) dropped into filled marks widget.",
    "instructor.status.step2_drop_files_changed": "Filled marks widget now has {count} file(s).",
    "instructor.status.step2_drop_files_rejected": "{count} dropped file(s) were rejected by filled marks widget.",
    "instructor.status.step1_validating_progress": "Validating course template files: {processed}/{total}.",
    "instructor.status.step1_validated_progress": "Validated valid files: {valid}/{total}.",
    "instructor.status.step1_prepare_progress": "Processed marks templates: {processed}/{total}.",
    "instructor.step1.drop.summary": "கோப்புகள்: {count}",
    "instructor.toast.step1_validation_summary": "Validation complete: {valid} valid, {invalid} invalid, {mismatched} wrong template, {duplicates} duplicate input.",
    "instructor.toast.step1_prepare_no_outputs": "No output files selected for marks template generation.",
    "instructor.toast.step1_prepare_summary": "Marks template generation complete: processed {processed}/{total}, generated {generated}, failed {failed}, skipped {skipped}.",
    "instructor.log.title": "செயல் பதிவு",
    "instructor.log.ready": "செயல் பதிவு தொடங்கப்பட்டது.",
    "instructor.log.completed_process": "{process} வெற்றிகரமாக முடிந்தது.",
    "instructor.log.error_while_process": "{process} செய்யும் போது பிழை ஏற்பட்டது.",
    "instructor.log.process.generate_course_details_template": "பாட விவர வார்ப்புருவை உருவாக்குதல்",
    "instructor.log.process.validate_course_details_workbook": "பதிவேற்றப்பட்ட பாட விவர பணிப்புத்தகம்-ஐ சரிபார்த்தல்",
    "instructor.log.process.generate_marks_template": "மதிப்பெண் வார்ப்புருவை உருவாக்குதல்",
    "instructor.log.process.upload_filled_marks_workbook": "நிரப்பப்பட்ட மதிப்பெண் பணிப்புத்தகம்-ஐ பதிவேற்றுதல்",
    "instructor.log.process.generate_final_co_report": "இறுதி CO அறிக்கையை உருவாக்குதல்",
    "instructor.validation.xlsxwriter_missing": "xlsxwriter நிறுவப்படவில்லை. பாட வார்ப்புருக்களை உருவாக்க அதை நிறுவவும்.",
    "instructor.validation.sheet_single_header_row": "'{sheet_name}' தாளில் துல்லியமாக ஒரு தலைப்பு வரி மட்டுமே இருக்க வேண்டும்.",
    "instructor.system.template_generate_failed": "'{output}' இடத்தில் பாட விவர வார்ப்புருவை உருவாக்க முடியவில்லை.",
    "instructor.validation.unknown_template": "அறியப்படாத பணிப்புத்தகம் வார்ப்புரு '{template_id}'. கிடைக்கும் வார்ப்புருக்கள்: {available}.",
    "instructor.validation.invalid_sheet_name": "தவறான தாள் பெயர்.",
    "instructor.validation.headers_empty": "'{sheet_name}' தாளுக்கான தலைப்புகள் காலியாக இருக்கக்கூடாது.",
    "instructor.validation.headers_unique": "'{sheet_name}' தாளில் தலைப்புகள் தனித்துவமாக இருக்க வேண்டும்.",
    "instructor.validation.row_length_mismatch": "'{sheet_name}' தாளில் வரி {row} நீளம் பொருந்தவில்லை: எதிர்பார்ப்பு {expected}, கிடைத்தது {found}.",
    "instructor.validation.openpyxl_missing": "openpyxl நிறுவப்படவில்லை. பதிவேற்றப்பட்ட பாட விவரங்களை சரிபார்க்க அதை நிறுவவும்.",
    "instructor.validation.workbook_not_found": "பாட விவர பணிப்புத்தகம் கிடைக்கவில்லை: {workbook}",
    "instructor.validation.workbook_open_failed": "பாட விவர பணிப்புத்தகம் '{workbook}' ஐ திறக்க முடியவில்லை.",
    "instructor.validation.system_sheet_missing": "பதிவேற்றப்பட்ட பணிப்புத்தகம் இல் தேவையான கணினி தாள் '{sheet}' இல்லை.",
    "instructor.validation.system_hash_missing_template_id_header": "தவறான கணினி ஹாஷ் தாள் வடிவம்: Template_ID தலைப்பு இல்லை.",
    "instructor.validation.system_hash_missing_template_hash_header": "தவறான கணினி ஹாஷ் தாள் வடிவம்: Template_Hash தலைப்பு இல்லை.",
    "instructor.validation.system_hash_template_id_missing": "கணினி ஹாஷ் தாளில் Template_ID இல்லை.",
    "instructor.validation.system_hash_mismatch": "வார்ப்புரு ஹாஷ் பொருந்தவில்லை. சரியான உருவாக்கப்பட்ட வார்ப்புருவைப் பயன்படுத்தவும்.",
    "instructor.validation.workbook_sheet_mismatch": "பணிப்புத்தகம் தாள்கள் '{template_id}' வார்ப்புருவுடன் பொருந்தவில்லை. எதிர்பார்ப்பு: {expected}. கிடைத்தது: {found}.",
    "instructor.validation.header_mismatch": "'{sheet_name}' தாளில் தலைப்பு பொருந்தவில்லை. எதிர்பார்ப்பு: {expected}.",
    "instructor.validation.unexpected_header": "'{sheet_name}' தாளின் நெடுவரிசை {col} இல் எதிர்பாராத தலைப்பு.",
    "instructor.validation.validator_missing": "'{template_id}' வார்ப்புருவுக்கு சரிபார்ப்பி இல்லை.",
    "instructor.validation.course_metadata_field_empty": "Course_Metadata வரி {row}: புலம் காலியாக இருக்கக்கூடாது.",
    "instructor.validation.course_metadata_duplicate_field": "Course_Metadata வரி {row}: '{field}' என்ற புலம் நகலாக உள்ளது.",
    "instructor.validation.course_metadata_unknown_field": "Course_Metadata வரி {row}: அறியப்படாத புலம் '{field}'.",
    "instructor.validation.course_metadata_value_required": "Course_Metadata வரி {row}: '{field}' க்கான Value அவசியம்.",
    "instructor.validation.course_metadata_missing_fields": "Course_Metadata இல் தேவையான புலங்கள் இல்லை: {fields}.",
    "instructor.validation.course_metadata_field_must_be_int": "Course_Metadata புலம் '{field}' முழு எண்ணாக இருக்க வேண்டும்.",
    "instructor.validation.course_metadata_field_must_be_non_empty_str": "Course_Metadata புலம் '{field}' காலியல்லாத உரையாக இருக்க வேண்டும்.",
    "instructor.validation.course_metadata_total_outcomes_invalid": "Course_Metadata புலம் 'Total_Outcomes' 0-ஐ விட பெரிய முழு எண்ணாக இருக்க வேண்டும்.",
    "instructor.validation.yes_no_required": "{sheet_name} வரி {row}: '{field}' என்பது YES அல்லது NO ஆக இருக்க வேண்டும்.",
    "instructor.validation.assessment_component_required_one": "Assessment_Config இல் குறைந்தது ஒரு கூறு இருக்க வேண்டும்.",
    "instructor.validation.assessment_component_required": "Assessment_Config வரி {row}: கூறு அவசியம்.",
    "instructor.validation.assessment_component_duplicate": "Assessment_Config வரி {row}: நகல் கூறு '{component}'.",
    "instructor.validation.assessment_weight_numeric": "Assessment_Config வரி {row}: Weight (%) எண் மதிப்பாக இருக்க வேண்டும்.",
    "instructor.validation.assessment_direct_missing": "Assessment_Config இல் குறைந்தது ஒரு நேரடி கூறு இருக்க வேண்டும்.",
    "instructor.validation.assessment_indirect_missing": "Assessment_Config இல் குறைந்தது ஒரு மறைமுக கூறு இருக்க வேண்டும்.",
    "instructor.validation.assessment_direct_total_invalid": "Assessment_Config நேரடி கூறு weights மொத்தம் 100 ஆக இருக்க வேண்டும். கிடைத்தது: {found}.",
    "instructor.validation.assessment_indirect_total_invalid": "Assessment_Config இன் மறைமுக கூறு எடைகள் மொத்தம் 100 ஆக இருக்க வேண்டும். கிடைத்தது: {found}.",
    "instructor.validation.question_map_row_required_one": "Question_Map இல் குறைந்தது ஒரு கேள்வி வரி இருக்க வேண்டும்.",
    "instructor.validation.question_component_required": "Question_Map வரி {row}: கூறு அவசியம்.",
    "instructor.validation.question_component_unknown": "Question_Map வரி {row}: அறியப்படாத கூறு '{component}'.",
    "instructor.validation.question_label_required": "Question_Map வரி {row}: Q_No/Rubric_Parameter அவசியம்.",
    "instructor.validation.question_max_marks_numeric": "Question_Map வரி {row}: Max_Marks எண் மதிப்பாக இருக்க வேண்டும்.",
    "instructor.validation.question_max_marks_positive": "Question_Map வரி {row}: Max_Marks பூஜ்யத்தை விட பெரியதாக இருக்க வேண்டும்.",
    "instructor.validation.question_co_required": "Question_Map வரி {row}: CO இல் குறைந்தது ஒரு மதிப்பு இருக்க வேண்டும்.",
    "instructor.validation.question_co_no_repeat": "Question_Map வரி {row}: CO மதிப்புகள் மீண்டும் வரக்கூடாது.",
    "instructor.validation.question_co_out_of_range": "Question_Map வரி {row}: CO மதிப்பு 1..{total_outcomes} வரம்பிற்கு வெளியே உள்ளது.",
    "instructor.validation.question_co_wise_requires_one": "Question_Map வரி {row}: '{component}' கூறு-க்கு ஒவ்வொரு கேள்விக்கும் துல்லியமாக ஒரு CO மட்டும் இருக்க வேண்டும்.",
    "instructor.validation.question_duplicate_for_component": "Question_Map வரி {row}: '{component}' கூறு-க்கு '{question}' என்ற கேள்வி நகலாக உள்ளது.",
    "instructor.validation.students_row_required_one": "Students தாளில் குறைந்தது ஒரு மாணவர் வரி இருக்க வேண்டும்.",
    "instructor.validation.students_reg_and_name_required": "Students வரி {row}: Reg_No மற்றும் Student_Name இரண்டும் அவசியம்.",
    "instructor.validation.students_duplicate_reg_no": "Students வரி {row}: நகல் Reg_No '{reg_no}'.",
    "instructor.validation.step2.layout_sheet_missing": "நிரப்பப்பட்ட மதிப்பெண் பணிப்புத்தகம்-இல் தேவையான அமைப்பு தாள் '{sheet}' இல்லை.",
    "instructor.validation.step2.layout_header_mismatch": "Layout தாளின் {column} தலைப்பு தவறானது. எதிர்பார்ப்பு '{expected}'.",
    "instructor.validation.step2.layout_manifest_missing": "System அமைப்பு தாளில் அமைப்பு விவரப்பட்டியல் அல்லது ஹாஷ் இல்லை.",
    "instructor.validation.step2.layout_hash_mismatch": "Layout ஹாஷ் பொருந்தவில்லை. மாற்றமில்லா உருவாக்கப்பட்ட மதிப்பெண்கள் வார்ப்புரு-ஐ பயன்படுத்தவும்.",
    "instructor.validation.step2.layout_manifest_json_invalid": "அமைப்பு விவரப்பட்டியல் JSON தவறான வடிவத்தில் உள்ளது.",
    "instructor.validation.step2.template_validator_missing": "வார்ப்புரு '{template_id}' க்கான Step 2 சரிபார்ப்பி இல்லை.",
    "instructor.validation.step2.manifest_root_invalid": "அமைப்பு விவரப்பட்டியல் root ஒரு object ஆக இருக்க வேண்டும்.",
    "instructor.validation.step2.manifest_structure_invalid": "அமைப்பு விவரப்பட்டியல்-இல் 'sheet_order' மற்றும் 'sheets' இரண்டும் இருக்க வேண்டும்.",
    "instructor.validation.step2.sheet_order_mismatch": "நிரப்பப்பட்ட மதிப்பெண்கள் தாள்கள் பொருந்தவில்லை. எதிர்பார்ப்பு: {expected}. கிடைத்தது: {found}.",
    "instructor.validation.step2.manifest_sheet_spec_invalid": "அமைப்பு விவரப்பட்டியல்-இல் தவறான sheet specification உள்ளது.",
    "instructor.validation.step2.sheet_missing": "எதிர்பார்க்கப்பட்ட '{sheet_name}' தாள் பணிப்புத்தகம்-இல் இல்லை.",
    "instructor.validation.step2.header_row_invalid": "'{sheet_name}' தாளின் தலைப்பு row metadata தவறானது: {header_row}.",
    "instructor.validation.step2.headers_missing": "'{sheet_name}' தாளுக்கான எதிர்பார்க்கப்பட்ட தலைப்புகள் அமைப்பு விவரப்பட்டியல்-இல் இல்லை.",
    "instructor.validation.step2.anchor_spec_invalid": "'{sheet_name}' தாளுக்கான anchor specification தவறானது.",
    "instructor.validation.step2.formula_anchor_spec_invalid": "'{sheet_name}' தாளுக்கான formula anchor specification தவறானது.",
    "instructor.validation.step2.header_row_mismatch": "'{sheet_name}' தாளின் row {row} தலைப்பு பொருந்தவில்லை. எதிர்பார்ப்பு: {expected}.",
    "instructor.validation.step2.anchor_value_mismatch": "'{sheet_name}' தாளின் {cell} செல்லின் மதிப்பு மாற்றப்பட்டுள்ளது. எதிர்பார்ப்பு '{expected}', கிடைத்தது '{found}'.",
    "instructor.validation.step2.formula_mismatch": "'{sheet_name}' தாளின் {cell} formula மாற்றப்பட்டுள்ளது.",
    "instructor.validation.step2.no_component_sheets": "நிரப்பப்பட்ட மதிப்பெண்கள் பணிப்புத்தகம்-இல் கூறு mark-entry தாள்கள் இல்லை.",
    "instructor.validation.step2.mark_entry_empty": "'{sheet_name}' தாளில் {cell} இல் mark-entry காலியாக உள்ளது. பதிவேற்றும் முன் அனைத்து மதிப்பெண்கள்-ஐயும் நிரப்பவும்.",
    "instructor.validation.step2.mark_value_invalid": "'{sheet_name}' தாளின் {cell} செல்லில் '{value}' தவறான mark value உள்ளது. அனுமதி: A/a அல்லது {minimum} முதல் {maximum} வரையிலான எண்.",
    "instructor.validation.step2.mark_precision_invalid": "'{sheet_name}' தாளின் {cell} செல்லில் '{value}' அதிக தசம இலக்கங்கள் உள்ளன. அதிகபட்சம் {decimals} மட்டும் அனுமதி.",
    "instructor.validation.step2.indirect_mark_must_be_integer": "'{sheet_name}' தாளின் {cell} செல்லில் '{value}' தவறான மறைமுக mark. முழு எண் Likert மதிப்பை மட்டுமே பயன்படுத்தவும்.",
    "instructor.validation.step2.absence_policy_violation": "'{sheet_name}' தாளின் வரி {row} இல் {range} பகுதியில் absence மற்றும் எண் மதிப்புகள் கலந்துள்ளது. முழுவதும் A/a அல்லது முழுவதும் எண் மதிப்புகள் மட்டுமே உள்ளிடவும்.",
    "instructor.validation.step2.total_formula_mismatch": "'{sheet_name}' தாளின் {cell} இல் total formula மாற்றப்பட்டுள்ளது.",
    "instructor.validation.step2.co_formula_mismatch": "'{sheet_name}' தாளின் {cell} இல் CO split formula மாற்றப்பட்டுள்ளது.",
    "instructor.validation.step2.structure_snapshot_missing": "'{sheet_name}' தாளுக்கான mark-structure metadata அமைப்பு விவரப்பட்டியல்-இல் இல்லை.",
    "instructor.validation.step2.structure_snapshot_mismatch": "'{sheet_name}' தாளின் mark-structure {cell} செல்லின் மதிப்பு மாற்றப்பட்டுள்ளது.",
    "instructor.validation.step2.student_identity_spec_invalid": "'{sheet_name}' தாளுக்கான student identity metadata அமைப்பு விவரப்பட்டியல்-இல் தவறாக உள்ளது.",
    "instructor.validation.step2.student_identity_mismatch": "'{sheet_name}' தாளில் மாணவர் Reg. No./Name வரிசைகள் மாற்றப்பட்டுள்ளன.",
    "instructor.validation.step2.student_reg_duplicate": "'{sheet_name}' தாளில் மாணவர் Reg. No. '{reg_no}' நகலாக உள்ளது.",
    "instructor.validation.step2.student_identity_cross_sheet_mismatch": "'{sheet_name}' தாளின் மாணவர் Reg. No./Name வரிசைகள் '{reference_sheet}' தாளுடன் பொருந்தவில்லை.",
    "instructor.validation.final_report.layout_manifest_invalid": "இறுதி அறிக்கை உருவாக்குதல் தோல்வியடைந்தது: அமைப்பு விவரப்பட்டியல் தவறானது.",
    "instructor.validation.final_report.direct_component_sheet_missing": "இறுதி அறிக்கை உருவாக்குதல் தோல்வியடைந்தது: '{component}' க்கான நேரடி கூறு தாள் இல்லை.",
    "instructor.validation.final_report.direct_component_marks_shape_invalid": "இறுதி அறிக்கை உருவாக்குதல் தோல்வியடைந்தது: '{component}' க்கான மதிப்பெண்கள் அமைப்பு தவறானது.",
    "instructor.validation.final_report.no_direct_components": "இறுதி அறிக்கை உருவாக்குதல் தோல்வியடைந்தது: நேரடி கூறுகள் எதுவும் இல்லை.",
    # Instructor template headers / labels
    # Coordinator module
    "coordinator.title": "பாட அடைவு",
    "coordinator.drop_hint": "பயிற்றுநர் தொகுதியின் இறுதி படியில் உருவாக்கப்பட்ட Final CO report பணிப்புத்தகம்-களை சேகரிக்கவும்.",
    "coordinator.calculate": "CO அடைவை கணக்கிடு",
    "coordinator.thresholds.title": "CO அடைவு வரம்புகள்",
    "coordinator.thresholds.description": (
        "- L1 வரம்பு என்பது பாடத்தின் தேர்ச்சி மதிப்பெண் அல்லது முந்தைய விதிமுறையில் வழங்கப்பட்ட 3 தொகுதிகளின் பாட சராசரி.\n"
        "- L2 வரம்பு என்பது முதல் வகுப்பு.\n"
        "- L3 வரம்பு என்பது சிறப்புத் தரம்."
    ),
    "coordinator.thresholds.l1.label": "L1 வரம்பு:",
    "coordinator.thresholds.l2.label": "L2 வரம்பு:",
    "coordinator.thresholds.l3.label": "L3 வரம்பு:",
    "coordinator.thresholds.invalid_rule": "Threshold rule violated: keep 0 < L1 < L2 < L3 < 100.",
    "coordinator.dialog.title": "Excel கோப்புகளை தேர்வு செய்ய",
    "coordinator.links.uploaded_report": "பதிவேற்றப்பட்ட Final CO Report",
    "coordinator.links.downloaded_output": "பதிவிறக்கப்பட்ட வெளியீடு",
    "coordinator.summary": "கோப்புகள்: {count}",
    "coordinator.file.remove_fallback": "நீக்கு",
    "coordinator.file.remove_tooltip": "கோப்பை நீக்கு",
    "coordinator.clear_all": "அனைத்தையும் நீக்கு",
    "coordinator.status.added": "{added} கோப்பு(கள்) சேர்க்கப்பட்டது. மொத்தம்: {total}.",
    "coordinator.duplicate.title": "கோப்பு ஏற்கனவே உள்ளது",
    "coordinator.duplicate.body": "பட்டியலில் ஏற்கனவே உள்ளதால் {count} நகல் கோப்பு(கள்) தவிர்க்கப்பட்டன.",
    "coordinator.invalid_final_report.title": "தவறான இறுதி CO அறிக்கை",
    "coordinator.invalid_final_report.body": "பயிற்றுநர் படி 3 மூலம் உருவாக்கப்பட்ட இறுதி CO report பணிப்புத்தகங்கள் மட்டுமே அனுமதிக்கப்படும்.\n\n{files}",
    "coordinator.status.ignored": (
        "{count} கோப்பு(கள்) புறக்கணிக்கப்பட்டன (ஆதரிக்காத வகை, இல்லை, நகல், "
        "அல்லது தவறான final report workbook)."
    ),
    "coordinator.status.removed": "{count} கோப்பு(கள்) நீக்கப்பட்டன.",
    "coordinator.status.cleared": "{count} கோப்பு(கள்) அழிக்கப்பட்டன.",
    "coordinator.status.processing_started": "தேர்ந்தெடுக்கப்பட்ட கோப்புகள் செயலாக்கப்படுகின்றன...",
    "coordinator.status.queued": "நடப்பு செயலாக்கம் நடைபெறுவதால் {count} கோப்பு(கள்) வரிசைப்படுத்தப்பட்டன.",
    "coordinator.status.operation_cancelled": "ஒருங்கிணைப்பாளர் செயலாக்கம் ரத்து செய்யப்பட்டது.",
    "coordinator.status.processing_failed": "ஒருங்கிணைப்பாளர் செயலாக்கம் தோல்வியடைந்தது.",
    "coordinator.status.processing_completed": "ஒருங்கிணைப்பாளர் செயலாக்கம் முடிந்தது.",
    "coordinator.status.calculate_completed": "CO அடைவு கணக்கீடு நிறைவடைந்து வெளியீட்டு பணிப்புத்தகம் உருவாக்கப்பட்டது.",
    "coordinator.regno_dedup.title": "நகல் பதிவு எண்கள் நீக்கப்பட்டன",
    "coordinator.regno_dedup.body": "CO அடைவு உருவாக்கும்போது {count} நகல் பதிவு எண் பதிவுகள் நீக்கப்பட்டன.",
    "coordinator.regno_dedup.log_body": "{count} நகல் பதிவு எண் பதிவுகள் நீக்கப்பட்டன:\n{details}",
    "coordinator.regno_dedup.log_detail": "பதிவு எண்: {reg_no} | பணித்தாள்: {worksheet} | பணிப்புத்தகம்: {workbook}",
    "coordinator.regno_dedup.log_detail_unavailable": "நகல் பதிவு விவரங்கள் கிடைக்கவில்லை.",
}



