"""Tamil (India) text catalog for user-facing strings."""

TEXTS = {
    # Startup / main
    "app.already_running": "பயன்பாடு ஏற்கனவே இயங்கிக்கொண்டிருக்கிறது.",
    "app.unexpected_error": "எதிர்பாராத பிழை ஏற்பட்டது. பதிவு கோப்பை சரிபார்க்கவும்.",
    "app.main_window_title": "FOCUS",
    "splash.starting": "பயன்பாடு தொடங்குகிறது...",
    "splash.loading_main_window": "முதன்மை சாளரம் ஏற்றப்படுகிறது...",
    # Main window
    "toolbar.navigation": "வழிசெலுத்தல்",
    "status.ready": "தயார்",
    "module.placeholder": "{title} தொகுதி இன்னும் செயல்படுத்தப்படவில்லை.",
    "module.instructor": "பயிற்றுநர்",
    "module.course_coordinator": "பாட ஒருங்கிணைப்பாளர்",
    "module.coordinator_short": "ஒருங்கிணைப்பாளர்",
    "module.po_analysis": "PO பகுப்பாய்வு",
    "module.load_failed_title": "தொகுதி ஏற்றப் பிழை",
    "module.load_failed_body": "'{module}' தொகுதியை ஏற்ற முடியவில்லை.\n\nவிவரம்: {error}",
    "module.load_failed_status": "தொகுதியை ஏற்ற முடியவில்லை: {module}.",
    "nav.help": "உதவி",
    "nav.about": "பற்றி",
    # Settings module
    "settings.title": "பயன்பாட்டு அமைப்புகள்",
    "settings.theme": "தீம்",
    "settings.language": "மொழி",
    "settings.theme.system": "கணினி இயல்புநிலை",
    "settings.theme.light": "ஒளி",
    "settings.theme.dark": "இருள்",
    "settings.apply": "பயன்படுத்து",
    "settings.saved.title": "அமைப்புகள் புதுப்பிக்கப்பட்டன",
    "settings.saved.body": "மொழி விருப்பம் செயல்படுத்தப்பட்டது.",
    "settings.saved.status": "அமைப்புகள் பயன்படுத்தப்பட்டன.",
    "language.switcher.button": "மொழி: {language}",
    "language.switcher.status": "மொழி {language}",
    "language.switcher.applied_status": "மொழி {language} ஆக அமைக்கப்பட்டது.",
    # About
    "about.version": "பதிப்பு {version}",
    "about.description": (
        "{app_name} என்பது Course Outcome (CO) அடைவை கணக்கிடவும், "
        "நேரடி மற்றும் மறைமுக மதிப்பீடுகளை அடிப்படையாகக் கொண்டு "
        "கட்டமைக்கப்பட்ட முடிவு பகுப்பாய்வை செய்யவும் வடிவமைக்கப்பட்ட மென்பொருள் கருவி."
    ),
    "about.institution": "கலசலிங்கம் ஆராய்ச்சி மற்றும் கல்வி கழகம் (KARE) இல் உருவாக்கப்பட்டது.",
    "about.copyright": "(c) {year} KARE. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    # Help module
    "help.doc_missing_title": "உதவி ஆவணம் இல்லை",
    "help.doc_missing_body": "உதவி PDF கிடைக்கவில்லை:\n{path}",
    "help.doc_error_title": "உதவி ஆவணப் பிழை",
    "help.doc_error_body": "உதவி PDF ஐ ஏற்ற முடியவில்லை.",
    "help.download_pdf": "PDF பதிவிறக்கு",
    "help.open_default_viewer": "இயல்புநிலை பார்வியில் திற",
    "help.missing_file_title": "கோப்பு இல்லை",
    "help.missing_file_body": "உதவி PDF கிடைக்கவில்லை.",
    "help.save_title": "CO அடைவு ஆவணத்தை சேமி",
    "help.save_default_name": "CO_Calculation_Document.pdf",
    "help.save_filter_pdf": "PDF கோப்புகள் (*.pdf)",
    "help.save_failed_title": "சேமித்தல் தோல்வி",
    "help.save_failed_body": "உதவி PDF சேமிக்கும் போது பிழை ஏற்பட்டது.",
    "help.save_success_title": "சேமிக்கப்பட்டது",
    "help.save_success_body": "உதவி PDF வெற்றிகரமாக சேமிக்கப்பட்டது.",
    "help.open_failed_title": "திறத்தல் தோல்வி",
    "help.open_failed_body": "இயல்புநிலை பார்வியில் உதவி PDF ஐ திறக்க முடியவில்லை.",
    "help.open_success_title": "திறக்கப்பட்டது",
    "help.open_success_body": "உதவி PDF இயல்புநிலை பார்வியில் திறக்கப்பட்டது.",
    "help.status.doc_loaded": "உதவி ஆவணம் ஏற்றப்பட்டது.",
    "help.status.doc_missing": "உதவி ஆவணம் இல்லை.",
    "help.status.doc_error": "உதவி ஆவணத்தை ஏற்ற முடியவில்லை.",
    "help.status.file_missing": "உதவி PDF கிடைக்கவில்லை.",
    "help.status.save_success": "உதவி PDF வெற்றிகரமாக சேமிக்கப்பட்டது.",
    "help.status.save_failed": "உதவி PDF சேமிக்கும் போது பிழை ஏற்பட்டது.",
    "help.status.open_success": "உதவி PDF இயல்புநிலை பார்வியில் திறக்கப்பட்டது.",
    "help.status.open_failed": "உதவி PDF திறக்கும் போது பிழை ஏற்பட்டது.",
    # Instructor module
    "instructor.workflow_title": "CO பணிச்சுற்று",
    "instructor.progress": "{completed} / {total} முடிந்தது",
    "instructor.step_button": "{number}. {title}",
    "instructor.step1.title": "பாட வார்ப்புருவை பதிவிறக்கு",
    "instructor.step2.title": "மதிப்பெண் வார்ப்புருவை உருவாக்கு",
    "instructor.step3.title": "CO மதிப்பெண் அறிக்கையை உருவாக்கு",
    "instructor.step4.title": "நிரப்பப்பட்ட மதிப்பெண்களை பதிவேற்று",
    "instructor.step5.title": "இறுதி CO அறிக்கையை உருவாக்கு",
    "instructor.step1.desc": "பாட விவரங்களை உள்ளிட பயன்படுத்தப்படும் காலி வார்ப்புருவை பதிவிறக்கவும்.",
    "instructor.step2.desc": "சரிபார்க்கப்பட்ட பாட விவர கோப்பை பதிவேற்றி, மதிப்பெண் வார்ப்புருவை தயாரித்து சேமிக்கவும்.",
    "instructor.step3.desc": "நிரப்பப்பட்ட மதிப்பெண் பணிப்புத்தகத்தை சரிபார்த்து பதிவேற்றி, இறுதி CO அறிக்கையை உருவாக்கவும்.",
    "instructor.step4.desc": "நிரப்பப்பட்ட மதிப்பெண் பணிப்புத்தகத்தை பதிவேற்றவும்.",
    "instructor.step5.desc": "ஒவ்வொரு மாணவருக்கும் கணக்கிடப்பட்ட CO மொத்தங்களுடன் இறுதி பணிப்புத்தகத்தை உருவாக்கவும்.",
    "instructor.badge.pending": "நிலுவையில்",
    "instructor.badge.done": "முடிந்தது",
    "instructor.badge.needs_update": "புதுப்பிப்பு தேவை",
    "instructor.links.title": "உருவாக்கப்பட்ட வெளியீடுகள்",
    "instructor.links.course_details_generated": "உருவாக்கப்பட்ட பாட விவர வார்ப்புரு",
    "instructor.links.course_details_uploaded": "பதிவேற்றப்பட்ட பாட விவர கோப்பு",
    "instructor.links.marks_template_generated": "உருவாக்கப்பட்ட மதிப்பெண் வார்ப்புரு",
    "instructor.links.marks_template_uploaded": "பதிவேற்றப்பட்ட மதிப்பெண் வார்ப்புரு",
    "instructor.links.final_co_report_generated": "உருவாக்கப்பட்ட இறுதி CO அறிக்கை",
    "instructor.links.open_file": "கோப்பை திற",
    "instructor.links.open_folder": "கோப்புறையை திற",
    "instructor.links.not_available": "இன்னும் கிடைக்கவில்லை",
    "instructor.links.open_failed": "தேர்ந்தெடுக்கப்பட்ட பாதையை திறக்க முடியவில்லை.",
    "instructor.file.none": "இன்னும் கோப்பு/பாதை தேர்வு செய்யப்படவில்லை.",
    "instructor.note.default": "முடித்த எந்த படியையும் மீண்டும் திறந்து மாற்றலாம்.",
    "instructor.note.outdated_current": "இந்த படி காலாவதியானது. இந்த படியை மீண்டும் இயக்கவும்.",
    "instructor.note.outdated_downstream": "மேல்நிலை மாற்றம் செய்யப்பட்டுள்ளது. அடுத்த படிகளை மீண்டும் உருவாக்க வேண்டி இருக்கலாம்.",
    "instructor.active_title": "படி {number}: {title}",
    "instructor.action.step1.default": "வார்ப்புருவை பதிவிறக்கு",
    "instructor.action.step1.redo": "வார்ப்புருவை மீண்டும் பதிவிறக்கு",
    "instructor.action.step2.default": "பதிவேற்று & மதிப்பெண் வார்ப்புரு உருவாக்கு",
    "instructor.action.step2.redo": "மாற்றி & மதிப்பெண் வார்ப்புரு மீண்டும் உருவாக்கு",
    "instructor.action.step2.upload": "பாட விவரங்களை பதிவேற்று",
    "instructor.action.step2.prepare": "மதிப்பெண் வார்ப்புருவை தயாரி",
    "instructor.action.step4.default": "நிரப்பப்பட்ட மதிப்பெண்களை பதிவேற்று",
    "instructor.action.step4.redo": "நிரப்பப்பட்ட மதிப்பெண்களை மாற்று",
    "instructor.action.step5.default": "இறுதி CO அறிக்கையை உருவாக்கு",
    "instructor.action.step5.redo": "இறுதி CO அறிக்கையை மீண்டும் உருவாக்கு",
    "instructor.require.step2": "முதலில் படி 2 ஐ முடிக்கவும்.",
    "instructor.require.step3": "முதலில் படி 3 ஐ முடிக்கவும்.",
    "instructor.msg.success_title": "வெற்றி",
    "instructor.msg.validation_title": "சரிபார்ப்பு பிழை",
    "instructor.msg.error_title": "தோல்வி",
    "instructor.msg.step_completed": "படி {step} முடிந்தது: {title}.",
    "instructor.msg.failed_to_do": "{action} செய்ய முடியவில்லை.",
    "instructor.msg.step_required_title": "படி தேவை",
    "instructor.dialog.filter.excel": "Excel கோப்புகள் (*.xlsx)",
    "instructor.dialog.filter.excel_open": "Excel கோப்புகள் (*.xlsx *.xlsm *.xls)",
    "instructor.dialog.step1.title": "பாட விவர வார்ப்புருவை சேமிக்க",
    "instructor.dialog.step1.default_name": "course_details_template.xlsx",
    "instructor.dialog.step2.title": "பாட விவர கோப்பை தேர்வு செய்ய",
    "instructor.dialog.step3.title": "நிரப்பப்பட்ட மதிப்பெண் கோப்பை தேர்வு செய்ய",
    "instructor.dialog.step3.default_name": "marks_template.xlsx",
    "instructor.dialog.step4.title": "இறுதி CO அறிக்கையை சேமிக்க",
    "instructor.dialog.step4.default_name": "co_report.xlsx",
    "instructor.status.step1_selected": "வார்ப்புரு பதிவிறக்கப் பாதை தேர்வு செய்யப்பட்டது.",
    "instructor.status.step2_validated": "பாட விவரங்கள் பதிவேற்றப்பட்டு சரிபார்க்கப்பட்டன. இப்போது மதிப்பெண் வார்ப்புருவை தயாரிக்கலாம்.",
    "instructor.status.step2_uploaded": "மதிப்பெண் வார்ப்புரு உருவாக்கப்பட்டது.",
    "instructor.status.step2_changed": "பாட விவரங்கள் மாற்றப்பட்டன. அடுத்த படிகளை மீண்டும் செய்யவும்.",
    "instructor.status.step3_selected": "மதிப்பெண் வார்ப்புரு உருவாக்கப்பட்டது.",
    "instructor.status.step3_uploaded": "நிரப்பப்பட்ட மதிப்பெண்கள் பதிவேற்றப்பட்டன.",
    "instructor.status.step3_changed": "நிரப்பப்பட்ட மதிப்பெண்கள் மாற்றப்பட்டன. இறுதி அறிக்கையை மீண்டும் உருவாக்கவும்.",
    "instructor.status.step4_selected": "இறுதி CO அறிக்கைப் பாதை தேர்வு செய்யப்பட்டது.",
    "instructor.status.step4_changed": "நிரப்பப்பட்ட மதிப்பெண்கள் மாற்றப்பட்டன. இறுதி அறிக்கையை மீண்டும் உருவாக்கவும்.",
    "instructor.status.operation_in_progress": "செயல் நடைபெற்று கொண்டிருக்கிறது...",
    "instructor.status.operation_cancelled": "செயல் ரத்து செய்யப்பட்டது.",
    "instructor.timer.idle": "",
    "instructor.timer.running": "செயல்படுகிறது... {elapsed}",
    "instructor.log.title": "செயல் பதிவு",
    "instructor.log.ready": "செயல் பதிவு தொடங்கப்பட்டது.",
    "instructor.log.completed_process": "{process} வெற்றிகரமாக முடிந்தது.",
    "instructor.log.error_while_process": "{process} செய்யும் போது பிழை ஏற்பட்டது.",
    "instructor.log.process.generate_course_details_template": "பாட விவர வார்ப்புருவை உருவாக்குதல்",
    "instructor.log.process.validate_course_details_workbook": "பதிவேற்றப்பட்ட பாட விவர workbook-ஐ சரிபார்த்தல்",
    "instructor.log.process.generate_marks_template": "மதிப்பெண் வார்ப்புருவை உருவாக்குதல்",
    "instructor.log.process.upload_filled_marks_workbook": "நிரப்பப்பட்ட மதிப்பெண் workbook-ஐ பதிவேற்றுதல்",
    "instructor.log.process.generate_final_co_report": "இறுதி CO அறிக்கையை உருவாக்குதல்",
    "instructor.validation.xlsxwriter_missing": "xlsxwriter நிறுவப்படவில்லை. பாட வார்ப்புருக்களை உருவாக்க அதை நிறுவவும்.",
    "instructor.validation.sheet_single_header_row": "'{sheet_name}' தாளில் துல்லியமாக ஒரு தலைப்பு வரி மட்டுமே இருக்க வேண்டும்.",
    "instructor.system.template_generate_failed": "'{output}' இடத்தில் பாட விவர வார்ப்புருவை உருவாக்க முடியவில்லை.",
    "instructor.validation.unknown_template": "அறியப்படாத workbook வார்ப்புரு '{template_id}'. கிடைக்கும் வார்ப்புருக்கள்: {available}.",
    "instructor.validation.invalid_sheet_name": "தவறான தாள் பெயர்.",
    "instructor.validation.headers_empty": "'{sheet_name}' தாளுக்கான தலைப்புகள் காலியாக இருக்கக்கூடாது.",
    "instructor.validation.headers_unique": "'{sheet_name}' தாளில் தலைப்புகள் தனித்துவமாக இருக்க வேண்டும்.",
    "instructor.validation.row_length_mismatch": "'{sheet_name}' தாளில் வரி {row} நீளம் பொருந்தவில்லை: எதிர்பார்ப்பு {expected}, கிடைத்தது {found}.",
    "instructor.validation.openpyxl_missing": "openpyxl நிறுவப்படவில்லை. பதிவேற்றப்பட்ட பாட விவரங்களை சரிபார்க்க அதை நிறுவவும்.",
    "instructor.validation.workbook_not_found": "பாட விவர workbook கிடைக்கவில்லை: {workbook}",
    "instructor.validation.workbook_open_failed": "பாட விவர workbook '{workbook}' ஐ திறக்க முடியவில்லை.",
    "instructor.validation.system_sheet_missing": "பதிவேற்றப்பட்ட workbook இல் தேவையான system தாள் '{sheet}' இல்லை.",
    "instructor.validation.system_hash_missing_template_id_header": "தவறான system hash தாள் வடிவம்: Template_ID header இல்லை.",
    "instructor.validation.system_hash_missing_template_hash_header": "தவறான system hash தாள் வடிவம்: Template_Hash header இல்லை.",
    "instructor.validation.system_hash_template_id_missing": "system hash தாளில் Template_ID இல்லை.",
    "instructor.validation.system_hash_mismatch": "Template hash பொருந்தவில்லை. சரியான உருவாக்கப்பட்ட வார்ப்புருவைப் பயன்படுத்தவும்.",
    "instructor.validation.workbook_sheet_mismatch": "Workbook தாள்கள் '{template_id}' வார்ப்புருவுடன் பொருந்தவில்லை. எதிர்பார்ப்பு: {expected}. கிடைத்தது: {found}.",
    "instructor.validation.header_mismatch": "'{sheet_name}' தாளில் header பொருந்தவில்லை. எதிர்பார்ப்பு: {expected}.",
    "instructor.validation.unexpected_header": "'{sheet_name}' தாளின் நெடுவரிசை {col} இல் எதிர்பாராத header.",
    "instructor.validation.validator_missing": "'{template_id}' வார்ப்புருவுக்கு validator இல்லை.",
    "instructor.validation.course_metadata_field_empty": "Course_Metadata வரி {row}: Field காலியாக இருக்கக்கூடாது.",
    "instructor.validation.course_metadata_duplicate_field": "Course_Metadata வரி {row}: நகல் field '{field}'.",
    "instructor.validation.course_metadata_unknown_field": "Course_Metadata வரி {row}: அறியப்படாத field '{field}'.",
    "instructor.validation.course_metadata_value_required": "Course_Metadata வரி {row}: '{field}' க்கு Value அவசியம்.",
    "instructor.validation.course_metadata_missing_fields": "Course_Metadata இல் தேவையான fields இல்லை: {fields}.",
    "instructor.validation.course_metadata_field_must_be_int": "Course_Metadata field '{field}' முழு எண்ணாக இருக்க வேண்டும்.",
    "instructor.validation.course_metadata_field_must_be_non_empty_str": "Course_Metadata field '{field}' காலியல்லாத உரையாக இருக்க வேண்டும்.",
    "instructor.validation.course_metadata_total_outcomes_invalid": "Course_Metadata field 'Total_Outcomes' 0-ஐ விட பெரிய முழு எண்ணாக இருக்க வேண்டும்.",
    "instructor.validation.yes_no_required": "{sheet_name} வரி {row}: '{field}' என்பது YES அல்லது NO ஆக இருக்க வேண்டும்.",
    "instructor.validation.assessment_component_required_one": "Assessment_Config இல் குறைந்தது ஒரு component இருக்க வேண்டும்.",
    "instructor.validation.assessment_component_required": "Assessment_Config வரி {row}: Component அவசியம்.",
    "instructor.validation.assessment_component_duplicate": "Assessment_Config வரி {row}: நகல் component '{component}'.",
    "instructor.validation.assessment_weight_numeric": "Assessment_Config வரி {row}: Weight (%) எண் மதிப்பாக இருக்க வேண்டும்.",
    "instructor.validation.assessment_direct_missing": "Assessment_Config இல் குறைந்தது ஒரு direct component இருக்க வேண்டும்.",
    "instructor.validation.assessment_indirect_missing": "Assessment_Config இல் குறைந்தது ஒரு indirect component இருக்க வேண்டும்.",
    "instructor.validation.assessment_direct_total_invalid": "Assessment_Config direct component weights மொத்தம் 100 ஆக இருக்க வேண்டும். கிடைத்தது: {found}.",
    "instructor.validation.assessment_indirect_total_invalid": "Assessment_Config indirect component weights மொத்தம் 100 ஆக இருக்க வேண்டும். கிடைத்தது: {found}.",
    "instructor.validation.question_map_row_required_one": "Question_Map இல் குறைந்தது ஒரு கேள்வி வரி இருக்க வேண்டும்.",
    "instructor.validation.question_component_required": "Question_Map வரி {row}: Component அவசியம்.",
    "instructor.validation.question_component_unknown": "Question_Map வரி {row}: அறியப்படாத component '{component}'.",
    "instructor.validation.question_label_required": "Question_Map வரி {row}: Q_No/Rubric_Parameter அவசியம்.",
    "instructor.validation.question_max_marks_numeric": "Question_Map வரி {row}: Max_Marks எண் மதிப்பாக இருக்க வேண்டும்.",
    "instructor.validation.question_max_marks_positive": "Question_Map வரி {row}: Max_Marks பூஜ்யத்தை விட பெரியதாக இருக்க வேண்டும்.",
    "instructor.validation.question_co_required": "Question_Map வரி {row}: CO இல் குறைந்தது ஒரு மதிப்பு இருக்க வேண்டும்.",
    "instructor.validation.question_co_no_repeat": "Question_Map வரி {row}: CO மதிப்புகள் மீண்டும் வரக்கூடாது.",
    "instructor.validation.question_co_out_of_range": "Question_Map வரி {row}: CO மதிப்பு 1..{total_outcomes} வரம்பிற்கு வெளியே உள்ளது.",
    "instructor.validation.question_co_wise_requires_one": "Question_Map வரி {row}: '{component}' component-க்கு ஒவ்வொரு கேள்விக்கும் துல்லியமாக ஒரு CO மட்டும் இருக்க வேண்டும்.",
    "instructor.validation.question_duplicate_for_component": "Question_Map வரி {row}: '{component}' component-க்கு நகல் கேள்வி '{question}'.",
    "instructor.validation.students_row_required_one": "Students தாளில் குறைந்தது ஒரு மாணவர் வரி இருக்க வேண்டும்.",
    "instructor.validation.students_reg_and_name_required": "Students வரி {row}: Reg_No மற்றும் Student_Name இரண்டும் அவசியம்.",
    "instructor.validation.students_duplicate_reg_no": "Students வரி {row}: நகல் Reg_No '{reg_no}'.",
    "instructor.validation.filled_marks_workbook_invalid": "நிரப்பப்பட்ட மதிப்பெண் பணிப்புத்தகம் தவறானது அல்லது இந்த கருவி மூலம் உருவாக்கப்படவில்லை.",
    "instructor.validation.step3.layout_sheet_missing": "நிரப்பப்பட்ட மதிப்பெண் workbook-இல் தேவையான layout தாள் '{sheet}' இல்லை.",
    "instructor.validation.step3.layout_header_mismatch": "Layout தாளின் {column} header தவறானது. எதிர்பார்ப்பு '{expected}'.",
    "instructor.validation.step3.layout_manifest_missing": "System layout தாளில் layout manifest அல்லது hash இல்லை.",
    "instructor.validation.step3.layout_hash_mismatch": "Layout hash பொருந்தவில்லை. மாற்றமில்லா உருவாக்கப்பட்ட marks template-ஐ பயன்படுத்தவும்.",
    "instructor.validation.step3.layout_manifest_json_invalid": "Layout manifest JSON தவறான வடிவத்தில் உள்ளது.",
    "instructor.validation.step3.template_validator_missing": "Template '{template_id}' க்கான Step 3 validator இல்லை.",
    "instructor.validation.step3.manifest_root_invalid": "Layout manifest root ஒரு object ஆக இருக்க வேண்டும்.",
    "instructor.validation.step3.manifest_structure_invalid": "Layout manifest-இல் 'sheet_order' மற்றும் 'sheets' இரண்டும் இருக்க வேண்டும்.",
    "instructor.validation.step3.sheet_order_mismatch": "நிரப்பப்பட்ட marks தாள்கள் பொருந்தவில்லை. எதிர்பார்ப்பு: {expected}. கிடைத்தது: {found}.",
    "instructor.validation.step3.manifest_sheet_spec_invalid": "Layout manifest-இல் தவறான sheet specification உள்ளது.",
    "instructor.validation.step3.sheet_missing": "எதிர்பார்க்கப்பட்ட '{sheet_name}' தாள் workbook-இல் இல்லை.",
    "instructor.validation.step3.header_row_invalid": "'{sheet_name}' தாளின் header row metadata தவறானது: {header_row}.",
    "instructor.validation.step3.headers_missing": "'{sheet_name}' தாளுக்கான எதிர்பார்க்கப்பட்ட headers layout manifest-இல் இல்லை.",
    "instructor.validation.step3.anchor_spec_invalid": "'{sheet_name}' தாளுக்கான anchor specification தவறானது.",
    "instructor.validation.step3.formula_anchor_spec_invalid": "'{sheet_name}' தாளுக்கான formula anchor specification தவறானது.",
    "instructor.validation.step3.header_row_mismatch": "'{sheet_name}' தாளின் row {row} header பொருந்தவில்லை. எதிர்பார்ப்பு: {expected}.",
    "instructor.validation.step3.anchor_value_mismatch": "'{sheet_name}' தாளின் {cell} செல்லின் மதிப்பு மாற்றப்பட்டுள்ளது. எதிர்பார்ப்பு '{expected}', கிடைத்தது '{found}'.",
    "instructor.validation.step3.formula_mismatch": "'{sheet_name}' தாளின் {cell} formula மாற்றப்பட்டுள்ளது.",
    "instructor.validation.step3.no_component_sheets": "நிரப்பப்பட்ட marks workbook-இல் component mark-entry தாள்கள் இல்லை.",
    "instructor.validation.step3.mark_entry_empty": "'{sheet_name}' தாளில் {cell} இல் mark-entry காலியாக உள்ளது. பதிவேற்றும் முன் அனைத்து marks-ஐயும் நிரப்பவும்.",
    "instructor.validation.step3.mark_value_invalid": "'{sheet_name}' தாளின் {cell} செல்லில் '{value}' தவறான mark value உள்ளது. அனுமதி: A/a அல்லது {minimum} முதல் {maximum} வரையிலான எண்.",
    "instructor.validation.step3.mark_precision_invalid": "'{sheet_name}' தாளின் {cell} செல்லில் '{value}' அதிக தசம இலக்கங்கள் உள்ளன. அதிகபட்சம் {decimals} மட்டும் அனுமதி.",
    "instructor.validation.step3.indirect_mark_must_be_integer": "'{sheet_name}' தாளின் {cell} செல்லில் '{value}' தவறான indirect mark. முழு எண் Likert மதிப்பை மட்டுமே பயன்படுத்தவும்.",
    "instructor.validation.step3.absence_policy_violation": "'{sheet_name}' தாளின் வரி {row} இல் {range} பகுதியில் absence மற்றும் எண் மதிப்புகள் கலந்துள்ளது. முழுவதும் A/a அல்லது முழுவதும் எண் மதிப்புகள் மட்டுமே உள்ளிடவும்.",
    "instructor.validation.step3.total_formula_mismatch": "'{sheet_name}' தாளின் {cell} இல் total formula மாற்றப்பட்டுள்ளது.",
    "instructor.validation.step3.co_formula_mismatch": "'{sheet_name}' தாளின் {cell} இல் CO split formula மாற்றப்பட்டுள்ளது.",
    "instructor.validation.step3.structure_snapshot_missing": "'{sheet_name}' தாளுக்கான mark-structure metadata layout manifest-இல் இல்லை.",
    "instructor.validation.step3.structure_snapshot_mismatch": "'{sheet_name}' தாளின் mark-structure {cell} செல்லின் மதிப்பு மாற்றப்பட்டுள்ளது.",
    "instructor.validation.step3.student_identity_spec_invalid": "'{sheet_name}' தாளுக்கான student identity metadata layout manifest-இல் தவறாக உள்ளது.",
    "instructor.validation.step3.student_identity_mismatch": "'{sheet_name}' தாளில் மாணவர் Reg. No./Name வரிசைகள் மாற்றப்பட்டுள்ளன.",
    "instructor.validation.step3.student_reg_duplicate": "'{sheet_name}' தாளில் மாணவர் Reg. No. '{reg_no}' நகலாக உள்ளது.",
    "instructor.validation.step3.student_identity_cross_sheet_mismatch": "'{sheet_name}' தாளின் மாணவர் Reg. No./Name வரிசைகள் '{reference_sheet}' தாளுடன் பொருந்தவில்லை.",
    "instructor.validation.final_report.layout_manifest_invalid": "இறுதி அறிக்கை உருவாக்குதல் தோல்வியடைந்தது: layout manifest தவறானது.",
    "instructor.validation.final_report.direct_component_sheet_missing": "இறுதி அறிக்கை உருவாக்குதல் தோல்வியடைந்தது: '{component}' க்கான direct component தாள் இல்லை.",
    "instructor.validation.final_report.direct_component_questions_missing": "இறுதி அறிக்கை உருவாக்குதல் தோல்வியடைந்தது: '{component}' க்கான கேள்வி mapping இல்லை.",
    "instructor.validation.final_report.direct_component_marks_shape_invalid": "இறுதி அறிக்கை உருவாக்குதல் தோல்வியடைந்தது: '{component}' க்கான marks அமைப்பு தவறானது.",
    "instructor.validation.final_report.no_direct_components": "இறுதி அறிக்கை உருவாக்குதல் தோல்வியடைந்தது: direct components எதுவும் இல்லை.",
    # Instructor template headers / labels
    "instructor.template.headers.course_metadata.field": "புலம்",
    "instructor.template.headers.course_metadata.value": "மதிப்பு",
    "instructor.template.headers.assessment.component": "கூறு",
    "instructor.template.headers.assessment.weight": "எடை (%)",
    "instructor.template.headers.assessment.cia": "CIA",
    "instructor.template.headers.assessment.co_wise_breakup": "CO_Wise_Marks_Breakup",
    "instructor.template.headers.assessment.direct": "நேரடி",
    "instructor.template.headers.question_map.component": "கூறு",
    "instructor.template.headers.question_map.question": "Q_No/மதிப்பீட்டு_அளவுகோல்",
    "instructor.template.headers.question_map.max_marks": "அதிகபட்ச_மதிப்பெண்",
    "instructor.template.headers.question_map.co": "CO",
    "instructor.template.headers.students.reg_no": "பதிவு_எண்",
    "instructor.template.headers.students.student_name": "மாணவர்_பெயர்",
    "instructor.template.validation.direct_title": "நேரடி",
    "instructor.template.validation.select_yes_no": "YES அல்லது NO தேர்வு செய்யவும்",
    "instructor.marks.validation.error_title": "தவறான மதிப்பெண்",
    "instructor.marks.validation.error_message": "A/a அல்லது அனுமதிக்கப்பட்ட வரம்பிற்குள் எண் மதிப்பெண் உள்ளிடவும்.",
    "instructor.marks.validation.indirect_error_message": "A/a அல்லது அனுமதிக்கப்பட்ட வரம்பிற்குள் எண் Likert மதிப்பு உள்ளிடவும்.",
    "instructor.marks.row_header.serial_no": "#",
    "instructor.marks.row_header.reg_no": "பதிவு எண்",
    "instructor.marks.row_header.student_name": "மாணவர் பெயர்",
    "instructor.marks.total_label": "மொத்தம்",
    "instructor.marks.co_prefix": "CO",
    "instructor.marks.question_prefix": "Q",
    "instructor.marks.co_marks_label_prefix": "CO க்கான மதிப்பெண்",
    "instructor.marks.cos_label": "COக்கள்",
    "instructor.status.step5_selected": "இறுதி CO அறிக்கைப் பாதை தேர்வு செய்யப்பட்டது.",
    # Coordinator module
    "coordinator.title": "ஒருங்கிணைப்பாளர் கோப்பு சேகரிப்பான்",
    "coordinator.drop_hint": "பயிற்றுநர் தொகுதியின் இறுதி படியில் உருவாக்கப்பட்ட Final CO report workbook-களை சேகரிக்கவும்.",
    "coordinator.list_placeholder": "Final CO report workbook-களை இங்கே இழுத்து விடுங்கள்",
    "coordinator.add_file": "கோப்பை சேர்",
    "coordinator.calculate": "CO அடைவை கணக்கிடு",
    "coordinator.browse_drop": "Final CO Report கோப்புகளை உலாவு அல்லது இங்கே இழுத்து விடுங்கள்",
    "coordinator.dialog.title": "Excel கோப்புகளை தேர்வு செய்ய",
    "coordinator.dialog.filter": "Excel கோப்புகள் (*.xlsx *.xlsm *.xls)",
    "coordinator.links.uploaded_report": "பதிவேற்றப்பட்ட Final CO Report",
    "coordinator.links.downloaded_output": "பதிவிறக்கப்பட்ட வெளியீடு",
    "coordinator.summary": "சேர்க்கப்பட்ட கோப்புகள்: {count}",
    "coordinator.empty": "இன்னும் எந்த Excel கோப்புகளும் சேர்க்கப்படவில்லை.",
    "coordinator.remove_selected": "தேர்வை நீக்கு",
    "coordinator.clear_all": "அனைத்தையும் நீக்கு",
    "coordinator.status.added": "{added} கோப்பு(கள்) சேர்க்கப்பட்டது. மொத்தம்: {total}.",
    "coordinator.duplicate.title": "கோப்பு ஏற்கனவே உள்ளது",
    "coordinator.duplicate.body": "பட்டியலில் ஏற்கனவே உள்ளதால் {count} நகல் கோப்பு(கள்) தவிர்க்கப்பட்டன.",
    "coordinator.invalid_final_report.title": "தவறான Final CO Report",
    "coordinator.invalid_final_report.body": (
        "பயிற்றுநர் படி 3 மூலம் உருவாக்கப்பட்ட Final CO report workbook-கள் மட்டுமே அனுமதிக்கப்படும்.\n\n{files}"
    ),
    "coordinator.status.ignored": (
        "{count} கோப்பு(கள்) புறக்கணிக்கப்பட்டன (ஆதரிக்காத வகை, இல்லை, நகல், "
        "அல்லது தவறான final report workbook)."
    ),
    "coordinator.status.removed": "{count} கோப்பு(கள்) நீக்கப்பட்டன.",
    "coordinator.status.cleared": "{count} கோப்பு(கள்) அழிக்கப்பட்டன.",
    "coordinator.cancel_processing": "செயலாக்கத்தை ரத்து செய்",
    "coordinator.status.processing_started": "தேர்ந்தெடுக்கப்பட்ட கோப்புகள் செயலாக்கப்படுகின்றன...",
    "coordinator.status.queued": "நடப்பு செயலாக்கம் நடைபெறுவதால் {count} கோப்பு(கள்) வரிசைப்படுத்தப்பட்டன.",
    "coordinator.status.cancelling": "ஒருங்கிணைப்பாளர் செயலாக்கம் ரத்து செய்யப்படுகிறது...",
    "coordinator.status.operation_cancelled": "ஒருங்கிணைப்பாளர் செயலாக்கம் ரத்து செய்யப்பட்டது.",
    "coordinator.status.processing_failed": "ஒருங்கிணைப்பாளர் செயலாக்கம் தோல்வியடைந்தது.",
    "coordinator.status.calculate_pending": "இந்த தொகுதியில் CO அடைவு கணக்கீடு இன்னும் செயல்படுத்தப்படவில்லை.",
}
