"""Telugu (India) text catalog for user-facing strings."""

TEXTS = {
    'app.already_running': 'అప్లికేషన్ ఇప్పటికే అమలులో ఉంది.',
    'app.unexpected_error': 'ఊహించని లోపం సంభవించింది. దయచేసి లాగ్ ఫైల్\u200cని తనిఖీ చేయండి.',
    'app.startup.workbook_secret_missing_frozen': 'వర్క్\\u200cబుక్ రహస్యం అందుబాటులో లేదు. దయచేసి సాఫ్ట్\\u200cవేర్\\u200cను మళ్లీ ఇన్\\u200cస్టాల్ చేయండి లేదా మద్దతును సంప్రదించండి.',
    'app.startup.workbook_secret_missing_dev': 'వర్క్\\u200cబుక్ రహస్యం అందుబాటులో లేదు. స్థానిక వర్క్\\u200cబుక్ రహస్య దుకాణాన్ని తొలగించి, మళ్లీ ప్రారంభించండి.',
    'app.main_window_title': 'ఫోకస్',
    'splash.starting': 'అప్లికేషన్\u200cను ప్రారంభిస్తోంది...',
    'splash.loading_main_window': 'ప్రధాన విండోను లోడ్ చేస్తోంది...',
    'toolbar.navigation': 'నావిగేషన్',
    'status.ready': 'సిద్ధం',
    'common.dropzone.placeholder': 'ఫైళ్లను జోడించడానికి Drag and Drop చేయండి, లేదా Ctrl + O నొక్కండి, లేదా ఒక్కసారి క్లిక్ చేయండి',
    'module.placeholder': '{title} మాడ్యూల్ ఇంకా అమలు చేయబడలేదు.',
    'module.instructor': 'బోధకుడు',
    'module.coordinator_short': 'సమన్వయకర్త',
    'module.po_analysis': 'PO విశ్లేషణ',
    'module.co_analysis': 'CO విశ్లేషణ',
    'module.load_failed_title': 'మాడ్యూల్ లోడ్ ఎర్రర్',
    'module.load_failed_body': "మాడ్యూల్ '{module}'ని లోడ్ చేయడం సాధ్యపడలేదు.\n\nవివరాలు: {error}",
    'module.load_failed_status': 'మాడ్యూల్\u200cను లోడ్ చేయడంలో విఫలమైంది: {module}.',
    'nav.help': 'సహాయం',
    'nav.about': 'గురించి',
    'language.switcher.button': 'భాష: {language}',
    'language.switcher.applied_status': 'భాష {language}కి సెట్ చేయబడింది.',
    'about.version': 'వెర్షన్ {version}',
    'about.subtitle': 'ఫ్రేమ్‌వర్క్ ఫర్ ఔట్‌కమ్ కంప్యూటేషన్ అండ్ యూనిఫికేషన్ సిస్టమ్',
    'about.description': '{app_name} అనేది కోర్స్ ఔట్‌కమ్ (CO) సాధనాన్ని గణించడానికి, మరియు ప్రత్యక్ష మరియు పరోక్ష అంచనాల ఆధారంగా నిర్మాణాత్మక ఫలితాల విశ్లేషణ చేయడానికి రూపొందించబడిన సాఫ్ట్\u200cవేర్ సాధనం.',
    'about.institution': 'కలసలింగం అకాడమీ ఆఫ్ రీసెర్చ్ అండ్ ఎడ్యుకేషన్ (KARE) వద్ద, ఈ క్రింది వారి సహకారంతో అభివృద్ధి చేయబడింది:',
    'about.copyright': '(సి) {year} KARE. అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.',
    'about.contributors.none': 'సహకారుల సమాచారం అందుబాటులో లేదు.',
    'about.repository.link_label': 'గిట్‌హబ్ రిపోజిటరీ',
    'about.meta_line_html': '{copyright} | <a href="{url}">{link_label}</a>',
    'help.doc_missing_title': 'సహాయ పత్రం లేదు',
    'help.doc_missing_body': 'సహాయం PDF కనుగొనబడలేదు:\\n{path}',
    'help.doc_error_title': 'సహాయ పత్రం లోపం',
    'help.doc_error_body': 'సహాయ PDFని లోడ్ చేయడంలో విఫలమైంది.',
    'help.download_pdf': 'PDFని డౌన్\\u200cలోడ్ చేయండి',
    'help.open_default_viewer': 'డిఫాల్ట్ వ్యూయర్\\u200cలో తెరవండి',
    'help.missing_file_title': 'ఫైల్ లేదు',
    'help.save_title': 'CO సాధన పత్రాన్ని సేవ్ చేయండి',
    'help.save_default_name': 'CO_Calculation_Document.pdf',
    'help.save_filter_pdf': 'PDF ఫైల్\\u200cలు (*.pdf)',
    'help.save_failed_title': 'సేవ్ చేయడం విఫలమైంది',
    'help.save_success_title': 'సేవ్ చేయబడింది',
    'help.open_failed_title': 'తెరవడం విఫలమైంది',
    'help.open_failed_body': 'డిఫాల్ట్ వ్యూయర్\\u200cలో సహాయ PDFని తెరవడం సాధ్యపడలేదు.',
    'help.open_success_title': 'తెరవబడింది',
    'help.open_success_body': 'సహాయం PDF డిఫాల్ట్ వ్యూయర్\\u200cలో తెరవబడింది.',
    'help.status.doc_loaded': 'సహాయ పత్రం లోడ్ చేయబడింది.',
    'help.status.doc_missing': 'సహాయ పత్రం లేదు.',
    'help.status.doc_error': 'సహాయ పత్రాన్ని లోడ్ చేయడంలో విఫలమైంది.',
    'help.status.file_missing': 'సహాయం PDF అందుబాటులో లేదు.',
    'help.status.save_success': 'సహాయం PDF విజయవంతంగా సేవ్ చేయబడింది.',
    'help.status.save_failed': 'సహాయ PDFని సేవ్ చేస్తున్నప్పుడు లోపం సంభవించింది.',
    'help.status.open_success': 'సహాయం PDF డిఫాల్ట్ వ్యూయర్\\u200cలో తెరవబడింది.',
    'help.status.open_failed': 'డిఫాల్ట్ వ్యూయర్\\u200cలో సహాయం PDF తెరవడంలో లోపం సంభవించింది.',
    'outputs.title': 'ఉత్పత్తి చేయబడిన అవుట్\\u200cపుట్\\u200cలు',
    'activity.log.title': 'కార్యకలాప లాగ్',
    'activity.log.ready': 'కార్యకలాప లాగ్ ప్రారంభించబడింది.',
    'outputs.none_generated': 'ఏ అవుట్‌పుట్‌లు రూపొందించబడలేదు.',
    'outputs.open_file': 'ఫైల్\\u200cని తెరవండి',
    'outputs.open_folder': ' ఫోల్డర్ తెరవండಿ',
    'outputs.open_failed': 'ಎಂಚುಕುನ್ನ ಮಾರ್ಗಾನ್ನಿ ತೆರವಡಂ ಸಾಧ್ಯಂ ಕಾಲೇದು.',
    'instructor.workflow_title': 'CO వర్క్\\u200cఫ్లో',
    'instructor.links.title': 'ఉత్పత్తి చేయబడిన అవుట్\\u200cపుట్\\u200cలు',
    'instructor.links.course_details_generated': 'కోర్సు వివరాల టెంప్లేట్ రూపొందించబడింది',
    'instructor.links.marks_template_generated': 'మార్కుల టెంప్లేట్ రూపొందించబడింది',
    'instructor.links.open_file': 'ఫైల్\\u200cని తెరవండి',
    'instructor.links.open_folder': 'ఫోల్డర్ తెరవండి',
    'instructor.links.open_failed': 'ఎంచుకున్న మార్గాన్ని తెరవడం సాధ్యం కాలేదు.',
    'instructor.action.download_course_template': 'కోర్సు టెంప్లేట్\\u200cను డౌన్\\u200cలోడ్ చేయండి',
    'instructor.action.download_course_template_link_html': '<a href="{href}">{text}</a>',
    'instructor.action.generate_marks_template': 'మార్కుల మూసను సిద్ధం చేయండి',
    'instructor.msg.success_title': 'విజయం',
    'instructor.msg.validation_title': 'ధ్రువీకరణ లోపం',
    'instructor.msg.error_title': 'విఫలమైంది',
    'instructor.msg.failed_to_do': '{action} చేయడంలో విఫలమైంది.',
    'instructor.dialog.filter.excel': 'Excel ఫైల్స్ (*.xlsx)',
    'instructor.dialog.filter.excel_open': 'Excel ఫైల్స్ (*.xlsx *.xlsm *.xls)',
    'instructor.dialog.course_template.save_title': 'కోర్సు వివరాల టెంప్లేట్\\u200cను సేవ్ చేయండి',
    'instructor.dialog.course_template.default_name': 'course_details_template.xlsx',
    'instructor.dialog.course_details.select_title': 'కోర్సు వివరాల ఫైల్\\u200cని ఎంచుకోండి',
    'instructor.dialog.marks_template.save_title': 'మార్కుల టెంప్లేట్\\u200cను సేవ్ చేయండి',
    'instructor.dialog.marks_template.default_name': 'marks_template.xlsx',
    'instructor.status.template_download_path_selected': 'టెంప్లేట్ డౌన్\\u200cలోడ్ మార్గం ఎంచుకోబడింది.',
    'instructor.status.course_details_validated': 'కోర్సు వివరాలు అప్\\u200cలోడ్ చేయబడ్డాయి మరియు ధృవీకరించబడ్డాయి. మీరు ఇప్పుడు మార్కుల టెంప్లేట్\\u200cను సిద్ధం చేయవచ్చు.',
    'instructor.status.marks_template_generated': 'మార్కుల టెంప్లేట్ రూపొందించబడింది.',
    'instructor.status.course_details_replaced': 'కోర్సు వివరాలు మారాయి. తదుపరి దశలను మళ్లీ అమలు చేయండి.',
    'instructor.status.operation_cancelled': 'ఆపరేషన్ రద్దు చేయబడింది.',
    'instructor.status.course_details_drop_browse_requested': 'డ్రాగ్-అండ్-డ్రాప్ విడ్జెట్ నుండి కోర్సు వివరాల ఫైల్ ఎంపిక అభ్యర్థించబడింది.',
    'instructor.status.course_details_drop_files_dropped': 'కోర్సు వివరాల విడ్జెట్‌లో {count} ఫైల్(లు) డ్రాప్ చేయబడ్డాయి.',
    'instructor.status.course_details_drop_files_changed': 'కోర్సు వివరాల విడ్జెట్‌లో ఇప్పుడు {count} ఫైల్(లు) ఉన్నాయి.',
    'instructor.status.course_details_drop_files_rejected': 'కోర్సు వివరాల విడ్జెట్‌లో డ్రాప్ చేసిన {count} ఫైల్(లు) తిరస్కరించబడ్డాయి.',
    'instructor.status.course_details_validation_progress': 'ధృవీకరించిన చెల్లుబాటు ఫైళ్లు: {valid}/{total}.',
    'instructor.status.marks_template_generation_progress': 'మార్కుల టెంప్లేట్లు ప్రాసెస్ చేసినవి: {processed}/{total}.',
    'instructor.status.marks_template_per_file_failures': 'మార్కుల-టెంప్లేట్ ఫైల్-ప్రతి వైఫల్యాలు: {details}',
    'instructor.drop.summary': 'ఫైల్‌లు: {count}',
    'instructor.toast.course_details_validation_summary': 'ధృవీకరణ పూర్తైంది: చెల్లుబాటు {valid}, చెల్లనివి {invalid}, తప్పు టెంప్లేట్ {mismatched}, నకిలీ ఇన్‌పుట్ {duplicates}.',
    'instructor.toast.marks_template_generation_summary': 'మార్కుల టెంప్లేట్ రూపొందింపు పూర్తైంది: ప్రాసెస్ చేసినవి {processed}/{total}, రూపొందించినవి {generated}, విఫలమైనవి {failed}, దాటవేసినవి {skipped}.',
    'instructor.log.process.generate_course_details_template': 'కోర్సు వివరాల టెంప్లేట్‌ను రూపొందిస్తోంది',
    'instructor.log.process.validate_course_details_workbook': 'అప్‌లోడ్ చేసిన కోర్సు వివరాల వర్క్‌బుక్‌ను ధృవీకరిస్తోంది',
    'instructor.log.process.generate_marks_template': 'మార్కుల టెంప్లేట్‌ను రూపొందిస్తోంది',
    'instructor.validation.course_details_missing': 'మార్కుల టెంప్లేట్ రూపొందించే ముందు కనీసం ఒక చెల్లుబాటు అయ్యే కోర్సు వివరాల వర్క్‌బుక్‌ను అప్‌లోడ్ చేయండి.',
    'coordinator.thresholds.l1.label': 'L1 పరిమితి:',
    'coordinator.thresholds.l2.label': 'L2 పరిమితి:',
    'coordinator.thresholds.l3.label': 'L3 పరిమితి:',
    'coordinator.thresholds.invalid_rule': 'పరిమితి నియమం ఉల్లంఘించబడింది: 0 < L1 < L2 < L3 < 100 ఉండాలి.',
    'coordinator.co_attainment.description': 'స్థిరీకరించిన స్థాయి మరియు అంతకన్నా పై స్థాయిలో ఉన్న విద్యార్థుల % ఆధారంగా సాధన నిర్ణయించబడుతుంది.',
    'coordinator.co_attainment.percent.label': 'CO AT%:',
    'coordinator.co_attainment.level.label': 'CO AT స్థాయి:',
    'coordinator.co_attainment.invalid_percent': 'చెల్లని CO AT%: విలువ 0 నుండి 100 మధ్య ఉండాలి.',
    'coordinator.dialog.title': 'ఎక్సెల్ ఫైల్స్ ఎంచుకోండి',
    'coordinator.links.downloaded_output': 'డౌన్\u200cలోడ్ చేసిన అవుట్\u200cపుట్',
    'coordinator.summary': 'ఫైల్\\u200cలు: {count}',
    'coordinator.file.remove_fallback': 'తొలగించు',
    'coordinator.file.remove_tooltip': 'ఫైల్ తొలగించు',
    'coordinator.clear_all': 'అన్నీ క్లియర్ చేయండి',
    'coordinator.status.added': '{added} ఫైల్(లు) జోడించబడ్డాయి. మొత్తం: {total}.',
    'coordinator.duplicate.title': 'ఫైల్ ఇప్పటికే ఉంది',
    'coordinator.duplicate.body': '{count} నకిలీ ఫైల్(లు) ఇప్పటికే జాబితాలో ఉన్నందున దాటవేయబడ్డాయి.',
    'coordinator.invalid_final_report.title': 'చెల్లని తుది CO నివేదిక',
    'coordinator.invalid_final_report.body': 'చెల్లుబాటు అయ్యే తుది CO నివేదిక వర్క్\\u200cబుక్\\u200cలు మాత్రమే అనుమతించబడతాయి.\\n\\n{files}',
    'coordinator.invalid_final_report.details_prefix': 'వివరాలు:',
    'coordinator.invalid_final_report.detail_line': '{file}: {reason}',
    'coordinator.status.ignored': '{count} ఫైల్(లు) పట్టించుకోలేదు (మద్దతు లేని రకం, ఫైల్ దొరకకపోవడం, నకిలీ లేదా చెల్లని తుది నివేదిక వర్క్\u200cబుక్).',
    'coordinator.status.removed': '{count} ఫైల్(లు) తీసివేయబడ్డాయి.',
    'coordinator.status.cleared': '{count} ఫైల్(లు) క్లియర్ చేయబడ్డాయి.',
    'coordinator.status.processing_started': 'ఎంచుకున్న ఫైల్\\u200cలను ప్రాసెస్ చేస్తోంది...',
    'coordinator.status.queued': 'ప్రస్తుత ప్రాసెసింగ్ నడుస్తున్నప్పుడు {count} ఫైల్(లు) క్యూలో ఉన్నాయి.',
    'coordinator.status.operation_cancelled': 'కోఆర్డినేటర్ ప్రాసెసింగ్ రద్దు చేయబడింది.',
    'coordinator.status.processing_failed': 'కోఆర్డినేటర్ ప్రాసెసింగ్ విఫలమైంది.',
    'coordinator.status.processing_completed': 'కోఆర్డినేటర్ ప్రాసెసింగ్ పూర్తయింది.',
    'coordinator.status.calculate_completed': 'CO సాధన గణన పూర్తయింది మరియు అవుట్\\u200cపుట్ వర్క్\\u200cబుక్ రూపొందించబడింది.',
    'coordinator.regno_dedup.title': 'డూప్లికేట్ రిజిస్టర్ నంబర్\\u200cలు తీసివేయబడ్డాయి',
    'coordinator.regno_dedup.body': 'CO సాధన రూపొందిస్తున్నప్పుడు {count} నకిలీ రిజిస్టర్ నంబర్ నమోదులు తొలగించబడ్డాయి.',
    'coordinator.regno_dedup.log_body': '{count} నకిలీ రిజిస్టర్ నంబర్ నమోదులు తొలగించబడ్డాయి:\n{details}',
    'coordinator.regno_dedup.log_detail': 'రెగ్ నంబర్: {reg_no} | వర్క్\u200cషీట్: {worksheet} | వర్క్\u200cబుక్: {workbook}',
    'coordinator.regno_dedup.log_detail_unavailable': 'డూప్లికేట్ ఎంట్రీ వివరాలు అందుబాటులో లేవు.',
    'coordinator.join_drop.body': 'కొన్ని వరుసలు Direct లేదా Indirect షీట్లలో మాత్రమే ఉన్నందున అవి పరిగణించబడలేదు. తొలగించిన వరుసలు: {count}. వివరాల కోసం కార్యాచరణ లాగ్ చూడండి.',
    'co_analysis.status.duplicate_reg_numbers': 'డూప్లికేట్ రిజిస్టర్ నంబర్ల కారణంగా {count} ఫైల్(లు) తిరస్కరించబడ్డాయి.',
    'co_analysis.status.co_count_mismatch': 'మొత్తం ఫలితాల సంఖ్య సరిపోలకపోవడంతో {count} ఫైల్(లు) తిరస్కరించబడ్డాయి.',
    'co_analysis.status.validation_warnings': '{count} ధృవీకరణ హెచ్చరిక(లు) నివేదించబడ్డాయి.',
    'co_analysis.status.rejected_code_with_context': '{file} తిరస్కరించబడింది: {code} ({context})',
    'co_analysis.dialog.select_files': 'విశ్లేషణ కోసం ఫైళ్లను ఎంచుకోండి',
    'co_analysis.validation.co_count_mismatch_body': 'ఎంచుకున్న బ్యాచ్‌తో మొత్తం ఫలితాల సంఖ్య భిన్నంగా ఉండటంతో {count} ఫైల్(లు) తిరస్కరించబడ్డాయి.',
    'co_analysis.validation.anomaly_warnings_body': 'అప్‌లోడ్ చేసిన ఫైల్‌లలో {count} ధృవీకరణ అసాధారణ హెచ్చరిక(లు) నివేదించబడ్డాయి.',
    'co_analysis.validation.rejection_breakdown_title': 'CO Analysis ఫైల్ తిరస్కరణలు',
    'co_analysis.validation.rejection_breakdown_body': (
        'కారణాల వారీగా తిరస్కరించిన ఫైల్‌లు:\\n'
        'మద్దతు లేని/లేని ఫైళ్లు: {unsupported_or_missing}\\n'
        'చెల్లని వర్క్‌బుక్: {invalid_workbook}\\n'
        'సిస్టమ్ హాష్/గుర్తింపు వైఫల్యాలు: {invalid_hash}\\n'
        'మార్కులు నింపలేదు: {marks_unfilled}\\n'
        'లేఅవుట్/మానిఫెస్ట్ వైఫల్యాలు: {layout_manifest}\\n'
        'టెంప్లేట్ సరిపోలిక లేదు: {template_mismatch}\\n'
        'చెల్లని మార్క్ విలువ/ఫార్మాట్: {mark_value}\\n'
        'ఇతర ధృవీకరణ వైఫల్యాలు: {invalid_other}\\n'
        'నకిలీలు: {duplicates}\\n'
        'నకిలీ రిజిస్టర్ నంబర్లు: {duplicate_reg}\\n'
        'మొత్తం ఫలితాల సంఖ్య సరిపోలలేదు: {co_count_mismatch}'
    ),
    'co_analysis.status.ignored_summary': (
        '{count} ఫైల్(లు) పట్టించుకోలేదు. '
        '{part1}{sep1_2}{part2}{sep2_3}{part3}{sep3_4}{part4}{sep4_5}{part5}{sep5_6}{part6}'
        '{sep6_7}{part7}{sep7_8}{part8}{sep8_9}{part9}{sep9_10}{part10}{sep10_11}{part11}{sep11_12}{part12}'
    ),
    'co_analysis.status.ignored_total': '{count} ఫైల్(లు) పట్టించుకోలేదు.',
    'co_analysis.status.ignored_reason.unsupported_or_missing': 'మద్దతు లేని/లేని ఫైళ్లు={count}',
    'co_analysis.status.ignored_reason.invalid_workbook': 'చెల్లని వర్క్‌బుక్={count}',
    'co_analysis.status.ignored_reason.invalid_hash': 'హాష్={count}',
    'co_analysis.status.ignored_reason.marks_unfilled': 'మార్కులు నింపలేదు={count}',
    'co_analysis.status.ignored_reason.layout_manifest': 'లేఅవుట్/మానిఫెస్ట్={count}',
    'co_analysis.status.ignored_reason.template_mismatch': 'టెంప్లేట్ సరిపోలిక లేదు={count}',
    'co_analysis.status.ignored_reason.mark_value': 'చెల్లని మార్క్ విలువ={count}',
    'co_analysis.status.ignored_reason.invalid_other': 'ఇతర ధృవీకరణ={count}',
    'co_analysis.status.ignored_reason.duplicates': 'నకిలీలు={count}',
    'co_analysis.status.ignored_reason.duplicate_reg': 'నకిలీ రిజిస్టర్ నంబర్లు={count}',
    'co_analysis.status.ignored_reason.co_count_mismatch': 'మొత్తం ఫలితాల సంఖ్య సరిపోలలేదు={count}',
}







