"""Telugu (India) text catalog for user-facing strings."""

TEXTS = {
    'app.already_running': 'అప్లికేషన్ ఇప్పటికే అమలులో ఉంది.',
    'app.unexpected_error': 'ఊహించని లోపం సంభవించింది. దయచేసి లాగ్ ఫైల్\u200cని తనిఖీ చేయండి.',
    'app.startup.workbook_secret_missing_frozen': 'వర్క్\\u200cబుక్ రహస్యం అందుబాటులో లేదు. దయచేసి సాఫ్ట్\\u200cవేర్\\u200cను మళ్లీ ఇన్\\u200cస్టాల్ చేయండి లేదా మద్దతును సంప్రదించండి.',
    'app.startup.workbook_secret_missing_dev': 'వర్క్\\u200cబుక్ రహస్యం అందుబాటులో లేదు. స్థానిక వర్క్\\u200cబుక్ రహస్య దుకాణాన్ని తొలగించి, మళ్లీ ప్రారంభించండి.',
    'app.main_window_title': 'ఫోకస్',
    'splash.starting': 'అప్లికేషన్\u200cను ప్రారంభిస్తోంది...',
    'splash.loading_main_window': 'ప్రధాన విండోను లోడ్ చేస్తోంది...',
    'toolbar.navigation': 'నావిగేషన్',
    'status.ready': 'సిద్ధం',
    'module.placeholder': '{title} మాడ్యూల్ ఇంకా అమలు చేయబడలేదు.',
    'module.instructor': 'బోధకుడు',
    'module.coordinator_short': 'సమన్వయకర్త',
    'module.po_analysis': 'PO విశ్లేషణ',
    'module.load_failed_title': 'మాడ్యూల్ లోడ్ ఎర్రర్',
    'module.load_failed_body': "మాడ్యూల్ '{module}'ని లోడ్ చేయడం సాధ్యపడలేదు.\n\nవివరాలు: {error}",
    'module.load_failed_status': 'మాడ్యూల్\u200cను లోడ్ చేయడంలో విఫలమైంది: {module}.',
    'nav.help': 'సహాయం',
    'nav.about': 'గురించి',
    'language.switcher.button': 'భాష: {language}',
    'language.switcher.applied_status': 'భాష {language}కి సెట్ చేయబడింది.',
    'about.version': 'వెర్షన్ {version}',
    'about.subtitle': 'ఫలిత గణన మరియు ఏకీకరణ వ్యవస్థ కోసం ఫ్రేమ్‌వర్క్',
    'about.description': '{app_name} అనేది కోర్సు ఫలితాన్ని (CO) సాధించడం మరియు ప్రత్యక్ష మరియు పరోక్ష అంచనాల ఆధారంగా నిర్మాణాత్మక ఫలితాల విశ్లేషణను కంప్యూటింగ్ చేయడానికి రూపొందించబడిన సాఫ్ట్\u200cవేర్ సాధనం.',
    'about.institution': 'కలశలింగం అకాడమీ ఆఫ్ రీసెర్చ్ అండ్ ఎడ్యుకేషన్ (KARE)లో అభివృద్ధి చేయబడింది.',
    'about.copyright': '(సి) {year} KARE. అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.',
    'help.doc_missing_title': 'సహాయ పత్రం లేదు',
    'help.doc_missing_body': 'సహాయం PDF కనుగొనబడలేదు:\\n{path}',
    'help.doc_error_title': 'సహాయ పత్రం లోపం',
    'help.doc_error_body': 'సహాయ PDFని లోడ్ చేయడంలో విఫలమైంది.',
    'help.download_pdf': 'PDFని డౌన్\\u200cలోడ్ చేయండి',
    'help.open_default_viewer': 'డిఫాల్ట్ వ్యూయర్\\u200cలో తెరవండి',
    'help.missing_file_title': 'ఫైల్ లేదు',
    'help.save_title': 'CO సాధన పత్రాన్ని సేవ్ చేయండి',
    'help.save_default_name': 'CO_Calculation_Document.pdf',
    'help.save_filter_pdf': 'PDF ఫైల్\\u200cలు (*.pdf)',
    'help.save_failed_title': 'సేవ్ చేయడం విఫలమైంది',
    'help.save_success_title': 'సేవ్ చేయబడింది',
    'help.open_failed_title': 'తెరవడం విఫలమైంది',
    'help.open_failed_body': 'డిఫాల్ట్ వ్యూయర్\\u200cలో సహాయ PDFని తెరవడం సాధ్యపడలేదు.',
    'help.open_success_title': 'తెరవబడింది',
    'help.open_success_body': 'సహాయం PDF డిఫాల్ట్ వ్యూయర్\\u200cలో తెరవబడింది.',
    'help.status.doc_loaded': 'సహాయ పత్రం లోడ్ చేయబడింది.',
    'help.status.doc_missing': 'సహాయ పత్రం లేదు.',
    'help.status.doc_error': 'సహాయ పత్రాన్ని లోడ్ చేయడంలో విఫలమైంది.',
    'help.status.file_missing': 'సహాయం PDF అందుబాటులో లేదు.',
    'help.status.save_success': 'సహాయం PDF విజయవంతంగా సేవ్ చేయబడింది.',
    'help.status.save_failed': 'సహాయ PDFని సేవ్ చేస్తున్నప్పుడు లోపం సంభవించింది.',
    'help.status.open_success': 'సహాయం PDF డిఫాల్ట్ వ్యూయర్\\u200cలో తెరవబడింది.',
    'help.status.open_failed': 'డిఫాల్ట్ వ్యూయర్\\u200cలో సహాయ PDFని తెరవడంలో లోపం సంభవించింది.',
    'instructor.workflow_title': 'CO వర్క్\\u200cఫ్లో',
    'instructor.step1.title': 'మార్కుల టెంప్లేట్\\u200cని రూపొందించండి',
    'instructor.step2.title': 'CO మార్కుల నివేదికను రూపొందించండి',
    'instructor.step1.desc': 'ధృవీకరించబడిన కోర్సు-వివరాల ఫైల్\\u200cను అప్\\u200cలోడ్ చేయండి, ఆపై మార్కుల టెంప్లేట్\\u200cను సిద్ధం చేసి, సేవ్ చేయండి.',
    'instructor.step2.desc': 'నింపిన మార్కుల వర్క్\\u200cబుక్\\u200cని అప్\\u200cలోడ్ చేసి, ధృవీకరించండి, ఆపై తుది CO నివేదికను రూపొందించండి.',
    'instructor.links.title': 'ఉత్పత్తి చేయబడిన అవుట్\\u200cపుట్\\u200cలు',
    'instructor.links.course_details_generated': 'కోర్సు వివరాల టెంప్లేట్ రూపొందించబడింది',
    'instructor.links.course_details_uploaded': 'కోర్సు వివరాల ఫైల్ అప్\\u200cలోడ్ చేయబడింది',
    'instructor.links.marks_template_generated': 'మార్కుల టెంప్లేట్ రూపొందించబడింది',
    'instructor.links.marks_template_uploaded': 'మార్కుల టెంప్లేట్ అప్\\u200cలోడ్ చేయబడింది',
    'instructor.links.final_co_report_generated': 'తుది CO నివేదిక రూపొందించబడింది',
    'instructor.links.open_file': 'ఫైల్\\u200cని తెరవండి',
    'instructor.links.open_folder': 'ఫోల్డర్ తెరవండి',
    'instructor.links.not_available': 'ఇంకా అందుబాటులో లేదు',
    'instructor.links.open_failed': 'ఎంచుకున్న మార్గాన్ని తెరవడం సాధ్యం కాలేదు.',
    'instructor.note.default': 'మీరు పూర్తిచేసిన ఏ దశకైనా తిరిగి వెళ్లి దానిని మార్చుకోవచ్చు.',
    'instructor.note.outdated_current': 'ఈ దశ పాతది. ఈ దశను మళ్లీ అమలు చేయండి.',
    'instructor.note.outdated_downstream': 'పై దశలో మార్పు జరిగింది. తదుపరి దశలను మళ్లీ రూపొందించాల్సి రావచ్చు.',
    'instructor.action.step1.default': 'టెంప్లేట్\\u200cని డౌన్\\u200cలోడ్ చేయండి',
    'instructor.action.step1.upload': 'కోర్సు వివరాలను అప్\\u200cలోడ్ చేయండి',
    'instructor.action.step1.prepare': 'మార్కుల మూసను సిద్ధం చేయండి',
    'instructor.action.step2.upload.default': 'నింపిన మార్కులను అప్\\u200cలోడ్ చేయండి',
    'instructor.action.step2.generate.default': 'తుది CO నివేదికను రూపొందించండి',
    'instructor.require.step2': 'ముందుగా 1వ దశను పూర్తి చేయండి.',
    'instructor.require.step1': 'ముందుగా 1వ దశను పూర్తి చేయండి.',
    'instructor.msg.success_title': 'విజయం',
    'instructor.msg.validation_title': 'ధ్రువీకరణ లోపం',
    'instructor.msg.error_title': 'విఫలమైంది',
    'instructor.msg.step_completed': 'దశ {step} పూర్తయింది: {title}.',
    'instructor.msg.failed_to_do': '{action} చేయడంలో విఫలమైంది.',
    'instructor.msg.step_required_title': 'దశ అవసరం',
    'instructor.dialog.filter.excel': 'Excel ఫైల్స్ (*.xlsx)',
    'instructor.dialog.filter.excel_open': 'Excel ఫైల్స్ (*.xlsx *.xlsm *.xls)',
    'instructor.dialog.step1.title': 'కోర్సు వివరాల టెంప్లేట్\\u200cను సేవ్ చేయండి',
    'instructor.dialog.step1.default_name': 'course_details_template.xlsx',
    'instructor.dialog.step2.title': 'కోర్సు వివరాల ఫైల్\\u200cని ఎంచుకోండి',
    'instructor.dialog.step1.prepare.title': 'మార్కుల టెంప్లేట్\\u200cను సేవ్ చేయండి',
    'instructor.dialog.step1.prepare.default_name': 'marks_template.xlsx',
    'instructor.dialog.step2.upload.title': 'నింపిన మార్కుల ఫైల్\\u200cని ఎంచుకోండి',
    'instructor.dialog.step2.generate.title': 'తుది CO నివేదికను సేవ్ చేయండి',
    'instructor.status.step1_selected': 'టెంప్లేట్ డౌన్\\u200cలోడ్ మార్గం ఎంచుకోబడింది.',
    'instructor.status.step1_validated': 'కోర్సు వివరాలు అప్\\u200cలోడ్ చేయబడ్డాయి మరియు ధృవీకరించబడ్డాయి. మీరు ఇప్పుడు మార్కుల టెంప్లేట్\\u200cను సిద్ధం చేయవచ్చు.',
    'instructor.status.step1_prepared': 'మార్కుల టెంప్లేట్ రూపొందించబడింది.',
    'instructor.status.step1_changed': 'కోర్సు వివరాలు మారాయి. తదుపరి దశలను మళ్లీ అమలు చేయండి.',
    'instructor.status.step2_uploaded_filled': 'నింపిన మార్కులు అప్\\u200cలోడ్ చేయబడ్డాయి.',
    'instructor.status.step2_changed_filled': 'నింపిన మార్కులు మారాయి. తుది నివేదికను మళ్లీ రూపొందించండి.',
    'instructor.status.step2_generated': 'తుది CO నివేదిక మార్గం ఎంచుకోబడింది.',
    'instructor.status.operation_cancelled': 'ఆపరేషన్ రద్దు చేయబడింది.',
    'instructor.status.step1_drop_browse_requested': 'డ్రాగ్-అండ్-డ్రాప్ విడ్జెట్ నుండి కోర్సు వివరాల ఫైల్ ఎంపిక అభ్యర్థించబడింది.',
    'instructor.status.step1_drop_files_dropped': 'కోర్సు వివరాల విడ్జెట్‌లో {count} ఫైల్(లు) డ్రాప్ చేయబడ్డాయి.',
    'instructor.status.step1_drop_files_changed': 'కోర్సు వివరాల విడ్జెట్‌లో ఇప్పుడు {count} ఫైల్(లు) ఉన్నాయి.',
    'instructor.status.step1_drop_files_rejected': 'కోర్సు వివరాల విడ్జెట్‌లో డ్రాప్ చేసిన {count} ఫైల్(లు) తిరస్కరించబడ్డాయి.',
    'instructor.status.step2_drop_browse_requested': 'Filled marks browse requested from drag-and-drop widget.',
    'instructor.status.step2_drop_files_dropped': '{count} file(s) dropped into filled marks widget.',
    'instructor.status.step2_drop_files_changed': 'Filled marks widget now has {count} file(s).',
    'instructor.status.step2_drop_files_rejected': '{count} dropped file(s) were rejected by filled marks widget.',
    'instructor.status.step1_validating_progress': 'Validating course template files: {processed}/{total}.',
    'instructor.status.step1_validated_progress': 'Validated valid files: {valid}/{total}.',
    'instructor.status.step1_prepare_progress': 'Processed marks templates: {processed}/{total}.',
    'instructor.step1.drop.summary': 'ఫైల్‌లు: {count}',
    'instructor.toast.step1_validation_summary': 'Validation complete: {valid} valid, {invalid} invalid, {mismatched} wrong template, {duplicates} duplicate input.',
    'instructor.toast.step1_prepare_no_outputs': 'No output files selected for marks template generation.',
    'instructor.toast.step1_prepare_summary': 'Marks template generation complete: processed {processed}/{total}, generated {generated}, failed {failed}, skipped {skipped}.',
    'instructor.log.title': 'కార్యాచరణ లాగ్',
    'instructor.log.ready': 'కార్యాచరణ లాగ్ ప్రారంభించబడింది.',
    'instructor.log.completed_process': '{process} విజయవంతంగా పూర్తయింది.',
    'instructor.log.error_while_process': '{process} సమయంలో లోపం సంభవించింది.',
    'instructor.log.process.generate_course_details_template': 'కోర్సు వివరాల టెంప్లేట్\\u200cను రూపొందిస్తోంది',
    'instructor.log.process.validate_course_details_workbook': 'అప్\\u200cలోడ్ చేసిన కోర్సు వివరాల వర్క్\\u200cబుక్\\u200cని ధృవీకరిస్తోంది',
    'instructor.log.process.generate_marks_template': 'మార్కుల టెంప్లేట్\\u200cను రూపొందించడం',
    'instructor.log.process.upload_filled_marks_workbook': 'నిండిన మార్కుల వర్క్\\u200cబుక్\\u200cని అప్\\u200cలోడ్ చేస్తోంది',
    'instructor.log.process.generate_final_co_report': 'తుది CO నివేదికను రూపొందిస్తోంది',
    'instructor.validation.xlsxwriter_missing': 'xlsxwriter ఇన్\\u200cస్టాల్ చేయబడలేదు. కోర్సు టెంప్లేట్\\u200cలను రూపొందించడానికి దీన్ని ఇన్\\u200cస్టాల్ చేయండి.',
    'instructor.validation.sheet_single_header_row': "షీట్ '{sheet_name}' ఖచ్చితంగా ఒక హెడర్ అడ్డు వరుసను నిర్వచించాలి.",
    'instructor.system.template_generate_failed': "'{output}' వద్ద కోర్సు వివరాల టెంప్లేట్\\u200cను రూపొందించడంలో విఫలమైంది.",
    'instructor.validation.unknown_template': "తెలియని వర్క్\\u200cబుక్ టెంప్లేట్ '{template_id}'. అందుబాటులో ఉన్న టెంప్లేట్\\u200cలు: {available}.",
    'instructor.validation.invalid_sheet_name': 'చెల్లని షీట్ పేరు.',
    'instructor.validation.headers_empty': "'{sheet_name}' షీట్ కోసం శీర్షికలు ఖాళీగా ఉండకూడదు.",
    'instructor.validation.headers_unique': "'{sheet_name}' షీట్ కోసం హెడ్\\u200cలు తప్పనిసరిగా ప్రత్యేకంగా ఉండాలి.",
    'instructor.validation.row_length_mismatch': "'{sheet_name}'లో అడ్డు వరుస {row} పొడవు అసమతుల్యత: ఊహించినది {expected}, {found} వచ్చింది.",
    'instructor.validation.openpyxl_missing': 'openpyxl ఇన్\\u200cస్టాల్ చేయబడలేదు. అప్\\u200cలోడ్ చేసిన కోర్సు వివరాలను ధృవీకరించడానికి దీన్ని ఇన్\\u200cస్టాల్ చేయండి.',
    'instructor.validation.workbook_not_found': 'కోర్సు వివరాల వర్క్\u200cబుక్ కనుగొనబడలేదు: {workbook}',
    'instructor.validation.workbook_open_failed': "కోర్సు వివరాల వర్క్\u200cబుక్ '{workbook}' తెరవడం సాధ్యం కాలేదు.",
    'instructor.validation.system_sheet_missing': "అప్\\u200cలోడ్ చేసిన వర్క్\\u200cబుక్\\u200cలో అవసరమైన సిస్టమ్ షీట్ '{sheet}' లేదు.",
    'instructor.validation.system_hash_missing_template_id_header': 'చెల్లని సిస్టమ్ హాష్ షీట్ ఫార్మాట్: Template_ID హెడర్ లేదు.',
    'instructor.validation.system_hash_missing_template_hash_header': 'చెల్లని సిస్టమ్ హాష్ షీట్ ఫార్మాట్: Template_Hash హెడర్ లేదు.',
    'instructor.validation.system_hash_template_id_missing': 'సిస్టమ్ హాష్ షీట్\\u200cలో Template_ID లేదు.',
    'instructor.validation.system_hash_mismatch': 'టెంప్లేట్ హాష్ సరిపోలలేదు. దయచేసి చెల్లుబాటు అయ్యే జనరేట్ టెంప్లేట్\\u200cని ఉపయోగించండి.',
    'instructor.validation.workbook_sheet_mismatch': "వర్క్\\u200cబుక్ షీట్\\u200cలు టెంప్లేట్ '{template_id}'తో సరిపోలడం లేదు. అంచనా వేయబడింది: {expected}. కనుగొనబడింది: {found}.",
    'instructor.validation.header_mismatch': "'{sheet_name}' షీట్\\u200cలో హెడర్ సరిపోలలేదు. అంచనా వేయబడింది: {expected}.",
    'instructor.validation.unexpected_header': "నిలువు వరుస {col} వద్ద '{sheet_name}' షీట్\\u200cలో ఊహించని హెడర్.",
    'instructor.validation.validator_missing': "'{template_id}' టెంప్లేట్ కోసం వాలిడేటర్ అమలు చేయబడలేదు.",
    'instructor.validation.course_metadata_field_empty': 'కోర్స్_మెటాడేటా అడ్డు వరుస {row}: ఫీల్డ్ ఖాళీగా ఉండకూడదు.',
    'instructor.validation.course_metadata_duplicate_field': "కోర్స్_మెటాడేటా అడ్డు వరుస {row}: నకిలీ ఫీల్డ్ '{field}'.",
    'instructor.validation.course_metadata_unknown_field': "కోర్స్_మెటాడేటా అడ్డు వరుస {row}: తెలియని ఫీల్డ్ '{field}'.",
    'instructor.validation.course_metadata_value_required': "కోర్స్_మెటాడేటా అడ్డు వరుస {row}: '{field}'కి విలువ అవసరం.",
    'instructor.validation.course_metadata_missing_fields': 'కోర్స్_మెటాడేటాలో అవసరమైన ఫీల్డ్\u200cలు లేవు: {fields}.',
    'instructor.validation.course_metadata_field_must_be_int': "Course_Metadata ఫీల్డ్ '{field}' తప్పనిసరిగా పూర్ణాంకం అయి ఉండాలి.",
    'instructor.validation.course_metadata_field_must_be_non_empty_str': "Course_Metadata ఫీల్డ్ '{field}' తప్పనిసరిగా ఖాళీ కాని స్ట్రింగ్ అయి ఉండాలి.",
    'instructor.validation.course_metadata_total_outcomes_invalid': "కోర్స్_మెటాడేటా ఫీల్డ్ 'టోటల్_అవుట్\\u200cకమ్స్' తప్పనిసరిగా పూర్ణాంకం > 0 అయి ఉండాలి.",
    'instructor.validation.yes_no_required': "{sheet_name} అడ్డు వరుస {row}: '{field}' తప్పనిసరిగా అవును లేదా కాదు.",
    'instructor.validation.assessment_component_required_one': 'Assessment_Config తప్పనిసరిగా కనీసం ఒక భాగాన్ని కలిగి ఉండాలి.',
    'instructor.validation.assessment_component_required': 'Assessment_Config అడ్డు వరుస {row}: భాగం అవసరం.',
    'instructor.validation.assessment_component_duplicate': "Assessment_Config అడ్డు వరుస {row}: నకిలీ భాగం '{component}'.",
    'instructor.validation.assessment_weight_numeric': 'Assessment_Config అడ్డు వరుస {row}: బరువు (%) తప్పనిసరిగా సంఖ్యాపరంగా ఉండాలి.',
    'instructor.validation.assessment_direct_missing': 'Assessment_Config తప్పనిసరిగా కనీసం ఒక ప్రత్యక్ష భాగాన్ని కలిగి ఉండాలి.',
    'instructor.validation.assessment_indirect_missing': 'Assessment_Config తప్పనిసరిగా కనీసం ఒక పరోక్ష భాగాన్ని కలిగి ఉండాలి.',
    'instructor.validation.assessment_direct_total_invalid': 'Assessment_Config డైరెక్ట్ కాంపోనెంట్ బరువులు తప్పనిసరిగా 100 ఉండాలి. కనుగొనబడింది: {found}.',
    'instructor.validation.assessment_indirect_total_invalid': 'Assessment_Config పరోక్ష కాంపోనెంట్ బరువులు తప్పనిసరిగా మొత్తం 100 ఉండాలి. కనుగొనబడింది: {found}.',
    'instructor.validation.question_map_row_required_one': 'Question_Map తప్పనిసరిగా కనీసం ఒక ప్రశ్న అడ్డు వరుసను కలిగి ఉండాలి.',
    'instructor.validation.question_component_required': 'Question_Map అడ్డు వరుస {row}: భాగం అవసరం.',
    'instructor.validation.question_component_unknown': "Question_Map అడ్డు వరుస {row}: తెలియని భాగం '{component}'.",
    'instructor.validation.question_label_required': 'Question_Map అడ్డు వరుస {row}: Q_No/Rubric_Parameter తప్పనిసరి.',
    'instructor.validation.question_max_marks_numeric': 'Question_Map అడ్డు వరుస {row}: Max_Marks తప్పనిసరిగా సంఖ్యాపరంగా ఉండాలి.',
    'instructor.validation.question_max_marks_positive': 'Question_Map అడ్డు వరుస {row}: Max_Marks తప్పనిసరిగా సున్నా కంటే ఎక్కువగా ఉండాలి.',
    'instructor.validation.question_co_required': 'Question_Map అడ్డు వరుస {row}: CO తప్పనిసరిగా కనీసం ఒక విలువను కలిగి ఉండాలి.',
    'instructor.validation.question_co_no_repeat': 'Question_Map అడ్డు వరుస {row}: CO విలువలు పునరావృతం కావు.',
    'instructor.validation.question_co_out_of_range': 'Question_Map అడ్డు వరుస {row}: CO విలువ 1..{total_outcomes} పరిధిలో లేదు.',
    'instructor.validation.question_co_wise_requires_one': "Question_Map అడ్డు వరుస {row}: కాంపోనెంట్ '{component}'కి ప్రతి ప్రశ్నకు ఖచ్చితంగా ఒక CO అవసరం.",
    'instructor.validation.question_duplicate_for_component': "Question_Map అడ్డు వరుస {row}: '{component}' భాగం కోసం నకిలీ ప్రశ్న '{question}'.",
    'instructor.validation.students_row_required_one': 'విద్యార్థుల షీట్ తప్పనిసరిగా కనీసం ఒక విద్యార్థి వరుసను కలిగి ఉండాలి.',
    'instructor.validation.students_reg_and_name_required': 'విద్యార్థుల వరుస {row}: Reg_No మరియు Student_Name రెండూ అవసరం.',
    'instructor.validation.students_duplicate_reg_no': "విద్యార్థుల వరుస {row}: నకిలీ Reg_No '{reg_no}'.",
    'instructor.validation.step2.layout_sheet_missing': "నిండిన మార్కుల వర్క్\\u200cబుక్\\u200cలో అవసరమైన లేఅవుట్ షీట్ '{sheet}' లేదు.",
    'instructor.validation.step2.layout_header_mismatch': "{column} వద్ద చెల్లని లేఅవుట్ షీట్ హెడర్. ఆశించిన '{expected}'.",
    'instructor.validation.step2.layout_manifest_missing': 'సిస్టమ్ లేఅవుట్ షీట్\\u200cలో లేఅవుట్ మానిఫెస్ట్ లేదా లేఅవుట్ హాష్ లేదు.',
    'instructor.validation.step2.layout_hash_mismatch': 'లేఅవుట్ హాష్ సరిపోలలేదు. దయచేసి మార్పులు చేయని, సిస్టమ్ జనరేట్ చేసిన మార్కుల టెంప్లేట్\u200cనే ఉపయోగించండి.',
    'instructor.validation.step2.layout_manifest_json_invalid': 'లేఅవుట్ మానిఫెస్ట్ JSON చెల్లదు.',
    'instructor.validation.step2.template_validator_missing': "'{template_id}' టెంప్లేట్ కోసం దశ 2 వాలిడేటర్ అందుబాటులో లేదు.",
    'instructor.validation.step2.manifest_root_invalid': 'లేఅవుట్ మానిఫెస్ట్ రూట్ తప్పనిసరిగా ఆబ్జెక్ట్ అయి ఉండాలి.',
    'instructor.validation.step2.manifest_structure_invalid': "లేఅవుట్ మానిఫెస్ట్ తప్పనిసరిగా 'షీట్_ఆర్డర్' మరియు 'షీట్\\u200cలు' రెండింటినీ కలిగి ఉండాలి.",
    'instructor.validation.step2.sheet_order_mismatch': 'నింపిన మార్కుల షీట్\\u200cలు సరిపోలలేదు. ఆశించిన ఆర్డర్: {expected}. కనుగొనబడింది: {found}.',
    'instructor.validation.step2.manifest_sheet_spec_invalid': 'లేఅవుట్ మానిఫెస్ట్ చెల్లని షీట్ స్పెసిఫికేషన్\\u200cను కలిగి ఉంది.',
    'instructor.validation.step2.sheet_missing': "వర్క్\\u200cబుక్\\u200cలో ఆశించిన షీట్ '{sheet_name}' లేదు.",
    'instructor.validation.step2.header_row_invalid': "షీట్ '{sheet_name}' చెల్లని హెడర్ అడ్డు వరుస మెటాడేటాను కలిగి ఉంది: {header_row}.",
    'instructor.validation.step2.headers_missing': "లేఅవుట్ మానిఫెస్ట్\\u200cలో '{sheet_name}' షీట్ ఆశించిన హెడర్ నిర్వచనాలు లేవు.",
    'instructor.validation.step2.anchor_spec_invalid': "లేఅవుట్ మానిఫెస్ట్\\u200cలో '{sheet_name}' షీట్ చెల్లని యాంకర్ స్పెసిఫికేషన్\\u200cను కలిగి ఉంది.",
    'instructor.validation.step2.formula_anchor_spec_invalid': "లేఅవుట్ మానిఫెస్ట్\\u200cలో '{sheet_name}' షీట్ చెల్లని ఫార్ములా యాంకర్ స్పెసిఫికేషన్\\u200cను కలిగి ఉంది.",
    'instructor.validation.step2.header_row_mismatch': "అడ్డు వరుస {row} వద్ద షీట్ '{sheet_name}' హెడర్ సరిపోలలేదు. అంచనా వేయబడింది: {expected}.",
    'instructor.validation.step2.anchor_value_mismatch': "షీట్ '{sheet_name}' సెల్ {cell} సవరించబడింది. ఆశించిన '{expected}', '{found}' కనుగొనబడింది.",
    'instructor.validation.step2.formula_mismatch': "{cell} వద్ద షీట్ '{sheet_name}' ఫార్ములా సవరించబడింది.",
    'instructor.validation.step2.no_component_sheets': 'పూరించిన మార్కుల వర్క్\\u200cబుక్\\u200cలో కాంపోనెంట్ మార్క్-ఎంట్రీ షీట్\\u200cలు ఏవీ కనుగొనబడలేదు.',
    'instructor.validation.step2.mark_entry_empty': "షీట్ '{sheet_name}' {cell} వద్ద ఖాళీ మార్క్-ఎంట్రీ సెల్\\u200cను కలిగి ఉంది. అప్\\u200cలోడ్ చేయడానికి ముందు అన్ని మార్కులను పూరించండి.",
    'instructor.validation.step2.mark_value_invalid': "షీట్ '{sheet_name}' సెల్ {cell} చెల్లని గుర్తు విలువ '{value}'ని కలిగి ఉంది. అనుమతించబడినది: A/a లేదా {minimum} మరియు {maximum} మధ్య సంఖ్య.",
    'instructor.validation.step2.mark_precision_invalid': "షీట్ '{sheet_name}' సెల్ {cell} '{value}'లో చాలా దశాంశ స్థానాలను కలిగి ఉంది. అనుమతించబడిన గరిష్టం {decimals}.",
    'instructor.validation.step2.indirect_mark_must_be_integer': "షీట్ '{sheet_name}' సెల్ {cell} చెల్లని పరోక్ష గుర్తు '{value}'ని కలిగి ఉంది. పూర్ణాంకం లైకర్ట్ విలువను ఉపయోగించండి.",
    'instructor.validation.step2.absence_policy_violation': "షీట్ '{sheet_name}' అడ్డు వరుస {row} {range}లో మిశ్రమ లేకపోవడం మరియు సంఖ్యా నమోదులను కలిగి ఉంది. అన్ని A/a లేదా అన్ని సంఖ్యా మార్కులను నమోదు చేయండి.",
    'instructor.validation.step2.total_formula_mismatch': "షీట్ '{sheet_name}' మొత్తం ఫార్ములా {cell} వద్ద సవరించబడింది.",
    'instructor.validation.step2.co_formula_mismatch': "షీట్ '{sheet_name}' CO స్ప్లిట్ ఫార్ములా {cell} వద్ద సవరించబడింది.",
    'instructor.validation.step2.structure_snapshot_missing': "లేఅవుట్ మానిఫెస్ట్\\u200cలో '{sheet_name}' షీట్ మార్క్-స్ట్రక్చర్ మెటాడేటా లేదు.",
    'instructor.validation.step2.structure_snapshot_mismatch': "షీట్ '{sheet_name}' మార్క్-స్ట్రక్చర్ సెల్ {cell} సవరించబడింది.",
    'instructor.validation.step2.student_identity_spec_invalid': "లేఅవుట్ మానిఫెస్ట్\\u200cలో '{sheet_name}' షీట్ చెల్లని విద్యార్థి గుర్తింపు మెటాడేటాను కలిగి ఉంది.",
    'instructor.validation.step2.student_identity_mismatch': "షీట్ '{sheet_name}' విద్యార్థి రెగ్. సంఖ్య/పేరు అడ్డు వరుసలు సవరించబడ్డాయి.",
    'instructor.validation.step2.student_reg_duplicate': "షీట్ '{sheet_name}'లో నకిలీ విద్యార్థి రెగ్. నం. '{reg_no}'.",
    'instructor.validation.step2.student_identity_cross_sheet_mismatch': "విద్యార్థి రెజి. '{sheet_name}' షీట్\\u200cలోని సంఖ్య/పేరు అడ్డు వరుసలు '{reference_sheet}' షీట్\\u200cతో సరిపోలడం లేదు.",
    'instructor.validation.final_report.layout_manifest_invalid': 'తుది నివేదిక రూపొందించడం విఫలమైంది: లేఅవుట్ మానిఫెస్ట్ చెల్లదు.',
    'instructor.validation.final_report.direct_component_sheet_missing': "తుది నివేదిక రూపొందించడం విఫలమైంది: '{component}' కోసం డైరెక్ట్ కాంపోనెంట్ షీట్ లేదు.",
    'instructor.validation.final_report.direct_component_marks_shape_invalid': "తుది నివేదిక రూపొందించడం విఫలమైంది: '{component}' భాగం కోసం చెల్లని మార్కుల ఆకారం.",
    'instructor.validation.final_report.no_direct_components': 'తుది నివేదిక రూపొందించడం విఫలమైంది: ప్రత్యక్ష భాగాలు ఏవీ కనుగొనబడలేదు.',
    'coordinator.title': 'కోర్సు అటైన్‌మెంట్',
    'coordinator.drop_hint': 'ఇన్\u200cస్ట్రక్టర్ మాడ్యూల్ నుంచి రూపొందించిన తుది CO రిపోర్ట్ వర్క్\u200cబుక్\u200cలను ఇక్కడ సేకరించండి.',
    'coordinator.calculate': 'CO సాధనను లెక్కించండి',
    'coordinator.thresholds.title': 'CO సాధన పరిమితులు',
    'coordinator.thresholds.description': (
        '- L1 పరిమితి అంటే కోర్సు పాస్ మార్క్ లేదా గత నియమావళిలో ఆఫర్ చేసిన 3 బ్యాచ్‌ల కోర్సు సగటు.\n'
        '- L2 పరిమితి అంటే ఫస్ట్ క్లాస్.\n'
        '- L3 పరిమితి అంటే డిస్టింక్షన్ క్లాస్.'
    ),
    'coordinator.thresholds.l1.label': 'L1 పరిమితి:',
    'coordinator.thresholds.l2.label': 'L2 పరిమితి:',
    'coordinator.thresholds.l3.label': 'L3 పరిమితి:',
    'coordinator.thresholds.invalid_rule': 'Threshold rule violated: keep 0 < L1 < L2 < L3 < 100.',
    'coordinator.dialog.title': 'ఎక్సెల్ ఫైల్స్ ఎంచుకోండి',
    'coordinator.links.uploaded_report': 'తుది CO నివేదిక అప్\\u200cలోడ్ చేయబడింది',
    'coordinator.links.downloaded_output': 'డౌన్\u200cలోడ్ చేసిన అవుట్\u200cపుట్',
    'coordinator.summary': 'ఫైల్\\u200cలు: {count}',
    'coordinator.file.remove_fallback': 'తొలగించు',
    'coordinator.file.remove_tooltip': 'ఫైల్ తొలగించు',
    'coordinator.clear_all': 'అన్నీ క్లియర్ చేయండి',
    'coordinator.status.added': '{added} ఫైల్(లు) జోడించబడ్డాయి. మొత్తం: {total}.',
    'coordinator.duplicate.title': 'ఫైల్ ఇప్పటికే ఉంది',
    'coordinator.duplicate.body': '{count} నకిలీ ఫైల్(లు) ఇప్పటికే జాబితాలో ఉన్నందున దాటవేయబడ్డాయి.',
    'coordinator.invalid_final_report.title': 'చెల్లని తుది CO నివేదిక',
    'coordinator.invalid_final_report.body': 'బోధకుడు దశ 3 నుండి రూపొందించబడిన తుది CO నివేదిక వర్క్\\u200cబుక్\\u200cలు మాత్రమే అనుమతించబడతాయి.\\n\\n{files}',
    'coordinator.status.ignored': '{count} ఫైల్(లు) పట్టించుకోలేదు (మద్దతు లేని రకం, ఫైల్ దొరకకపోవడం, నకిలీ లేదా చెల్లని తుది నివేదిక వర్క్\u200cబుక్).',
    'coordinator.status.removed': '{count} ఫైల్(లు) తీసివేయబడ్డాయి.',
    'coordinator.status.cleared': '{count} ఫైల్(లు) క్లియర్ చేయబడ్డాయి.',
    'coordinator.status.processing_started': 'ఎంచుకున్న ఫైల్\\u200cలను ప్రాసెస్ చేస్తోంది...',
    'coordinator.status.queued': 'ప్రస్తుత ప్రాసెసింగ్ నడుస్తున్నప్పుడు {count} ఫైల్(లు) క్యూలో ఉన్నాయి.',
    'coordinator.status.operation_cancelled': 'కోఆర్డినేటర్ ప్రాసెసింగ్ రద్దు చేయబడింది.',
    'coordinator.status.processing_failed': 'కోఆర్డినేటర్ ప్రాసెసింగ్ విఫలమైంది.',
    'coordinator.status.processing_completed': 'కోఆర్డినేటర్ ప్రాసెసింగ్ పూర్తయింది.',
    'coordinator.status.calculate_completed': 'CO సాధన గణన పూర్తయింది మరియు అవుట్\\u200cపుట్ వర్క్\\u200cబుక్ రూపొందించబడింది.',
    'coordinator.regno_dedup.title': 'డూప్లికేట్ రిజిస్టర్ నంబర్\\u200cలు తీసివేయబడ్డాయి',
    'coordinator.regno_dedup.body': 'CO సాధన రూపొందిస్తున్నప్పుడు {count} నకిలీ రిజిస్టర్ నంబర్ నమోదులు తొలగించబడ్డాయి.',
    'coordinator.regno_dedup.log_body': '{count} నకిలీ రిజిస్టర్ నంబర్ నమోదులు తొలగించబడ్డాయి:\n{details}',
    'coordinator.regno_dedup.log_detail': 'రెగ్ నంబర్: {reg_no} | వర్క్\u200cషీట్: {worksheet} | వర్క్\u200cబుక్: {workbook}',
    'coordinator.regno_dedup.log_detail_unavailable': 'డూప్లికేట్ ఎంట్రీ వివరాలు అందుబాటులో లేవు.',
}


