ID_COURSE_SETUP = "COURSE_SETUP_V1"
ID_MARKS_ENTRY = "MARKS_ENTRY_V1"

SYSTEM_VERSION = "3.0.0"

SYSTEM_HASH_SHEET_NAME = "__SYSTEM_HASH__"
METADATA_SHEET_NAME = "__METADATA__"

WORKBOOK_PASSWORD = "kare"

DEFAULT_MAX_COL_WIDTH = 50
DEFAULT_MIN_COL_WIDTH = 10
WIDTH_PADDING = 2
